namespace sRT106
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyContract = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyContract = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCmtyContract = new Srvtools.InfoCommand(this.components);
            this.cmdRT1061 = new Srvtools.InfoCommand(this.components);
            this.cmdRT1062 = new Srvtools.InfoCommand(this.components);
            this.cmdRT1063 = new Srvtools.InfoCommand(this.components);
            this.cmdRT1064 = new Srvtools.InfoCommand(this.components);
            this.cmd = new Srvtools.InfoCommand(this.components);
            this.RT1061 = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContract)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContract)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1061)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1062)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1063)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1064)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1061)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT1061";
            service1.NonLogin = false;
            service1.ServiceName = "smRT1061";
            service2.DelegateName = "smRT1062";
            service2.NonLogin = false;
            service2.ServiceName = "smRT1062";
            service3.DelegateName = "smRT1063";
            service3.NonLogin = false;
            service3.ServiceName = "smRT1063";
            service4.DelegateName = "smRT1064";
            service4.NonLogin = false;
            service4.ServiceName = "smRT1064";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyContract
            // 
            this.RTLessorAVSCmtyContract.CacheConnection = false;
            this.RTLessorAVSCmtyContract.CommandText = "SELECT dbo.[RTLessorAVSCmtyContract].* FROM dbo.[RTLessorAVSCmtyContract]";
            this.RTLessorAVSCmtyContract.CommandTimeout = 30;
            this.RTLessorAVSCmtyContract.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyContract.DynamicTableName = false;
            this.RTLessorAVSCmtyContract.EEPAlias = null;
            this.RTLessorAVSCmtyContract.EncodingAfter = null;
            this.RTLessorAVSCmtyContract.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyContract.EncodingConvert = null;
            this.RTLessorAVSCmtyContract.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "CONTRACTNO";
            this.RTLessorAVSCmtyContract.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyContract.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyContract.MultiSetWhere = false;
            this.RTLessorAVSCmtyContract.Name = "RTLessorAVSCmtyContract";
            this.RTLessorAVSCmtyContract.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyContract.SecExcept = null;
            this.RTLessorAVSCmtyContract.SecFieldName = null;
            this.RTLessorAVSCmtyContract.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyContract.SelectPaging = false;
            this.RTLessorAVSCmtyContract.SelectTop = 0;
            this.RTLessorAVSCmtyContract.SiteControl = false;
            this.RTLessorAVSCmtyContract.SiteFieldName = null;
            this.RTLessorAVSCmtyContract.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyContract
            // 
            this.ucRTLessorAVSCmtyContract.AutoTrans = true;
            this.ucRTLessorAVSCmtyContract.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CONTRACTNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "STRDAT";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "CONTDAT";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CONTCNT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ENDDAT";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "CONTRACTOBJ";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "OBJTEL";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "OBJMOBILE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "SIGNDEPT";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "SIGNPERSON";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "REMITBANK1";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "REMITBANK2";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "ACNO";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "AC";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "POWERBILLKIND";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "POWERBILLPAYKIND";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "SCALEAMT";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "PAYKIND";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "PAYCYCLE";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "CLOSEDAT";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "CLOSEUSR";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "CANCELDAT";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CANCELUSR";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "EUSR";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "EDAT";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "UUSR";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "UDAT";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "MEMO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "BATCHNO";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "TARDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "TUSR";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyContract.LogInfo = null;
            this.ucRTLessorAVSCmtyContract.Name = "ucRTLessorAVSCmtyContract";
            this.ucRTLessorAVSCmtyContract.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyContract.SelectCmd = this.RTLessorAVSCmtyContract;
            this.ucRTLessorAVSCmtyContract.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyContract.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyContract.ServerModify = true;
            this.ucRTLessorAVSCmtyContract.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyContract.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyContract.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyContract.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyContract.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCmtyContract
            // 
            this.View_RTLessorAVSCmtyContract.CacheConnection = false;
            this.View_RTLessorAVSCmtyContract.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyContract]";
            this.View_RTLessorAVSCmtyContract.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyContract.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyContract.DynamicTableName = false;
            this.View_RTLessorAVSCmtyContract.EEPAlias = null;
            this.View_RTLessorAVSCmtyContract.EncodingAfter = null;
            this.View_RTLessorAVSCmtyContract.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyContract.EncodingConvert = null;
            this.View_RTLessorAVSCmtyContract.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "COMQ1";
            keyItem4.KeyName = "CONTRACTNO";
            this.View_RTLessorAVSCmtyContract.KeyFields.Add(keyItem3);
            this.View_RTLessorAVSCmtyContract.KeyFields.Add(keyItem4);
            this.View_RTLessorAVSCmtyContract.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyContract.Name = "View_RTLessorAVSCmtyContract";
            this.View_RTLessorAVSCmtyContract.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyContract.SecExcept = null;
            this.View_RTLessorAVSCmtyContract.SecFieldName = null;
            this.View_RTLessorAVSCmtyContract.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyContract.SelectPaging = false;
            this.View_RTLessorAVSCmtyContract.SelectTop = 0;
            this.View_RTLessorAVSCmtyContract.SiteControl = false;
            this.View_RTLessorAVSCmtyContract.SiteFieldName = null;
            this.View_RTLessorAVSCmtyContract.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1061
            // 
            this.cmdRT1061.CacheConnection = false;
            this.cmdRT1061.CommandText = "usp_RTLessorAVSCmtyContractCancel";
            this.cmdRT1061.CommandTimeout = 30;
            this.cmdRT1061.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1061.DynamicTableName = false;
            this.cmdRT1061.EEPAlias = null;
            this.cmdRT1061.EncodingAfter = null;
            this.cmdRT1061.EncodingBefore = "Windows-1252";
            this.cmdRT1061.EncodingConvert = null;
            this.cmdRT1061.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter1.ParameterName = "comq1";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 0;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter2.ParameterName = "CONTRACTNO";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 10;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "usr";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 6;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1061.InfoParameters.Add(infoParameter1);
            this.cmdRT1061.InfoParameters.Add(infoParameter2);
            this.cmdRT1061.InfoParameters.Add(infoParameter3);
            this.cmdRT1061.MultiSetWhere = false;
            this.cmdRT1061.Name = "cmdRT1061";
            this.cmdRT1061.NotificationAutoEnlist = false;
            this.cmdRT1061.SecExcept = null;
            this.cmdRT1061.SecFieldName = null;
            this.cmdRT1061.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1061.SelectPaging = false;
            this.cmdRT1061.SelectTop = 0;
            this.cmdRT1061.SiteControl = false;
            this.cmdRT1061.SiteFieldName = null;
            this.cmdRT1061.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1062
            // 
            this.cmdRT1062.CacheConnection = false;
            this.cmdRT1062.CommandText = "usp_RTLessorAVSCmtyContractFR";
            this.cmdRT1062.CommandTimeout = 30;
            this.cmdRT1062.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1062.DynamicTableName = false;
            this.cmdRT1062.EEPAlias = null;
            this.cmdRT1062.EncodingAfter = null;
            this.cmdRT1062.EncodingBefore = "Windows-1252";
            this.cmdRT1062.EncodingConvert = null;
            this.cmdRT1062.InfoConnection = this.InfoConnection1;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter4.ParameterName = "comq1";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 15;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "CONTRACTNO";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 10;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter6.ParameterName = "usr";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 6;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1062.InfoParameters.Add(infoParameter4);
            this.cmdRT1062.InfoParameters.Add(infoParameter5);
            this.cmdRT1062.InfoParameters.Add(infoParameter6);
            this.cmdRT1062.MultiSetWhere = false;
            this.cmdRT1062.Name = "cmdRT1062";
            this.cmdRT1062.NotificationAutoEnlist = false;
            this.cmdRT1062.SecExcept = null;
            this.cmdRT1062.SecFieldName = null;
            this.cmdRT1062.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1062.SelectPaging = false;
            this.cmdRT1062.SelectTop = 0;
            this.cmdRT1062.SiteControl = false;
            this.cmdRT1062.SiteFieldName = null;
            this.cmdRT1062.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1063
            // 
            this.cmdRT1063.CacheConnection = false;
            this.cmdRT1063.CommandText = "usp_RTLessorAVSCmtyContractCancel";
            this.cmdRT1063.CommandTimeout = 30;
            this.cmdRT1063.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1063.DynamicTableName = false;
            this.cmdRT1063.EEPAlias = null;
            this.cmdRT1063.EncodingAfter = null;
            this.cmdRT1063.EncodingBefore = "Windows-1252";
            this.cmdRT1063.EncodingConvert = null;
            this.cmdRT1063.InfoConnection = this.InfoConnection1;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter7.ParameterName = "comq1";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 0;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "CONTRACTNO";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 10;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "usr";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 6;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1063.InfoParameters.Add(infoParameter7);
            this.cmdRT1063.InfoParameters.Add(infoParameter8);
            this.cmdRT1063.InfoParameters.Add(infoParameter9);
            this.cmdRT1063.MultiSetWhere = false;
            this.cmdRT1063.Name = "cmdRT1063";
            this.cmdRT1063.NotificationAutoEnlist = false;
            this.cmdRT1063.SecExcept = null;
            this.cmdRT1063.SecFieldName = null;
            this.cmdRT1063.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1063.SelectPaging = false;
            this.cmdRT1063.SelectTop = 0;
            this.cmdRT1063.SiteControl = false;
            this.cmdRT1063.SiteFieldName = null;
            this.cmdRT1063.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1064
            // 
            this.cmdRT1064.CacheConnection = false;
            this.cmdRT1064.CommandText = "usp_RTLessorAVSCmtyContractCancelRTN";
            this.cmdRT1064.CommandTimeout = 30;
            this.cmdRT1064.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1064.DynamicTableName = false;
            this.cmdRT1064.EEPAlias = null;
            this.cmdRT1064.EncodingAfter = null;
            this.cmdRT1064.EncodingBefore = "Windows-1252";
            this.cmdRT1064.EncodingConvert = null;
            this.cmdRT1064.InfoConnection = this.InfoConnection1;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter10.ParameterName = "comq1";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 15;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "CONTRACTNO";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 10;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter12.ParameterName = "usr";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 6;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1064.InfoParameters.Add(infoParameter10);
            this.cmdRT1064.InfoParameters.Add(infoParameter11);
            this.cmdRT1064.InfoParameters.Add(infoParameter12);
            this.cmdRT1064.MultiSetWhere = false;
            this.cmdRT1064.Name = "cmdRT1064";
            this.cmdRT1064.NotificationAutoEnlist = false;
            this.cmdRT1064.SecExcept = null;
            this.cmdRT1064.SecFieldName = null;
            this.cmdRT1064.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1064.SelectPaging = false;
            this.cmdRT1064.SelectTop = 0;
            this.cmdRT1064.SiteControl = false;
            this.cmdRT1064.SiteFieldName = null;
            this.cmdRT1064.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmd
            // 
            this.cmd.CacheConnection = false;
            this.cmd.CommandText = "";
            this.cmd.CommandTimeout = 30;
            this.cmd.CommandType = System.Data.CommandType.Text;
            this.cmd.DynamicTableName = false;
            this.cmd.EEPAlias = null;
            this.cmd.EncodingAfter = null;
            this.cmd.EncodingBefore = "Windows-1252";
            this.cmd.EncodingConvert = null;
            this.cmd.InfoConnection = this.InfoConnection1;
            this.cmd.MultiSetWhere = false;
            this.cmd.Name = "cmd";
            this.cmd.NotificationAutoEnlist = false;
            this.cmd.SecExcept = null;
            this.cmd.SecFieldName = null;
            this.cmd.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmd.SelectPaging = false;
            this.cmd.SelectTop = 0;
            this.cmd.SiteControl = false;
            this.cmd.SiteFieldName = null;
            this.cmd.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT1061
            // 
            this.RT1061.CacheConnection = false;
            this.RT1061.CommandText = resources.GetString("RT1061.CommandText");
            this.RT1061.CommandTimeout = 30;
            this.RT1061.CommandType = System.Data.CommandType.Text;
            this.RT1061.DynamicTableName = false;
            this.RT1061.EEPAlias = null;
            this.RT1061.EncodingAfter = null;
            this.RT1061.EncodingBefore = "Windows-1252";
            this.RT1061.EncodingConvert = null;
            this.RT1061.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "COMQ1";
            keyItem6.KeyName = "CONTRACTNO";
            keyItem7.KeyName = "ENTRYNO";
            this.RT1061.KeyFields.Add(keyItem5);
            this.RT1061.KeyFields.Add(keyItem6);
            this.RT1061.KeyFields.Add(keyItem7);
            this.RT1061.MultiSetWhere = false;
            this.RT1061.Name = "RT1061";
            this.RT1061.NotificationAutoEnlist = false;
            this.RT1061.SecExcept = null;
            this.RT1061.SecFieldName = null;
            this.RT1061.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT1061.SelectPaging = false;
            this.RT1061.SelectTop = 0;
            this.RT1061.SiteControl = false;
            this.RT1061.SiteFieldName = null;
            this.RT1061.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "RT106";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "getFix()";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 2;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "CONTRACTNO";
            this.autoNumber1.UpdateComp = this.ucRTLessorAVSCmtyContract;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContract)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContract)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1061)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1062)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1063)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1064)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1061)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyContract;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyContract;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyContract;
        private Srvtools.InfoCommand cmdRT1061;
        private Srvtools.InfoCommand cmdRT1062;
        private Srvtools.InfoCommand cmdRT1063;
        private Srvtools.InfoCommand cmdRT1064;
        private Srvtools.InfoCommand cmd;
        private Srvtools.InfoCommand RT1061;
        private Srvtools.AutoNumber autoNumber1;
    }
}
