namespace sRT102
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyContract = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyContract = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCmtyContractLog = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyContractLog = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCmtyContract = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCmtyContractLog = new Srvtools.InfoCommand(this.components);
            this.ucRT102 = new Srvtools.InfoCommand(this.components);
            this.ucRT1021 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContract)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContractLog)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContract)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContractLog)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucRT102)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucRT1021)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT1021";
            service1.NonLogin = false;
            service1.ServiceName = "smRT1021";
            this.serviceManager1.ServiceCollection.Add(service1);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyContract
            // 
            this.RTLessorAVSCmtyContract.CacheConnection = false;
            this.RTLessorAVSCmtyContract.CommandText = "SELECT dbo.[RTLessorAVSCmtyContract].* FROM dbo.[RTLessorAVSCmtyContract]";
            this.RTLessorAVSCmtyContract.CommandTimeout = 30;
            this.RTLessorAVSCmtyContract.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyContract.DynamicTableName = false;
            this.RTLessorAVSCmtyContract.EEPAlias = null;
            this.RTLessorAVSCmtyContract.EncodingAfter = null;
            this.RTLessorAVSCmtyContract.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyContract.EncodingConvert = null;
            this.RTLessorAVSCmtyContract.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "CONTRACTNO";
            this.RTLessorAVSCmtyContract.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyContract.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyContract.MultiSetWhere = false;
            this.RTLessorAVSCmtyContract.Name = "RTLessorAVSCmtyContract";
            this.RTLessorAVSCmtyContract.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyContract.SecExcept = null;
            this.RTLessorAVSCmtyContract.SecFieldName = null;
            this.RTLessorAVSCmtyContract.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyContract.SelectPaging = false;
            this.RTLessorAVSCmtyContract.SelectTop = 0;
            this.RTLessorAVSCmtyContract.SiteControl = false;
            this.RTLessorAVSCmtyContract.SiteFieldName = null;
            this.RTLessorAVSCmtyContract.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyContract
            // 
            this.ucRTLessorAVSCmtyContract.AutoTrans = true;
            this.ucRTLessorAVSCmtyContract.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "CONTRACTNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "STRDAT";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "CONTDAT";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "CONTCNT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ENDDAT";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "CONTRACTOBJ";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "OBJTEL";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "OBJMOBILE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "SIGNDEPT";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "SIGNPERSON";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "REMITBANK1";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "REMITBANK2";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "ACNO";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "AC";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "POWERBILLKIND";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "POWERBILLPAYKIND";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "SCALEAMT";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "PAYKIND";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "PAYCYCLE";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "CLOSEDAT";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "CLOSEUSR";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "CANCELDAT";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CANCELUSR";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "EUSR";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "EDAT";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "UUSR";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "UDAT";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "MEMO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "BATCHNO";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "TARDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "TUSR";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyContract.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyContract.LogInfo = null;
            this.ucRTLessorAVSCmtyContract.Name = "ucRTLessorAVSCmtyContract";
            this.ucRTLessorAVSCmtyContract.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyContract.SelectCmd = this.RTLessorAVSCmtyContract;
            this.ucRTLessorAVSCmtyContract.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyContract.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyContract.ServerModify = true;
            this.ucRTLessorAVSCmtyContract.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyContract.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyContract.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyContract.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyContract.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCmtyContractLog
            // 
            this.RTLessorAVSCmtyContractLog.CacheConnection = false;
            this.RTLessorAVSCmtyContractLog.CommandText = "SELECT dbo.[RTLessorAVSCmtyContractLog].* FROM dbo.[RTLessorAVSCmtyContractLog]";
            this.RTLessorAVSCmtyContractLog.CommandTimeout = 30;
            this.RTLessorAVSCmtyContractLog.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyContractLog.DynamicTableName = false;
            this.RTLessorAVSCmtyContractLog.EEPAlias = null;
            this.RTLessorAVSCmtyContractLog.EncodingAfter = null;
            this.RTLessorAVSCmtyContractLog.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyContractLog.EncodingConvert = null;
            this.RTLessorAVSCmtyContractLog.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "COMQ1";
            keyItem4.KeyName = "CONTRACTNO";
            keyItem5.KeyName = "ENTRYNO";
            this.RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem3);
            this.RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem4);
            this.RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem5);
            this.RTLessorAVSCmtyContractLog.MultiSetWhere = false;
            this.RTLessorAVSCmtyContractLog.Name = "RTLessorAVSCmtyContractLog";
            this.RTLessorAVSCmtyContractLog.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyContractLog.SecExcept = null;
            this.RTLessorAVSCmtyContractLog.SecFieldName = null;
            this.RTLessorAVSCmtyContractLog.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyContractLog.SelectPaging = false;
            this.RTLessorAVSCmtyContractLog.SelectTop = 0;
            this.RTLessorAVSCmtyContractLog.SiteControl = false;
            this.RTLessorAVSCmtyContractLog.SiteFieldName = null;
            this.RTLessorAVSCmtyContractLog.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyContractLog
            // 
            this.ucRTLessorAVSCmtyContractLog.AutoTrans = true;
            this.ucRTLessorAVSCmtyContractLog.ExceptJoin = false;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "COMQ1";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "CONTRACTNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "ENTRYNO";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CHGDAT";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CHGCODE";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CHGUSR";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "STRDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "CONTDAT";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CONTCNT";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "ENDDAT";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "CONTRACTOBJ";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "OBJTEL";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "OBJMOBILE";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "SIGNDEPT";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "SIGNPERSON";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "REMITBANK1";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "REMITBANK2";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "ACNO";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "AC";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "POWERBILLKIND";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "POWERBILLPAYKIND";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "SCALEAMT";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "PAYKIND";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "PAYCYCLE";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "CLOSEDAT";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CharSetNull = false;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "CLOSEUSR";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CharSetNull = false;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "CANCELDAT";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CharSetNull = false;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "CANCELUSR";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CharSetNull = false;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "EUSR";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CharSetNull = false;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "EDAT";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CharSetNull = false;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "UUSR";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CharSetNull = false;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "UDAT";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CharSetNull = false;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "MEMO";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CharSetNull = false;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "BATCHNO";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CharSetNull = false;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "TARDAT";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CharSetNull = false;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "TUSR";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr49);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr50);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr51);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr52);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr53);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr54);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr55);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr56);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr57);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr58);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr59);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr60);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr61);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr62);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr63);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr64);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr65);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr66);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr67);
            this.ucRTLessorAVSCmtyContractLog.FieldAttrs.Add(fieldAttr68);
            this.ucRTLessorAVSCmtyContractLog.LogInfo = null;
            this.ucRTLessorAVSCmtyContractLog.Name = "ucRTLessorAVSCmtyContractLog";
            this.ucRTLessorAVSCmtyContractLog.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyContractLog.SelectCmd = this.RTLessorAVSCmtyContractLog;
            this.ucRTLessorAVSCmtyContractLog.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyContractLog.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyContractLog.ServerModify = true;
            this.ucRTLessorAVSCmtyContractLog.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyContractLog.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyContractLog.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyContractLog.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyContractLog.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCmtyContract
            // 
            this.View_RTLessorAVSCmtyContract.CacheConnection = false;
            this.View_RTLessorAVSCmtyContract.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyContract]";
            this.View_RTLessorAVSCmtyContract.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyContract.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyContract.DynamicTableName = false;
            this.View_RTLessorAVSCmtyContract.EEPAlias = null;
            this.View_RTLessorAVSCmtyContract.EncodingAfter = null;
            this.View_RTLessorAVSCmtyContract.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyContract.EncodingConvert = null;
            this.View_RTLessorAVSCmtyContract.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "COMQ1";
            keyItem7.KeyName = "CONTRACTNO";
            this.View_RTLessorAVSCmtyContract.KeyFields.Add(keyItem6);
            this.View_RTLessorAVSCmtyContract.KeyFields.Add(keyItem7);
            this.View_RTLessorAVSCmtyContract.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyContract.Name = "View_RTLessorAVSCmtyContract";
            this.View_RTLessorAVSCmtyContract.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyContract.SecExcept = null;
            this.View_RTLessorAVSCmtyContract.SecFieldName = null;
            this.View_RTLessorAVSCmtyContract.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyContract.SelectPaging = false;
            this.View_RTLessorAVSCmtyContract.SelectTop = 0;
            this.View_RTLessorAVSCmtyContract.SiteControl = false;
            this.View_RTLessorAVSCmtyContract.SiteFieldName = null;
            this.View_RTLessorAVSCmtyContract.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCmtyContractLog
            // 
            this.View_RTLessorAVSCmtyContractLog.CacheConnection = false;
            this.View_RTLessorAVSCmtyContractLog.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyContractLog]";
            this.View_RTLessorAVSCmtyContractLog.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyContractLog.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyContractLog.DynamicTableName = false;
            this.View_RTLessorAVSCmtyContractLog.EEPAlias = null;
            this.View_RTLessorAVSCmtyContractLog.EncodingAfter = null;
            this.View_RTLessorAVSCmtyContractLog.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyContractLog.EncodingConvert = null;
            this.View_RTLessorAVSCmtyContractLog.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "COMQ1";
            keyItem9.KeyName = "CONTRACTNO";
            keyItem10.KeyName = "ENTRYNO";
            this.View_RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem8);
            this.View_RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem9);
            this.View_RTLessorAVSCmtyContractLog.KeyFields.Add(keyItem10);
            this.View_RTLessorAVSCmtyContractLog.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyContractLog.Name = "View_RTLessorAVSCmtyContractLog";
            this.View_RTLessorAVSCmtyContractLog.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyContractLog.SecExcept = null;
            this.View_RTLessorAVSCmtyContractLog.SecFieldName = null;
            this.View_RTLessorAVSCmtyContractLog.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyContractLog.SelectPaging = false;
            this.View_RTLessorAVSCmtyContractLog.SelectTop = 0;
            this.View_RTLessorAVSCmtyContractLog.SiteControl = false;
            this.View_RTLessorAVSCmtyContractLog.SiteFieldName = null;
            this.View_RTLessorAVSCmtyContractLog.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRT102
            // 
            this.ucRT102.CacheConnection = false;
            this.ucRT102.CommandText = null;
            this.ucRT102.CommandTimeout = 30;
            this.ucRT102.CommandType = System.Data.CommandType.Text;
            this.ucRT102.DynamicTableName = false;
            this.ucRT102.EEPAlias = null;
            this.ucRT102.EncodingAfter = null;
            this.ucRT102.EncodingBefore = "Windows-1252";
            this.ucRT102.EncodingConvert = null;
            this.ucRT102.InfoConnection = this.InfoConnection1;
            this.ucRT102.MultiSetWhere = false;
            this.ucRT102.Name = "ucRT102";
            this.ucRT102.NotificationAutoEnlist = false;
            this.ucRT102.SecExcept = null;
            this.ucRT102.SecFieldName = null;
            this.ucRT102.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ucRT102.SelectPaging = false;
            this.ucRT102.SelectTop = 0;
            this.ucRT102.SiteControl = false;
            this.ucRT102.SiteFieldName = null;
            this.ucRT102.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRT1021
            // 
            this.ucRT1021.CacheConnection = false;
            this.ucRT1021.CommandText = "usp_RTLessorAVSCmtyContractCancel";
            this.ucRT1021.CommandTimeout = 30;
            this.ucRT1021.CommandType = System.Data.CommandType.StoredProcedure;
            this.ucRT1021.DynamicTableName = false;
            this.ucRT1021.EEPAlias = null;
            this.ucRT1021.EncodingAfter = null;
            this.ucRT1021.EncodingBefore = "Windows-1252";
            this.ucRT1021.EncodingConvert = null;
            this.ucRT1021.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter1.ParameterName = "comq1";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 0;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter2.ParameterName = "CONTRACTNO";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 10;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "usr";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 6;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            this.ucRT1021.InfoParameters.Add(infoParameter1);
            this.ucRT1021.InfoParameters.Add(infoParameter2);
            this.ucRT1021.InfoParameters.Add(infoParameter3);
            this.ucRT1021.MultiSetWhere = false;
            this.ucRT1021.Name = "ucRT1021";
            this.ucRT1021.NotificationAutoEnlist = false;
            this.ucRT1021.SecExcept = null;
            this.ucRT1021.SecFieldName = null;
            this.ucRT1021.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.ucRT1021.SelectPaging = false;
            this.ucRT1021.SelectTop = 0;
            this.ucRT1021.SiteControl = false;
            this.ucRT1021.SiteFieldName = null;
            this.ucRT1021.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContract)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyContractLog)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContract)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyContractLog)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucRT102)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ucRT1021)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyContract;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyContract;
        private Srvtools.InfoCommand RTLessorAVSCmtyContractLog;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyContractLog;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyContract;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyContractLog;
        private Srvtools.InfoCommand ucRT102;
        private Srvtools.InfoCommand ucRT1021;
    }
}
