namespace sRT2033
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyLineHardware = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyLineHardware = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCmtyLineHardware = new Srvtools.InfoCommand(this.components);
            this.cmdRT20331 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20332 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20333 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20334 = new Srvtools.InfoCommand(this.components);
            this.cmd = new Srvtools.InfoCommand(this.components);
            this.RT20331 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyLineHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20331)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20332)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20333)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20334)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20331)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT20331";
            service1.NonLogin = false;
            service1.ServiceName = "smRT20331";
            service2.DelegateName = "smRT20332";
            service2.NonLogin = false;
            service2.ServiceName = "smRT20332";
            service3.DelegateName = "smRT20333";
            service3.NonLogin = false;
            service3.ServiceName = "smRT20333";
            service4.DelegateName = "smRT20334";
            service4.NonLogin = false;
            service4.ServiceName = "smRT20334";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyLineHardware
            // 
            this.RTLessorAVSCmtyLineHardware.CacheConnection = false;
            this.RTLessorAVSCmtyLineHardware.CommandText = "SELECT dbo.[RTLessorAVSCmtyLineHardware].* FROM dbo.[RTLessorAVSCmtyLineHardware]" +
    "";
            this.RTLessorAVSCmtyLineHardware.CommandTimeout = 30;
            this.RTLessorAVSCmtyLineHardware.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyLineHardware.DynamicTableName = false;
            this.RTLessorAVSCmtyLineHardware.EEPAlias = null;
            this.RTLessorAVSCmtyLineHardware.EncodingAfter = null;
            this.RTLessorAVSCmtyLineHardware.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyLineHardware.EncodingConvert = null;
            this.RTLessorAVSCmtyLineHardware.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "LINEQ1";
            keyItem3.KeyName = "PRTNO";
            keyItem4.KeyName = "SEQ";
            this.RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem3);
            this.RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem4);
            this.RTLessorAVSCmtyLineHardware.MultiSetWhere = false;
            this.RTLessorAVSCmtyLineHardware.Name = "RTLessorAVSCmtyLineHardware";
            this.RTLessorAVSCmtyLineHardware.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyLineHardware.SecExcept = null;
            this.RTLessorAVSCmtyLineHardware.SecFieldName = null;
            this.RTLessorAVSCmtyLineHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyLineHardware.SelectPaging = false;
            this.RTLessorAVSCmtyLineHardware.SelectTop = 0;
            this.RTLessorAVSCmtyLineHardware.SiteControl = false;
            this.RTLessorAVSCmtyLineHardware.SiteFieldName = null;
            this.RTLessorAVSCmtyLineHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyLineHardware
            // 
            this.ucRTLessorAVSCmtyLineHardware.AutoTrans = true;
            this.ucRTLessorAVSCmtyLineHardware.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "LINEQ1";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PRTNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SEQ";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "PRODNO";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ITEMNO";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "QTY";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "DROPDAT";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "DROPREASON";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "WAREHOUSE";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "ASSETNO";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "DROPUSR";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "UNIT";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "AMT";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "EUSR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "EDAT";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "UUSR";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "UDAT";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "MEMO";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "BATCHNO";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "TARDAT";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "TUSR";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "RCVPRTNO";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "RCVDAT";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "RCVFINISHDAT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "HOSTNO";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "PRELEVELHOSTNO";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "PRELEVELPORTNO";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyLineHardware.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyLineHardware.LogInfo = null;
            this.ucRTLessorAVSCmtyLineHardware.Name = "ucRTLessorAVSCmtyLineHardware";
            this.ucRTLessorAVSCmtyLineHardware.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyLineHardware.SelectCmd = this.RTLessorAVSCmtyLineHardware;
            this.ucRTLessorAVSCmtyLineHardware.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyLineHardware.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyLineHardware.ServerModify = true;
            this.ucRTLessorAVSCmtyLineHardware.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyLineHardware.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyLineHardware.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyLineHardware.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyLineHardware.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCmtyLineHardware
            // 
            this.View_RTLessorAVSCmtyLineHardware.CacheConnection = false;
            this.View_RTLessorAVSCmtyLineHardware.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyLineHardware]";
            this.View_RTLessorAVSCmtyLineHardware.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyLineHardware.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyLineHardware.DynamicTableName = false;
            this.View_RTLessorAVSCmtyLineHardware.EEPAlias = null;
            this.View_RTLessorAVSCmtyLineHardware.EncodingAfter = null;
            this.View_RTLessorAVSCmtyLineHardware.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyLineHardware.EncodingConvert = null;
            this.View_RTLessorAVSCmtyLineHardware.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "COMQ1";
            keyItem6.KeyName = "LINEQ1";
            keyItem7.KeyName = "PRTNO";
            keyItem8.KeyName = "SEQ";
            this.View_RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem5);
            this.View_RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem6);
            this.View_RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem7);
            this.View_RTLessorAVSCmtyLineHardware.KeyFields.Add(keyItem8);
            this.View_RTLessorAVSCmtyLineHardware.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyLineHardware.Name = "View_RTLessorAVSCmtyLineHardware";
            this.View_RTLessorAVSCmtyLineHardware.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyLineHardware.SecExcept = null;
            this.View_RTLessorAVSCmtyLineHardware.SecFieldName = null;
            this.View_RTLessorAVSCmtyLineHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyLineHardware.SelectPaging = false;
            this.View_RTLessorAVSCmtyLineHardware.SelectTop = 0;
            this.View_RTLessorAVSCmtyLineHardware.SiteControl = false;
            this.View_RTLessorAVSCmtyLineHardware.SiteFieldName = null;
            this.View_RTLessorAVSCmtyLineHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20331
            // 
            this.cmdRT20331.CacheConnection = false;
            this.cmdRT20331.CommandText = "usp_RTLessorAVSCmtyLineHardwareTRNRCVExe";
            this.cmdRT20331.CommandTimeout = 30;
            this.cmdRT20331.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20331.DynamicTableName = false;
            this.cmdRT20331.EEPAlias = null;
            this.cmdRT20331.EncodingAfter = null;
            this.cmdRT20331.EncodingBefore = "Windows-1252";
            this.cmdRT20331.EncodingConvert = null;
            this.cmdRT20331.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter1.ParameterName = "comq1";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 0;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "lineq1";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "prtno";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 12;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "usr";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 6;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20331.InfoParameters.Add(infoParameter1);
            this.cmdRT20331.InfoParameters.Add(infoParameter2);
            this.cmdRT20331.InfoParameters.Add(infoParameter3);
            this.cmdRT20331.InfoParameters.Add(infoParameter4);
            this.cmdRT20331.MultiSetWhere = false;
            this.cmdRT20331.Name = "cmdRT20331";
            this.cmdRT20331.NotificationAutoEnlist = false;
            this.cmdRT20331.SecExcept = null;
            this.cmdRT20331.SecFieldName = null;
            this.cmdRT20331.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20331.SelectPaging = false;
            this.cmdRT20331.SelectTop = 0;
            this.cmdRT20331.SiteControl = false;
            this.cmdRT20331.SiteFieldName = null;
            this.cmdRT20331.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20332
            // 
            this.cmdRT20332.CacheConnection = false;
            this.cmdRT20332.CommandText = "usp_RTLessorAVSCustHardwareTRNRCVRTNExe";
            this.cmdRT20332.CommandTimeout = 30;
            this.cmdRT20332.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20332.DynamicTableName = false;
            this.cmdRT20332.EEPAlias = null;
            this.cmdRT20332.EncodingAfter = null;
            this.cmdRT20332.EncodingBefore = "Windows-1252";
            this.cmdRT20332.EncodingConvert = null;
            this.cmdRT20332.InfoConnection = this.InfoConnection1;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "rcvprtno";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 13;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter6.ParameterName = "usr";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 6;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20332.InfoParameters.Add(infoParameter5);
            this.cmdRT20332.InfoParameters.Add(infoParameter6);
            this.cmdRT20332.MultiSetWhere = false;
            this.cmdRT20332.Name = "cmdRT20332";
            this.cmdRT20332.NotificationAutoEnlist = false;
            this.cmdRT20332.SecExcept = null;
            this.cmdRT20332.SecFieldName = null;
            this.cmdRT20332.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20332.SelectPaging = false;
            this.cmdRT20332.SelectTop = 0;
            this.cmdRT20332.SiteControl = false;
            this.cmdRT20332.SiteFieldName = null;
            this.cmdRT20332.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20333
            // 
            this.cmdRT20333.CacheConnection = false;
            this.cmdRT20333.CommandText = "usp_RTLessorAVSCmtyLineHardwareDrop";
            this.cmdRT20333.CommandTimeout = 30;
            this.cmdRT20333.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20333.DynamicTableName = false;
            this.cmdRT20333.EEPAlias = null;
            this.cmdRT20333.EncodingAfter = null;
            this.cmdRT20333.EncodingBefore = "Windows-1252";
            this.cmdRT20333.EncodingConvert = null;
            this.cmdRT20333.InfoConnection = this.InfoConnection1;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter7.ParameterName = "comq1";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 0;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter8.ParameterName = "lineq1";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 0;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "prtno";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 12;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter10.ParameterName = "seq";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 0;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "usr";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 6;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20333.InfoParameters.Add(infoParameter7);
            this.cmdRT20333.InfoParameters.Add(infoParameter8);
            this.cmdRT20333.InfoParameters.Add(infoParameter9);
            this.cmdRT20333.InfoParameters.Add(infoParameter10);
            this.cmdRT20333.InfoParameters.Add(infoParameter11);
            this.cmdRT20333.MultiSetWhere = false;
            this.cmdRT20333.Name = "cmdRT20333";
            this.cmdRT20333.NotificationAutoEnlist = false;
            this.cmdRT20333.SecExcept = null;
            this.cmdRT20333.SecFieldName = null;
            this.cmdRT20333.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20333.SelectPaging = false;
            this.cmdRT20333.SelectTop = 0;
            this.cmdRT20333.SiteControl = false;
            this.cmdRT20333.SiteFieldName = null;
            this.cmdRT20333.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20334
            // 
            this.cmdRT20334.CacheConnection = false;
            this.cmdRT20334.CommandText = "usp_RTLessorAVSCmtyLineHardwareDropC";
            this.cmdRT20334.CommandTimeout = 30;
            this.cmdRT20334.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20334.DynamicTableName = false;
            this.cmdRT20334.EEPAlias = null;
            this.cmdRT20334.EncodingAfter = null;
            this.cmdRT20334.EncodingBefore = "Windows-1252";
            this.cmdRT20334.EncodingConvert = null;
            this.cmdRT20334.InfoConnection = this.InfoConnection1;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter12.ParameterName = "comq1";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 0;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter13.ParameterName = "lineq1";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 0;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter14.ParameterName = "prtno";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 12;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter15.ParameterName = "seq";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 0;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter16.ParameterName = "usr";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 6;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20334.InfoParameters.Add(infoParameter12);
            this.cmdRT20334.InfoParameters.Add(infoParameter13);
            this.cmdRT20334.InfoParameters.Add(infoParameter14);
            this.cmdRT20334.InfoParameters.Add(infoParameter15);
            this.cmdRT20334.InfoParameters.Add(infoParameter16);
            this.cmdRT20334.MultiSetWhere = false;
            this.cmdRT20334.Name = "cmdRT20334";
            this.cmdRT20334.NotificationAutoEnlist = false;
            this.cmdRT20334.SecExcept = null;
            this.cmdRT20334.SecFieldName = null;
            this.cmdRT20334.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20334.SelectPaging = false;
            this.cmdRT20334.SelectTop = 0;
            this.cmdRT20334.SiteControl = false;
            this.cmdRT20334.SiteFieldName = null;
            this.cmdRT20334.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmd
            // 
            this.cmd.CacheConnection = false;
            this.cmd.CommandText = "";
            this.cmd.CommandTimeout = 30;
            this.cmd.CommandType = System.Data.CommandType.Text;
            this.cmd.DynamicTableName = false;
            this.cmd.EEPAlias = null;
            this.cmd.EncodingAfter = null;
            this.cmd.EncodingBefore = "Windows-1252";
            this.cmd.EncodingConvert = null;
            this.cmd.InfoConnection = this.InfoConnection1;
            this.cmd.MultiSetWhere = false;
            this.cmd.Name = "cmd";
            this.cmd.NotificationAutoEnlist = false;
            this.cmd.SecExcept = null;
            this.cmd.SecFieldName = null;
            this.cmd.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmd.SelectPaging = false;
            this.cmd.SelectTop = 0;
            this.cmd.SiteControl = false;
            this.cmd.SiteFieldName = null;
            this.cmd.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT20331
            // 
            this.RT20331.CacheConnection = false;
            this.RT20331.CommandText = resources.GetString("RT20331.CommandText");
            this.RT20331.CommandTimeout = 30;
            this.RT20331.CommandType = System.Data.CommandType.Text;
            this.RT20331.DynamicTableName = false;
            this.RT20331.EEPAlias = null;
            this.RT20331.EncodingAfter = null;
            this.RT20331.EncodingBefore = "Windows-1252";
            this.RT20331.EncodingConvert = null;
            this.RT20331.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "comq1";
            keyItem10.KeyName = "lineq1";
            keyItem11.KeyName = "PRTNO";
            keyItem12.KeyName = "seq";
            keyItem13.KeyName = "SEQ2";
            this.RT20331.KeyFields.Add(keyItem9);
            this.RT20331.KeyFields.Add(keyItem10);
            this.RT20331.KeyFields.Add(keyItem11);
            this.RT20331.KeyFields.Add(keyItem12);
            this.RT20331.KeyFields.Add(keyItem13);
            this.RT20331.MultiSetWhere = false;
            this.RT20331.Name = "RT20331";
            this.RT20331.NotificationAutoEnlist = false;
            this.RT20331.SecExcept = null;
            this.RT20331.SecFieldName = null;
            this.RT20331.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT20331.SelectPaging = false;
            this.RT20331.SelectTop = 0;
            this.RT20331.SiteControl = false;
            this.RT20331.SiteFieldName = null;
            this.RT20331.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyLineHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20331)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20332)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20333)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20334)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20331)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyLineHardware;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyLineHardware;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyLineHardware;
        private Srvtools.InfoCommand cmdRT20331;
        private Srvtools.InfoCommand cmdRT20332;
        private Srvtools.InfoCommand cmdRT20333;
        private Srvtools.InfoCommand cmdRT20334;
        private Srvtools.InfoCommand cmd;
        private Srvtools.InfoCommand RT20331;
    }
}
