--«Ø¥ßºûÅ@¤H­ûªº¿ï³æ
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S2', 'T99281', '¾G®¼±¶')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S2', 'T03001', '¤ýïï¸Û')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S2', 'T99300', '¸­¬ü®R')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S2', 'T95224', '¸­²Q´@')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S2', 'T99278', '¯Îä§Áâ')

INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S3', 'T90047', '¾G´_Ä}')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S3', 'T06002', '°K¹B¿Î')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S3', 'T06001', '¿à¬f§¡')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S3', 'C92026', '¬x·ç§»')
INSERT INTO RTCode (KIND, CODE, CODENC) VALUES ('S3', 'K89002', '©P·G©¾')
