DROP VIEW V_RT104FAQ
GO

CREATE VIEW V_RT104FAQ AS 
SELECT A.CUSID, ISNULL(C.QT_CC, 0) AS QT_CC
FROM RTLessorAVSCust A
LEFT JOIN (SELECT CUSID, COUNT(CASENO) AS QT_CC FROM RTFaqM GROUP BY CUSID) C ON C.CUSID=A.CUSID
