<HTML>
<HEAD>
<meta http-equiv=Content-Type content="text/html; charset=Big5">
<TITLE>HiBuilding 未完工或未報竣戶一覽表</TITLE>
<SCRIPT language=VBScript>
Sub cmdSure_onClick
  PGM="/report/hb/HBReport8.asp?parm=" 
  
  'yyyymm=document.all("search3").value 
  'if Len(Rtrim(yyyymm)) = 1 then yyyymm = "0" & yyyymm
  'yyyymm=document.all("search1").value & yyyymm
  'groupid=document.all("sEARCH6").value  '業務群組代號
  'eusr=document.all("search4").value 
  'pgm=pgm & yyyymm & ";" & Rtrim(groupid) & ";" & eusr
  'msgbox pgm
  window.open pgm 
   window.close
End Sub
Sub cmdcancel_onClick
  window.close
End Sub

</SCRIPT>
</HEAD>
<OBJECT classid="CLSID:B8C54992-B7BF-11D3-AACE-0080C8BA466E" codeBase=http://www.cbbn.com.tw/stock/EF2KDT.CAB#version=9,0,0,3 
	height=60 id=objEF2KDT style="DISPLAY: none; HEIGHT: 0px; LEFT: 0px; TOP: 0px; WIDTH: 0px" 
	width=60 VIEWASTEXT>
	<PARAM NAME="_ExtentX" VALUE="1270">
	<PARAM NAME="_ExtentY" VALUE="1270"></OBJECT>

<BODY style="background:lightblue">
<DIV align=Center><i><font face="標楷體" size="5" color="#FF00FF">Hibuilding 社區－報表列印</font></i> </DIV>
<DIV align=Center><i><font face="標楷體" size="3" color="#FF00FF">未完工或未報竣戶一覽表 </font></i> </DIV>
<P><P>
<table align="center" width="90%" border=0 cellPadding=0 cellSpacing=0>
</SELECT>  
 </font></td> 


</table> 
<p><center><font face="標楷體">
 <INPUT TYPE="button" VALUE="送出" ID="cmdSure"   
 style="font-family: 標楷體; color: #FF0000;cursor:hand"> 
  <INPUT TYPE="button" VALUE="取消" ID="cmdcancel"   
 style="font-family: 標楷體; color: #FF0000;cursor:hand">
 </center>
  <HR><P>
  <table width="100%">
  <TABLE></font></p> 
</BODY> 
</HTML>
