<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=big5">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>元訊寬頻網路股份有限公司</title>
</head>
<script language="JavaScript" fptype="dynamicanimation">
<!--
function dynAnimation() {}
function clickSwapImg() {}
//-->
</script>
<script language="JavaScript1.2" fptype="dynamicanimation" src="animate.js">
</script>
<script language=vbscript>
  sub newurl(num)
    select case num
      case 1
        prog="dialog1.asp"
      case 2
        prog="dialog2.asp"
      case 3
        prog="dialog3.asp"
      case 4
        prog="dialog4.asp"
      case 5
        prog="dialog5.asp"
      case 6
        prog="dialog6.asp"
      case 7
        prog="dialog7.asp"
      case 8
        prog="dialog8.asp"
      case 9
        prog="dialog9.asp"
      case 10
        prog="dialog10.asp"
      case 11
        prog="dialog11.asp"
      case 12
        prog="dialog12.asp"
      case 13
        prog="dialog13.asp"
      case 14
        prog="dialog14.asp"
      case 15
        prog="dialog15.asp"
      case 16
        prog="dialog16.asp"
      case 17
        prog="dialog17.asp"
      case 18
        prog="dialog18.asp"
      case 19
        prog="dialog19.asp"
      case 20
        prog="dialog20.asp"
      case 21
        prog="dialog21.asp"
      case 22
        prog="dialog22.asp"
      case 23
        prog="dialog23.asp"
      case 24
        prog="dialog24.asp"

      case else
    end select
    xx=(window.screen.width -7)/1.5
    yy=(window.screen.height -74)/1.5
    xx2=(window.screen.width - XX)/2
    yy2=(window.screen.height - yy)/2
    features="top=" & xx2 & ",left=" & yy2 & ",status=yes,location=no,menubar=no,scrollbars=yes" & ",height=" & yy & ",width=" & xx
    result=window.open(prog,"ppAP",features)
    window.event.returnValue=False
  end sub
</script>
<body bgcolor="#c3c9d2">
<table border="0" width="100%">
  <tr>
    <td width="20%"></td>
    <td width="60%" align="middle"><font color="#0000ff">元訊寬頻網路股份有限公司</font></td>
    <td width="20%"><font color="#0000ff">日期：<%=DATEVALUE(NOW)%></font></td>
  </tr>
  <tr>
    <td width="20%">　</td>
    <td width="60%" align="middle"><font color="#0000ff">HI-BUILDING－各類報表列印</font></td>
    <td width="20%"><font color="#0000ff">時間：<%=timeVALUE(TIME)%></font></td>
  </tr>

</table>
<HR>
<CENTER>
<TABLE style="WIDTH: 587px; HEIGHT: 75px" cellSpacing=0 cellPadding=0 width=587 
bgColor=antiquewhite border=1>
  
  <TR>
    <TD style="WIDTH: 33%" width="33%" bgColor=#3e7373>
      <P style="COLOR: yellow" align=center>各方案報表</P></TD>
    <TD style="WIDTH: 34%" width="34%" bgColor=#3e7373>
      <P style="COLOR: yellow" align=center>HB599月報表</P></TD>
    <TD style="WIDTH: 33%" width="33" bgColor=#3e7373>
      <P style="COLOR: yellow" align=center>HB599其它管理報表</P></TD></TR>
  <TR>
    <TD onclick="newurl(13)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(1)各方案客戶數統計表(Excel)</FONT></TD>
    <TD onclick="newurl(1)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(1)HI-BUILDING社區用戶統計月報表</FONT></TD>
    <TD onclick="newurl(2)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(1)中華電信報竣客戶明細表(計量制)</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(14)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(2)各方案退租,欠拆戶明細表(Excel)</FONT></TD>
    <TD onclick="newurl(9)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(2)員工獎金統計表</FONT></TD>
    <TD onclick="newurl(4)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(2)HiBuilding 社區戶數統計表</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(15)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(3)各方案北區直銷社區報竣退租欠拆數統計(Excel)</FONT></TD>
    <TD onclick="newurl(17)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(3)工務人員各方案社區線數戶數統計(Excel)</FONT></TD>
    <TD onclick="newurl(19)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(3)HiBuilding 客戶建置明細表</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(16)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(4)各方案平均線數&戶數統計(Excel)</FONT></TD>
    <TD onclick="newurl(21)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(4)CHT599及399各組累總表(Excel)</FONT></TD>
    <TD onclick="newurl(6)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(4)客戶密碼條信封列印</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(5)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(5)社區主線資料(Excel)</FONT></TD>
    <TD onclick="newurl(22)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(5)業務員各方案每月報竣欠退數(Excel)</FONT></TD>
    <TD onclick="newurl(7)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(5)社區實際客戶勘查表</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(18)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(6)直銷業務員線數&戶數統計(Excel)</FONT></TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(8)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(6)未完工或未報竣戶一覽表</FONT></TD></TR>
  <TR>
    <TD onclick="newurl(20)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(7)經銷業務員線數&戶數統計(Excel)</FONT></TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(3)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(7)計量制有ip無完工或無報竣一覽表</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(10)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(8)直銷社區名單</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(11)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(9)裝機人報竣一覽表</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(12)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(10)社區送線一覽表</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(23)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(11)HiBuilding客戶 Call Out 名單</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD onclick="newurl(24)" onmouseover="rollIn(this)" onmouseout="rollOut(this)"
        language="Javascript1.2" dynamicanimation="fpAnimformatRolloverFP1" fprolloverstyle="font-size: 10pt; color: #FF0000; font-family: 細明體; background-color: #e0ffff; cursor:hand">
        <FONT style="COLOR: darkorchid;font-size:10pt">(12)中華客戶信封列印</FONT></TD></TR>
  <TR>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD>
    <TD>&nbsp;</TD></TR>
    </TABLE>
</CENTER>
</body></HTML>
