SELECT REPLACE(LTRIM(REPLACE(LTRIM(ISNULL(P7, '') + ' ' + ISNULL(P6, '') + ' ' + ISNULL(P5, '') + ' ' + ISNULL(P4, '') + ' ' + 
ISNULL(P3, '') + ' ' + ISNULL(P2, '') + ' ' + ISNULL(P1, '') + ' ' + CAPTION), 'ROOT', '')), ' ', ',')  AS MENU
FROM (
SELECT A.MENUID, A.CAPTION, A.PARENT, B.PARENT AS PARENT1, B.CAPTION AS P1, C.PARENT AS PARENT2
, C.CAPTION AS P2, D.PARENT AS PARENT3, D.CAPTION AS P3, E.PARENT AS PARENT4, E.CAPTION AS P4
, F.PARENT AS PARENT5, F.CAPTION AS P5, G.PARENT AS PARENT6, G.CAPTION AS P6
, H.PARENT AS PARENT7, H.CAPTION AS P7, A.SEQ_NO
FROM MENUFUNCTION A
LEFT JOIN MENUFUNCTION B ON B.MENUID=A.PARENT
LEFT JOIN MENUFUNCTION C ON C.MENUID=B.PARENT
LEFT JOIN MENUFUNCTION D ON D.MENUID=C.PARENT
LEFT JOIN MENUFUNCTION E ON E.MENUID=D.PARENT
LEFT JOIN MENUFUNCTION F ON F.MENUID=E.PARENT
LEFT JOIN MENUFUNCTION G ON G.MENUID=F.PARENT
LEFT JOIN MENUFUNCTION H ON H.MENUID=G.PARENT
WHERE A.MENUID NOT IN (SELECT PARENT FROM MENUFUNCTION)
AND A.ITEMTYPE LIKE '¥¼%') A
ORDER BY A.MENUID