namespace sRT101
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr82 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr83 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr84 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr85 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr86 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr87 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr88 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr89 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr90 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr91 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr92 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr93 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr94 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr95 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr96 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr97 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr98 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr99 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr100 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr101 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr102 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr103 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr104 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr105 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr106 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr107 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyH = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyH = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCmtyH = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.RTLessorAVSCmtyLineHARDWARE = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyLineHARDWARE = new Srvtools.UpdateComponent(this.components);
            this.RT1012 = new Srvtools.InfoCommand(this.components);
            this.RT10121 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyH)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyH)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineHARDWARE)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1012)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10121)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyH
            // 
            this.RTLessorAVSCmtyH.CacheConnection = false;
            this.RTLessorAVSCmtyH.CommandText = resources.GetString("RTLessorAVSCmtyH.CommandText");
            this.RTLessorAVSCmtyH.CommandTimeout = 30;
            this.RTLessorAVSCmtyH.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyH.DynamicTableName = false;
            this.RTLessorAVSCmtyH.EEPAlias = null;
            this.RTLessorAVSCmtyH.EncodingAfter = null;
            this.RTLessorAVSCmtyH.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyH.EncodingConvert = null;
            this.RTLessorAVSCmtyH.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "COMQ1";
            this.RTLessorAVSCmtyH.KeyFields.Add(keyItem7);
            this.RTLessorAVSCmtyH.MultiSetWhere = false;
            this.RTLessorAVSCmtyH.Name = "RTLessorAVSCmtyH";
            this.RTLessorAVSCmtyH.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyH.SecExcept = null;
            this.RTLessorAVSCmtyH.SecFieldName = null;
            this.RTLessorAVSCmtyH.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyH.SelectPaging = false;
            this.RTLessorAVSCmtyH.SelectTop = 0;
            this.RTLessorAVSCmtyH.SiteControl = false;
            this.RTLessorAVSCmtyH.SiteFieldName = null;
            this.RTLessorAVSCmtyH.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyH
            // 
            this.ucRTLessorAVSCmtyH.AutoTrans = true;
            this.ucRTLessorAVSCmtyH.ExceptJoin = false;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "COMQ1";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "COMN";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "CUTID";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "TOWNSHIP";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "RADDR";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "RZONE";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CUTID2";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "TOWNSHIP2";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "RADDR2";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CUTID3";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "TOWNSHIP3";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "RADDR3";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CUTID4";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "TOWNSHIP4";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "RADDR4";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "COMCNT";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "BUILDTYPE";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "BUILDCNT";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "BUILDFLOOR";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "POWERJECT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "POWERTYPE";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "POWERDISTANCE";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "SETUPTYPE";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "CABLELENGTH";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "AGREEDRILL";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "TELCOMROOM";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "SURVEYDAT";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "AGREEDAT";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "AGREE";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CharSetNull = false;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "UNAGREEDESC";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CharSetNull = false;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "UPDEBTCHKDAT";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CharSetNull = false;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "UPDEBTCHKUSR";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CharSetNull = false;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "UPDEBTDAT";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CharSetNull = false;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "TELCOMBOX";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CharSetNull = false;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "CONTACT";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CharSetNull = false;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "CONTACTTEL";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CharSetNull = false;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "EUSR";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = "_usercode";
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CharSetNull = false;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "EDAT";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = "_today";
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CharSetNull = false;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "UUSR";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr67.DefaultValue = "_usercode";
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CharSetNull = false;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "UDAT";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Update;
            fieldAttr68.DefaultValue = "_today";
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CharSetNull = false;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "REMITAGREE";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CharSetNull = false;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "COPYREMIT";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CharSetNull = false;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "REMITNO";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CharSetNull = false;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "REMITBANK";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CharSetNull = false;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "BANKBRANCH";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CharSetNull = false;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "REMITACCOUNT";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            fieldAttr75.CharSetNull = false;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "REMITNAME";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CharSetNull = false;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "CHECKTITLE";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CharSetNull = false;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "CCUTID";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CharSetNull = false;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "CTOWNSHIP";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CharSetNull = false;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "CADDR";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = null;
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr49);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr50);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr51);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr52);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr53);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr54);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr55);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr56);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr57);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr58);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr59);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr60);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr61);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr62);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr63);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr64);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr65);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr66);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr67);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr68);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr69);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr70);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr71);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr72);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr73);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr74);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr75);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr76);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr77);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr78);
            this.ucRTLessorAVSCmtyH.FieldAttrs.Add(fieldAttr79);
            this.ucRTLessorAVSCmtyH.LogInfo = null;
            this.ucRTLessorAVSCmtyH.Name = "ucRTLessorAVSCmtyH";
            this.ucRTLessorAVSCmtyH.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyH.SelectCmd = this.RTLessorAVSCmtyH;
            this.ucRTLessorAVSCmtyH.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyH.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyH.ServerModify = true;
            this.ucRTLessorAVSCmtyH.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyH.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyH.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyH.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyH.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCmtyH
            // 
            this.View_RTLessorAVSCmtyH.CacheConnection = false;
            this.View_RTLessorAVSCmtyH.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyH]";
            this.View_RTLessorAVSCmtyH.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyH.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyH.DynamicTableName = false;
            this.View_RTLessorAVSCmtyH.EEPAlias = null;
            this.View_RTLessorAVSCmtyH.EncodingAfter = null;
            this.View_RTLessorAVSCmtyH.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyH.EncodingConvert = null;
            this.View_RTLessorAVSCmtyH.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "COMQ1";
            this.View_RTLessorAVSCmtyH.KeyFields.Add(keyItem8);
            this.View_RTLessorAVSCmtyH.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyH.Name = "View_RTLessorAVSCmtyH";
            this.View_RTLessorAVSCmtyH.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyH.SecExcept = null;
            this.View_RTLessorAVSCmtyH.SecFieldName = null;
            this.View_RTLessorAVSCmtyH.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyH.SelectPaging = false;
            this.View_RTLessorAVSCmtyH.SelectTop = 0;
            this.View_RTLessorAVSCmtyH.SiteControl = false;
            this.View_RTLessorAVSCmtyH.SiteFieldName = null;
            this.View_RTLessorAVSCmtyH.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "RT101";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "RT101";
            this.autoNumber1.isNumFill = true;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 999999;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 590;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "COMQ1";
            this.autoNumber1.UpdateComp = this.ucRTLessorAVSCmtyH;
            // 
            // RTLessorAVSCmtyLineHARDWARE
            // 
            this.RTLessorAVSCmtyLineHARDWARE.CacheConnection = false;
            this.RTLessorAVSCmtyLineHARDWARE.CommandText = "SELECT * FROM RTLessorAVSCmtyLineHARDWARE";
            this.RTLessorAVSCmtyLineHARDWARE.CommandTimeout = 30;
            this.RTLessorAVSCmtyLineHARDWARE.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyLineHARDWARE.DynamicTableName = false;
            this.RTLessorAVSCmtyLineHARDWARE.EEPAlias = null;
            this.RTLessorAVSCmtyLineHARDWARE.EncodingAfter = null;
            this.RTLessorAVSCmtyLineHARDWARE.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyLineHARDWARE.EncodingConvert = null;
            this.RTLessorAVSCmtyLineHARDWARE.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem9.KeyName = "LINEQ1";
            keyItem10.KeyName = "PRTNO";
            keyItem11.KeyName = "SEQ";
            this.RTLessorAVSCmtyLineHARDWARE.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyLineHARDWARE.KeyFields.Add(keyItem9);
            this.RTLessorAVSCmtyLineHARDWARE.KeyFields.Add(keyItem10);
            this.RTLessorAVSCmtyLineHARDWARE.KeyFields.Add(keyItem11);
            this.RTLessorAVSCmtyLineHARDWARE.MultiSetWhere = false;
            this.RTLessorAVSCmtyLineHARDWARE.Name = "RTLessorAVSCmtyLineHARDWARE";
            this.RTLessorAVSCmtyLineHARDWARE.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyLineHARDWARE.SecExcept = null;
            this.RTLessorAVSCmtyLineHARDWARE.SecFieldName = null;
            this.RTLessorAVSCmtyLineHARDWARE.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyLineHARDWARE.SelectPaging = false;
            this.RTLessorAVSCmtyLineHARDWARE.SelectTop = 0;
            this.RTLessorAVSCmtyLineHARDWARE.SiteControl = false;
            this.RTLessorAVSCmtyLineHARDWARE.SiteFieldName = null;
            this.RTLessorAVSCmtyLineHARDWARE.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyLineHARDWARE
            // 
            this.ucRTLessorAVSCmtyLineHARDWARE.AutoTrans = true;
            this.ucRTLessorAVSCmtyLineHARDWARE.ExceptJoin = false;
            fieldAttr80.CharSetNull = false;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "COMQ1";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = null;
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CharSetNull = false;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "LINEQ1";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr81.DefaultValue = null;
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            fieldAttr82.CharSetNull = false;
            fieldAttr82.CheckNull = false;
            fieldAttr82.DataField = "PRTNO";
            fieldAttr82.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr82.DefaultValue = null;
            fieldAttr82.TrimLength = 0;
            fieldAttr82.UpdateEnable = true;
            fieldAttr82.WhereMode = true;
            fieldAttr83.CharSetNull = false;
            fieldAttr83.CheckNull = false;
            fieldAttr83.DataField = "SEQ";
            fieldAttr83.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr83.DefaultValue = null;
            fieldAttr83.TrimLength = 0;
            fieldAttr83.UpdateEnable = true;
            fieldAttr83.WhereMode = true;
            fieldAttr84.CharSetNull = false;
            fieldAttr84.CheckNull = false;
            fieldAttr84.DataField = "PRODNO";
            fieldAttr84.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr84.DefaultValue = null;
            fieldAttr84.TrimLength = 0;
            fieldAttr84.UpdateEnable = true;
            fieldAttr84.WhereMode = true;
            fieldAttr85.CharSetNull = false;
            fieldAttr85.CheckNull = false;
            fieldAttr85.DataField = "ITEMNO";
            fieldAttr85.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr85.DefaultValue = null;
            fieldAttr85.TrimLength = 0;
            fieldAttr85.UpdateEnable = true;
            fieldAttr85.WhereMode = true;
            fieldAttr86.CharSetNull = false;
            fieldAttr86.CheckNull = false;
            fieldAttr86.DataField = "QTY";
            fieldAttr86.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr86.DefaultValue = null;
            fieldAttr86.TrimLength = 0;
            fieldAttr86.UpdateEnable = true;
            fieldAttr86.WhereMode = true;
            fieldAttr87.CharSetNull = false;
            fieldAttr87.CheckNull = false;
            fieldAttr87.DataField = "DROPDAT";
            fieldAttr87.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr87.DefaultValue = null;
            fieldAttr87.TrimLength = 0;
            fieldAttr87.UpdateEnable = true;
            fieldAttr87.WhereMode = true;
            fieldAttr88.CharSetNull = false;
            fieldAttr88.CheckNull = false;
            fieldAttr88.DataField = "DROPREASON";
            fieldAttr88.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr88.DefaultValue = null;
            fieldAttr88.TrimLength = 0;
            fieldAttr88.UpdateEnable = true;
            fieldAttr88.WhereMode = true;
            fieldAttr89.CharSetNull = false;
            fieldAttr89.CheckNull = false;
            fieldAttr89.DataField = "WAREHOUSE";
            fieldAttr89.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr89.DefaultValue = null;
            fieldAttr89.TrimLength = 0;
            fieldAttr89.UpdateEnable = true;
            fieldAttr89.WhereMode = true;
            fieldAttr90.CharSetNull = false;
            fieldAttr90.CheckNull = false;
            fieldAttr90.DataField = "ASSETNO";
            fieldAttr90.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr90.DefaultValue = null;
            fieldAttr90.TrimLength = 0;
            fieldAttr90.UpdateEnable = true;
            fieldAttr90.WhereMode = true;
            fieldAttr91.CharSetNull = false;
            fieldAttr91.CheckNull = false;
            fieldAttr91.DataField = "DROPUSR";
            fieldAttr91.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr91.DefaultValue = null;
            fieldAttr91.TrimLength = 0;
            fieldAttr91.UpdateEnable = true;
            fieldAttr91.WhereMode = true;
            fieldAttr92.CharSetNull = false;
            fieldAttr92.CheckNull = false;
            fieldAttr92.DataField = "UNIT";
            fieldAttr92.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr92.DefaultValue = null;
            fieldAttr92.TrimLength = 0;
            fieldAttr92.UpdateEnable = true;
            fieldAttr92.WhereMode = true;
            fieldAttr93.CharSetNull = false;
            fieldAttr93.CheckNull = false;
            fieldAttr93.DataField = "AMT";
            fieldAttr93.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr93.DefaultValue = null;
            fieldAttr93.TrimLength = 0;
            fieldAttr93.UpdateEnable = true;
            fieldAttr93.WhereMode = true;
            fieldAttr94.CharSetNull = false;
            fieldAttr94.CheckNull = false;
            fieldAttr94.DataField = "EUSR";
            fieldAttr94.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr94.DefaultValue = null;
            fieldAttr94.TrimLength = 0;
            fieldAttr94.UpdateEnable = true;
            fieldAttr94.WhereMode = true;
            fieldAttr95.CharSetNull = false;
            fieldAttr95.CheckNull = false;
            fieldAttr95.DataField = "EDAT";
            fieldAttr95.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr95.DefaultValue = null;
            fieldAttr95.TrimLength = 0;
            fieldAttr95.UpdateEnable = true;
            fieldAttr95.WhereMode = true;
            fieldAttr96.CharSetNull = false;
            fieldAttr96.CheckNull = false;
            fieldAttr96.DataField = "UUSR";
            fieldAttr96.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr96.DefaultValue = null;
            fieldAttr96.TrimLength = 0;
            fieldAttr96.UpdateEnable = true;
            fieldAttr96.WhereMode = true;
            fieldAttr97.CharSetNull = false;
            fieldAttr97.CheckNull = false;
            fieldAttr97.DataField = "UDAT";
            fieldAttr97.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr97.DefaultValue = null;
            fieldAttr97.TrimLength = 0;
            fieldAttr97.UpdateEnable = true;
            fieldAttr97.WhereMode = true;
            fieldAttr98.CharSetNull = false;
            fieldAttr98.CheckNull = false;
            fieldAttr98.DataField = "MEMO";
            fieldAttr98.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr98.DefaultValue = null;
            fieldAttr98.TrimLength = 0;
            fieldAttr98.UpdateEnable = true;
            fieldAttr98.WhereMode = true;
            fieldAttr99.CharSetNull = false;
            fieldAttr99.CheckNull = false;
            fieldAttr99.DataField = "BATCHNO";
            fieldAttr99.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr99.DefaultValue = null;
            fieldAttr99.TrimLength = 0;
            fieldAttr99.UpdateEnable = true;
            fieldAttr99.WhereMode = true;
            fieldAttr100.CharSetNull = false;
            fieldAttr100.CheckNull = false;
            fieldAttr100.DataField = "TARDAT";
            fieldAttr100.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr100.DefaultValue = null;
            fieldAttr100.TrimLength = 0;
            fieldAttr100.UpdateEnable = true;
            fieldAttr100.WhereMode = true;
            fieldAttr101.CharSetNull = false;
            fieldAttr101.CheckNull = false;
            fieldAttr101.DataField = "TUSR";
            fieldAttr101.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr101.DefaultValue = null;
            fieldAttr101.TrimLength = 0;
            fieldAttr101.UpdateEnable = true;
            fieldAttr101.WhereMode = true;
            fieldAttr102.CharSetNull = false;
            fieldAttr102.CheckNull = false;
            fieldAttr102.DataField = "RCVPRTNO";
            fieldAttr102.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr102.DefaultValue = null;
            fieldAttr102.TrimLength = 0;
            fieldAttr102.UpdateEnable = true;
            fieldAttr102.WhereMode = true;
            fieldAttr103.CharSetNull = false;
            fieldAttr103.CheckNull = false;
            fieldAttr103.DataField = "RCVDAT";
            fieldAttr103.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr103.DefaultValue = null;
            fieldAttr103.TrimLength = 0;
            fieldAttr103.UpdateEnable = true;
            fieldAttr103.WhereMode = true;
            fieldAttr104.CharSetNull = false;
            fieldAttr104.CheckNull = false;
            fieldAttr104.DataField = "RCVFINISHDAT";
            fieldAttr104.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr104.DefaultValue = null;
            fieldAttr104.TrimLength = 0;
            fieldAttr104.UpdateEnable = true;
            fieldAttr104.WhereMode = true;
            fieldAttr105.CharSetNull = false;
            fieldAttr105.CheckNull = false;
            fieldAttr105.DataField = "HOSTNO";
            fieldAttr105.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr105.DefaultValue = null;
            fieldAttr105.TrimLength = 0;
            fieldAttr105.UpdateEnable = true;
            fieldAttr105.WhereMode = true;
            fieldAttr106.CharSetNull = false;
            fieldAttr106.CheckNull = false;
            fieldAttr106.DataField = "PRELEVELHOSTNO";
            fieldAttr106.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr106.DefaultValue = null;
            fieldAttr106.TrimLength = 0;
            fieldAttr106.UpdateEnable = true;
            fieldAttr106.WhereMode = true;
            fieldAttr107.CharSetNull = false;
            fieldAttr107.CheckNull = false;
            fieldAttr107.DataField = "PRELEVELPORTNO";
            fieldAttr107.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr107.DefaultValue = null;
            fieldAttr107.TrimLength = 0;
            fieldAttr107.UpdateEnable = true;
            fieldAttr107.WhereMode = true;
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr80);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr81);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr82);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr83);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr84);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr85);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr86);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr87);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr88);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr89);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr90);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr91);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr92);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr93);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr94);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr95);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr96);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr97);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr98);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr99);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr100);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr101);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr102);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr103);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr104);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr105);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr106);
            this.ucRTLessorAVSCmtyLineHARDWARE.FieldAttrs.Add(fieldAttr107);
            this.ucRTLessorAVSCmtyLineHARDWARE.LogInfo = null;
            this.ucRTLessorAVSCmtyLineHARDWARE.Name = "ucRTLessorAVSCmtyLineHARDWARE";
            this.ucRTLessorAVSCmtyLineHARDWARE.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyLineHARDWARE.SelectCmd = this.RTLessorAVSCmtyLineHARDWARE;
            this.ucRTLessorAVSCmtyLineHARDWARE.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyLineHARDWARE.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyLineHARDWARE.ServerModify = true;
            this.ucRTLessorAVSCmtyLineHARDWARE.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyLineHARDWARE.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyLineHARDWARE.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyLineHARDWARE.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyLineHARDWARE.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RT1012
            // 
            this.RT1012.CacheConnection = false;
            this.RT1012.CommandText = resources.GetString("RT1012.CommandText");
            this.RT1012.CommandTimeout = 30;
            this.RT1012.CommandType = System.Data.CommandType.Text;
            this.RT1012.DynamicTableName = false;
            this.RT1012.EEPAlias = null;
            this.RT1012.EncodingAfter = null;
            this.RT1012.EncodingBefore = "Windows-1252";
            this.RT1012.EncodingConvert = null;
            this.RT1012.InfoConnection = this.InfoConnection1;
            this.RT1012.MultiSetWhere = false;
            this.RT1012.Name = "RT1012";
            this.RT1012.NotificationAutoEnlist = false;
            this.RT1012.SecExcept = null;
            this.RT1012.SecFieldName = null;
            this.RT1012.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT1012.SelectPaging = false;
            this.RT1012.SelectTop = 0;
            this.RT1012.SiteControl = false;
            this.RT1012.SiteFieldName = null;
            this.RT1012.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT10121
            // 
            this.RT10121.CacheConnection = false;
            this.RT10121.CommandText = resources.GetString("RT10121.CommandText");
            this.RT10121.CommandTimeout = 30;
            this.RT10121.CommandType = System.Data.CommandType.Text;
            this.RT10121.DynamicTableName = false;
            this.RT10121.EEPAlias = null;
            this.RT10121.EncodingAfter = null;
            this.RT10121.EncodingBefore = "Windows-1252";
            this.RT10121.EncodingConvert = null;
            this.RT10121.InfoConnection = this.InfoConnection1;
            keyItem2.KeyName = "comq1";
            keyItem12.KeyName = "lineq1";
            keyItem13.KeyName = "PRTNO";
            keyItem14.KeyName = "seq";
            keyItem15.KeyName = "SEQ2";
            this.RT10121.KeyFields.Add(keyItem2);
            this.RT10121.KeyFields.Add(keyItem12);
            this.RT10121.KeyFields.Add(keyItem13);
            this.RT10121.KeyFields.Add(keyItem14);
            this.RT10121.KeyFields.Add(keyItem15);
            this.RT10121.MultiSetWhere = false;
            this.RT10121.Name = "RT10121";
            this.RT10121.NotificationAutoEnlist = false;
            this.RT10121.SecExcept = null;
            this.RT10121.SecFieldName = null;
            this.RT10121.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT10121.SelectPaging = false;
            this.RT10121.SelectTop = 0;
            this.RT10121.SiteControl = false;
            this.RT10121.SiteFieldName = null;
            this.RT10121.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyH)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyH)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineHARDWARE)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1012)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10121)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyH;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyH;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyH;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand RTLessorAVSCmtyLineHARDWARE;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyLineHARDWARE;
        private Srvtools.InfoCommand RT1012;
        private Srvtools.InfoCommand RT10121;
    }
}
