//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment,附件,附件,attachment,attachment,attachment,attachment,attachment.
        /// </summary>
        internal static string attachment {
            get {
                return ResourceManager.GetString("attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add,添加(&amp;A),添加(&amp;A),&amp;Add,&amp;Add,&amp;Add,&amp;Add,&amp;Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel,取消(&amp;C),取消(&amp;C),&amp;Cancel,&amp;Cancel,&amp;Cancel,&amp;Cancel,&amp;Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug,調試(&amp;E),调试(&amp;E),&amp;Debug,&amp;Debug,&amp;Debug,&amp;Debug,&amp;Debug.
        /// </summary>
        internal static string btnDebug {
            get {
                return ResourceManager.GetString("btnDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit,編輯(&amp;E),编辑(&amp;E),&amp;Edit,&amp;Edit,&amp;Edit,&amp;Edit,&amp;Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK,確定(&amp;O),确定(&amp;O),&amp;OK,&amp;OK,&amp;OK,&amp;OK,&amp;OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output,輸出,输出,Output,Output,Output,Output,Output.
        /// </summary>
        internal static string btnOutput {
            get {
                return ResourceManager.GetString("btnOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove,移除(&amp;R),移除(&amp;R),&amp;Remove,&amp;Remove,&amp;Remove,&amp;Remove,&amp;Remove.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset,重置(&amp;R),重置(&amp;R),&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save,保存(&amp;S),保存(&amp;S),&amp;Save,&amp;Save,&amp;Save,&amp;Save,&amp;Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send,發送(&amp;S),发送(&amp;S),&amp;Send,&amp;Send,&amp;Send,&amp;Send,&amp;Send.
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start,开始(&amp;S),开始(&amp;S),&amp;Start,&amp;Start,&amp;Start,&amp;Start,&amp;Start.
        /// </summary>
        internal static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo,撤消(&amp;U),撤消(&amp;U),&amp;Undo,&amp;Undo,&amp;Undo,&amp;Undo,&amp;Undo.
        /// </summary>
        internal static string btnUndo {
            get {
                return ResourceManager.GetString("btnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View,查看(&amp;V),查看(&amp;V),&amp;View,&amp;View,&amp;View,&amp;View,&amp;View.
        /// </summary>
        internal static string btnView {
            get {
                return ResourceManager.GetString("btnView", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DataSet {
            get {
                object obj = ResourceManager.GetObject("DataSet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default,默認,默认,Default,Default,Default,Default,Default.
        /// </summary>
        internal static string defaulvalue {
            get {
                return ResourceManager.GetString("defaulvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail,詳情,详情,Detail,Detail,Detail,Detail,Detail.
        /// </summary>
        internal static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor,編輯器,编辑器,Editor,Editor,Editor,Editor,Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail,電子郵件,电子邮件,E-mail,E-mail,E-mail,E-mail,E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap function {
            get {
                object obj = ResourceManager.GetObject("function", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail from,發件人,发件人,Mail from,Mail from,Mail from,Mail from,Mail from.
        /// </summary>
        internal static string mailfrom {
            get {
                return ResourceManager.GetString("mailfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail to,收件人,收件人,Mail to,Mail to,Mail to,Mail to,Mail to.
        /// </summary>
        internal static string mailto {
            get {
                return ResourceManager.GetString("mailto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member,成員,成员,member,member,member,member,member.
        /// </summary>
        internal static string member {
            get {
                return ResourceManager.GetString("member", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap micro {
            get {
                object obj = ResourceManager.GetObject("micro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password,密碼,密码,Password,Password,Password,Password,Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to properties,屬性,属性,properties,properties,properties,properties,properties.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap property {
            get {
                object obj = ResourceManager.GetObject("property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server,服務器,服务器,Server,Server,Server,Server,Server.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap value {
            get {
                object obj = ResourceManager.GetObject("value", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap word {
            get {
                object obj = ResourceManager.GetObject("word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
