SELECT * FROM RTArea
SELECT * FROM RTAreaCty
SELECT * FROM RTAreaTownShip
WHERE CUTID = '05'
SELECT * FROM RTCounty

UPDATE RTCounty
SET CUTNC = '®ç¶é¥«'
WHERE CUTID='05'

UPDATE RTAreaTownShip
SET TOWNSHIP = SUBSTRING(TOWNSHIP,1,2) + '°Ï'
WHERE CUTID = '05'