//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWizard2015 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandBar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandBar() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MWizard2015.CommandBar", typeof(CommandBar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string enAction {
            get {
                return ResourceManager.GetString("enAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        internal static string enBuild {
            get {
                return ResourceManager.GetString("enBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string enData {
            get {
                return ResourceManager.GetString("enData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 的本地化字符串。
        /// </summary>
        internal static string enDatabase {
            get {
                return ResourceManager.GetString("enDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string enDebug {
            get {
                return ResourceManager.GetString("enDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagram 的本地化字符串。
        /// </summary>
        internal static string enDiagram {
            get {
                return ResourceManager.GetString("enDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string enEdit {
            get {
                return ResourceManager.GetString("enEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string enFile {
            get {
                return ResourceManager.GetString("enFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string enFormat {
            get {
                return ResourceManager.GetString("enFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        internal static string enFrames {
            get {
                return ResourceManager.GetString("enFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string enHelp {
            get {
                return ResourceManager.GetString("enHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string enImage {
            get {
                return ResourceManager.GetString("enImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string enProject {
            get {
                return ResourceManager.GetString("enProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string enQuery {
            get {
                return ResourceManager.GetString("enQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schema 的本地化字符串。
        /// </summary>
        internal static string enSchema {
            get {
                return ResourceManager.GetString("enSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        internal static string enStyles {
            get {
                return ResourceManager.GetString("enStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table 的本地化字符串。
        /// </summary>
        internal static string enTable {
            get {
                return ResourceManager.GetString("enTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        internal static string enTools {
            get {
                return ResourceManager.GetString("enTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string enView {
            get {
                return ResourceManager.GetString("enView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        internal static string enWindow {
            get {
                return ResourceManager.GetString("enWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string enXML {
            get {
                return ResourceManager.GetString("enXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string jaAction {
            get {
                return ResourceManager.GetString("jaAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビルド 的本地化字符串。
        /// </summary>
        internal static string jaBuild {
            get {
                return ResourceManager.GetString("jaBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データ 的本地化字符串。
        /// </summary>
        internal static string jaData {
            get {
                return ResourceManager.GetString("jaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 データベース 的本地化字符串。
        /// </summary>
        internal static string jaDatabase {
            get {
                return ResourceManager.GetString("jaDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 デバッグ 的本地化字符串。
        /// </summary>
        internal static string jaDebug {
            get {
                return ResourceManager.GetString("jaDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ダイアグラム 的本地化字符串。
        /// </summary>
        internal static string jaDiagram {
            get {
                return ResourceManager.GetString("jaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 編集 的本地化字符串。
        /// </summary>
        internal static string jaEdit {
            get {
                return ResourceManager.GetString("jaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ファイル 的本地化字符串。
        /// </summary>
        internal static string jaFile {
            get {
                return ResourceManager.GetString("jaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 書式 的本地化字符串。
        /// </summary>
        internal static string jaFormat {
            get {
                return ResourceManager.GetString("jaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フレーム 的本地化字符串。
        /// </summary>
        internal static string jaFrames {
            get {
                return ResourceManager.GetString("jaFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘルプ 的本地化字符串。
        /// </summary>
        internal static string jaHelp {
            get {
                return ResourceManager.GetString("jaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 イメージ 的本地化字符串。
        /// </summary>
        internal static string jaImage {
            get {
                return ResourceManager.GetString("jaImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロジェクト 的本地化字符串。
        /// </summary>
        internal static string jaProject {
            get {
                return ResourceManager.GetString("jaProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クエリ 的本地化字符串。
        /// </summary>
        internal static string jaQuery {
            get {
                return ResourceManager.GetString("jaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スキーマ 的本地化字符串。
        /// </summary>
        internal static string jaSchema {
            get {
                return ResourceManager.GetString("jaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スタイル 的本地化字符串。
        /// </summary>
        internal static string jaStyles {
            get {
                return ResourceManager.GetString("jaStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テーブル 的本地化字符串。
        /// </summary>
        internal static string jaTable {
            get {
                return ResourceManager.GetString("jaTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ツール 的本地化字符串。
        /// </summary>
        internal static string jaTools {
            get {
                return ResourceManager.GetString("jaTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示 的本地化字符串。
        /// </summary>
        internal static string jaView {
            get {
                return ResourceManager.GetString("jaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ 的本地化字符串。
        /// </summary>
        internal static string jaWindow {
            get {
                return ResourceManager.GetString("jaWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 的本地化字符串。
        /// </summary>
        internal static string jaXML {
            get {
                return ResourceManager.GetString("jaXML", resourceCulture);
            }
        }
    }
}
