namespace sRT1041
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.KeyItem keyItem17 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem18 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem19 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustRepair = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustRepair = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustRepair = new Srvtools.InfoCommand(this.components);
            this.cmdRT1041 = new Srvtools.InfoCommand(this.components);
            this.V_RTLessorAVSCUST = new Srvtools.InfoCommand(this.components);
            this.V_RTLessorAVSCUSTAR = new Srvtools.InfoCommand(this.components);
            this.RTLessorAVSCustAR = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustAR = new Srvtools.UpdateComponent(this.components);
            this.cmdRT10411 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104111 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104112 = new Srvtools.InfoCommand(this.components);
            this.cmdRT1041121 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104113 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustRepair)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustRepair)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1041)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RTLessorAVSCUST)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RTLessorAVSCUSTAR)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustAR)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10411)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104111)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104112)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1041121)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104113)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT1041";
            service1.NonLogin = false;
            service1.ServiceName = "smRT1041";
            service2.DelegateName = "smRT104111";
            service2.NonLogin = false;
            service2.ServiceName = "smRT104111";
            service3.DelegateName = "smRT104112";
            service3.NonLogin = false;
            service3.ServiceName = "smRT104112";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustRepair
            // 
            this.RTLessorAVSCustRepair.CacheConnection = false;
            this.RTLessorAVSCustRepair.CommandText = "SELECT dbo.[RTLessorAVSCustRepair].* FROM dbo.[RTLessorAVSCustRepair]";
            this.RTLessorAVSCustRepair.CommandTimeout = 30;
            this.RTLessorAVSCustRepair.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustRepair.DynamicTableName = false;
            this.RTLessorAVSCustRepair.EEPAlias = null;
            this.RTLessorAVSCustRepair.EncodingAfter = null;
            this.RTLessorAVSCustRepair.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustRepair.EncodingConvert = null;
            this.RTLessorAVSCustRepair.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "ENTRYNO";
            this.RTLessorAVSCustRepair.KeyFields.Add(keyItem1);
            this.RTLessorAVSCustRepair.KeyFields.Add(keyItem2);
            this.RTLessorAVSCustRepair.MultiSetWhere = false;
            this.RTLessorAVSCustRepair.Name = "RTLessorAVSCustRepair";
            this.RTLessorAVSCustRepair.NotificationAutoEnlist = false;
            this.RTLessorAVSCustRepair.SecExcept = null;
            this.RTLessorAVSCustRepair.SecFieldName = null;
            this.RTLessorAVSCustRepair.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustRepair.SelectPaging = false;
            this.RTLessorAVSCustRepair.SelectTop = 0;
            this.RTLessorAVSCustRepair.SiteControl = false;
            this.RTLessorAVSCustRepair.SiteFieldName = null;
            this.RTLessorAVSCustRepair.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustRepair
            // 
            this.ucRTLessorAVSCustRepair.AutoTrans = true;
            this.ucRTLessorAVSCustRepair.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CUSID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ENTRYNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "APPLYDAT";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "EQUIP";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "EQUIPAMT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "SETAMT";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "MOVEAMT";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "PAYTYPE";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "CREDITCARDTYPE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "CREDITBANK";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CREDITCARDNO";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CREDITNAME";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CREDITDUEM";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "CREDITDUEY";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "MAXENTRYNO";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "TARDAT";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "BATCHNO";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "TUSR";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "FINISHDAT";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "CANCELDAT";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "CANCELUSR";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "MEMO";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "REALENGINEER";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "REALCONSIGNEE";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "UDAT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "UUSR";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "RCVMONEYDAT";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustRepair.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustRepair.LogInfo = null;
            this.ucRTLessorAVSCustRepair.Name = "ucRTLessorAVSCustRepair";
            this.ucRTLessorAVSCustRepair.RowAffectsCheck = true;
            this.ucRTLessorAVSCustRepair.SelectCmd = this.RTLessorAVSCustRepair;
            this.ucRTLessorAVSCustRepair.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustRepair.SendSQLCmd = true;
            this.ucRTLessorAVSCustRepair.ServerModify = true;
            this.ucRTLessorAVSCustRepair.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustRepair.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustRepair.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustRepair.UseTranscationScope = false;
            this.ucRTLessorAVSCustRepair.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustRepair
            // 
            this.View_RTLessorAVSCustRepair.CacheConnection = false;
            this.View_RTLessorAVSCustRepair.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustRepair]";
            this.View_RTLessorAVSCustRepair.CommandTimeout = 30;
            this.View_RTLessorAVSCustRepair.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustRepair.DynamicTableName = false;
            this.View_RTLessorAVSCustRepair.EEPAlias = null;
            this.View_RTLessorAVSCustRepair.EncodingAfter = null;
            this.View_RTLessorAVSCustRepair.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustRepair.EncodingConvert = null;
            this.View_RTLessorAVSCustRepair.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "ENTRYNO";
            this.View_RTLessorAVSCustRepair.KeyFields.Add(keyItem3);
            this.View_RTLessorAVSCustRepair.KeyFields.Add(keyItem4);
            this.View_RTLessorAVSCustRepair.MultiSetWhere = false;
            this.View_RTLessorAVSCustRepair.Name = "View_RTLessorAVSCustRepair";
            this.View_RTLessorAVSCustRepair.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustRepair.SecExcept = null;
            this.View_RTLessorAVSCustRepair.SecFieldName = null;
            this.View_RTLessorAVSCustRepair.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustRepair.SelectPaging = false;
            this.View_RTLessorAVSCustRepair.SelectTop = 0;
            this.View_RTLessorAVSCustRepair.SiteControl = false;
            this.View_RTLessorAVSCustRepair.SiteFieldName = null;
            this.View_RTLessorAVSCustRepair.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1041
            // 
            this.cmdRT1041.CacheConnection = false;
            this.cmdRT1041.CommandText = "usp_RTLessorAVSCustRepairAR";
            this.cmdRT1041.CommandTimeout = 30;
            this.cmdRT1041.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1041.DynamicTableName = false;
            this.cmdRT1041.EEPAlias = null;
            this.cmdRT1041.EncodingAfter = null;
            this.cmdRT1041.EncodingBefore = "Windows-1252";
            this.cmdRT1041.EncodingConvert = null;
            this.cmdRT1041.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter1.ParameterName = "cusid";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 15;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "entryno";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "usr";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 6;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "typ";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 8;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "batchno";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 12;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1041.InfoParameters.Add(infoParameter1);
            this.cmdRT1041.InfoParameters.Add(infoParameter2);
            this.cmdRT1041.InfoParameters.Add(infoParameter3);
            this.cmdRT1041.InfoParameters.Add(infoParameter4);
            this.cmdRT1041.InfoParameters.Add(infoParameter5);
            this.cmdRT1041.MultiSetWhere = false;
            this.cmdRT1041.Name = "cmdRT1041";
            this.cmdRT1041.NotificationAutoEnlist = false;
            this.cmdRT1041.SecExcept = null;
            this.cmdRT1041.SecFieldName = null;
            this.cmdRT1041.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1041.SelectPaging = false;
            this.cmdRT1041.SelectTop = 0;
            this.cmdRT1041.SiteControl = false;
            this.cmdRT1041.SiteFieldName = null;
            this.cmdRT1041.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // V_RTLessorAVSCUST
            // 
            this.V_RTLessorAVSCUST.CacheConnection = false;
            this.V_RTLessorAVSCUST.CommandText = "SELECT * FROM RTLessorAVSCUST";
            this.V_RTLessorAVSCUST.CommandTimeout = 30;
            this.V_RTLessorAVSCUST.CommandType = System.Data.CommandType.Text;
            this.V_RTLessorAVSCUST.DynamicTableName = false;
            this.V_RTLessorAVSCUST.EEPAlias = null;
            this.V_RTLessorAVSCUST.EncodingAfter = null;
            this.V_RTLessorAVSCUST.EncodingBefore = "Windows-1252";
            this.V_RTLessorAVSCUST.EncodingConvert = null;
            this.V_RTLessorAVSCUST.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "COMQ1";
            keyItem6.KeyName = "LINEQ1";
            keyItem7.KeyName = "CUSID";
            this.V_RTLessorAVSCUST.KeyFields.Add(keyItem5);
            this.V_RTLessorAVSCUST.KeyFields.Add(keyItem6);
            this.V_RTLessorAVSCUST.KeyFields.Add(keyItem7);
            this.V_RTLessorAVSCUST.MultiSetWhere = false;
            this.V_RTLessorAVSCUST.Name = "V_RTLessorAVSCUST";
            this.V_RTLessorAVSCUST.NotificationAutoEnlist = false;
            this.V_RTLessorAVSCUST.SecExcept = null;
            this.V_RTLessorAVSCUST.SecFieldName = null;
            this.V_RTLessorAVSCUST.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.V_RTLessorAVSCUST.SelectPaging = false;
            this.V_RTLessorAVSCUST.SelectTop = 0;
            this.V_RTLessorAVSCUST.SiteControl = false;
            this.V_RTLessorAVSCUST.SiteFieldName = null;
            this.V_RTLessorAVSCUST.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // V_RTLessorAVSCUSTAR
            // 
            this.V_RTLessorAVSCUSTAR.CacheConnection = false;
            this.V_RTLessorAVSCUSTAR.CommandText = "SELECT * FROM RTLessorAVSCUSTAR";
            this.V_RTLessorAVSCUSTAR.CommandTimeout = 30;
            this.V_RTLessorAVSCUSTAR.CommandType = System.Data.CommandType.Text;
            this.V_RTLessorAVSCUSTAR.DynamicTableName = false;
            this.V_RTLessorAVSCUSTAR.EEPAlias = null;
            this.V_RTLessorAVSCUSTAR.EncodingAfter = null;
            this.V_RTLessorAVSCUSTAR.EncodingBefore = "Windows-1252";
            this.V_RTLessorAVSCUSTAR.EncodingConvert = null;
            this.V_RTLessorAVSCUSTAR.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "CUSID";
            keyItem9.KeyName = "BATCHNO";
            this.V_RTLessorAVSCUSTAR.KeyFields.Add(keyItem8);
            this.V_RTLessorAVSCUSTAR.KeyFields.Add(keyItem9);
            this.V_RTLessorAVSCUSTAR.MultiSetWhere = false;
            this.V_RTLessorAVSCUSTAR.Name = "V_RTLessorAVSCUSTAR";
            this.V_RTLessorAVSCUSTAR.NotificationAutoEnlist = false;
            this.V_RTLessorAVSCUSTAR.SecExcept = null;
            this.V_RTLessorAVSCUSTAR.SecFieldName = null;
            this.V_RTLessorAVSCUSTAR.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.V_RTLessorAVSCUSTAR.SelectPaging = false;
            this.V_RTLessorAVSCUSTAR.SelectTop = 0;
            this.V_RTLessorAVSCUSTAR.SiteControl = false;
            this.V_RTLessorAVSCUSTAR.SiteFieldName = null;
            this.V_RTLessorAVSCUSTAR.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RTLessorAVSCustAR
            // 
            this.RTLessorAVSCustAR.CacheConnection = false;
            this.RTLessorAVSCustAR.CommandText = "SELECT * FROM RTLessorAVSCustAR";
            this.RTLessorAVSCustAR.CommandTimeout = 30;
            this.RTLessorAVSCustAR.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustAR.DynamicTableName = false;
            this.RTLessorAVSCustAR.EEPAlias = null;
            this.RTLessorAVSCustAR.EncodingAfter = null;
            this.RTLessorAVSCustAR.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustAR.EncodingConvert = null;
            this.RTLessorAVSCustAR.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "CUSID";
            keyItem11.KeyName = "BATCHNO";
            this.RTLessorAVSCustAR.KeyFields.Add(keyItem10);
            this.RTLessorAVSCustAR.KeyFields.Add(keyItem11);
            this.RTLessorAVSCustAR.MultiSetWhere = false;
            this.RTLessorAVSCustAR.Name = "RTLessorAVSCustAR";
            this.RTLessorAVSCustAR.NotificationAutoEnlist = false;
            this.RTLessorAVSCustAR.SecExcept = null;
            this.RTLessorAVSCustAR.SecFieldName = null;
            this.RTLessorAVSCustAR.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustAR.SelectPaging = false;
            this.RTLessorAVSCustAR.SelectTop = 0;
            this.RTLessorAVSCustAR.SiteControl = false;
            this.RTLessorAVSCustAR.SiteFieldName = null;
            this.RTLessorAVSCustAR.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustAR
            // 
            this.ucRTLessorAVSCustAR.AutoTrans = true;
            this.ucRTLessorAVSCustAR.ExceptJoin = false;
            this.ucRTLessorAVSCustAR.LogInfo = null;
            this.ucRTLessorAVSCustAR.Name = "ucRTLessorAVSCustAR";
            this.ucRTLessorAVSCustAR.RowAffectsCheck = true;
            this.ucRTLessorAVSCustAR.SelectCmd = this.RTLessorAVSCustAR;
            this.ucRTLessorAVSCustAR.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustAR.SendSQLCmd = true;
            this.ucRTLessorAVSCustAR.ServerModify = true;
            this.ucRTLessorAVSCustAR.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustAR.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustAR.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustAR.UseTranscationScope = false;
            this.ucRTLessorAVSCustAR.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // cmdRT10411
            // 
            this.cmdRT10411.CacheConnection = false;
            this.cmdRT10411.CommandText = resources.GetString("cmdRT10411.CommandText");
            this.cmdRT10411.CommandTimeout = 30;
            this.cmdRT10411.CommandType = System.Data.CommandType.Text;
            this.cmdRT10411.DynamicTableName = false;
            this.cmdRT10411.EEPAlias = null;
            this.cmdRT10411.EncodingAfter = null;
            this.cmdRT10411.EncodingBefore = "Windows-1252";
            this.cmdRT10411.EncodingConvert = null;
            this.cmdRT10411.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "CUSID";
            keyItem13.KeyName = "BATCHNO";
            this.cmdRT10411.KeyFields.Add(keyItem12);
            this.cmdRT10411.KeyFields.Add(keyItem13);
            this.cmdRT10411.MultiSetWhere = false;
            this.cmdRT10411.Name = "cmdRT10411";
            this.cmdRT10411.NotificationAutoEnlist = false;
            this.cmdRT10411.SecExcept = null;
            this.cmdRT10411.SecFieldName = null;
            this.cmdRT10411.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10411.SelectPaging = false;
            this.cmdRT10411.SelectTop = 0;
            this.cmdRT10411.SiteControl = false;
            this.cmdRT10411.SiteFieldName = null;
            this.cmdRT10411.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104111
            // 
            this.cmdRT104111.CacheConnection = false;
            this.cmdRT104111.CommandText = "usp_RTLessorAVSCustARClearExe";
            this.cmdRT104111.CommandTimeout = 30;
            this.cmdRT104111.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT104111.DynamicTableName = false;
            this.cmdRT104111.EEPAlias = null;
            this.cmdRT104111.EncodingAfter = null;
            this.cmdRT104111.EncodingBefore = "Windows-1252";
            this.cmdRT104111.EncodingConvert = null;
            this.cmdRT104111.InfoConnection = this.InfoConnection1;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter6.ParameterName = "cusid";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 15;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter7.ParameterName = "batchno";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 12;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter8.ParameterName = "realamtx";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 0;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "usr";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 6;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT104111.InfoParameters.Add(infoParameter6);
            this.cmdRT104111.InfoParameters.Add(infoParameter7);
            this.cmdRT104111.InfoParameters.Add(infoParameter8);
            this.cmdRT104111.InfoParameters.Add(infoParameter9);
            this.cmdRT104111.MultiSetWhere = false;
            this.cmdRT104111.Name = "cmdRT104111";
            this.cmdRT104111.NotificationAutoEnlist = false;
            this.cmdRT104111.SecExcept = null;
            this.cmdRT104111.SecFieldName = null;
            this.cmdRT104111.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104111.SelectPaging = false;
            this.cmdRT104111.SelectTop = 0;
            this.cmdRT104111.SiteControl = false;
            this.cmdRT104111.SiteFieldName = null;
            this.cmdRT104111.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104112
            // 
            this.cmdRT104112.CacheConnection = false;
            this.cmdRT104112.CommandText = resources.GetString("cmdRT104112.CommandText");
            this.cmdRT104112.CommandTimeout = 30;
            this.cmdRT104112.CommandType = System.Data.CommandType.Text;
            this.cmdRT104112.DynamicTableName = false;
            this.cmdRT104112.EEPAlias = null;
            this.cmdRT104112.EncodingAfter = null;
            this.cmdRT104112.EncodingBefore = "Windows-1252";
            this.cmdRT104112.EncodingConvert = null;
            this.cmdRT104112.InfoConnection = this.InfoConnection1;
            keyItem14.KeyName = "CUSID";
            keyItem15.KeyName = "BATCHNO";
            keyItem16.KeyName = "SEQ";
            this.cmdRT104112.KeyFields.Add(keyItem14);
            this.cmdRT104112.KeyFields.Add(keyItem15);
            this.cmdRT104112.KeyFields.Add(keyItem16);
            this.cmdRT104112.MultiSetWhere = false;
            this.cmdRT104112.Name = "cmdRT104112";
            this.cmdRT104112.NotificationAutoEnlist = false;
            this.cmdRT104112.SecExcept = null;
            this.cmdRT104112.SecFieldName = null;
            this.cmdRT104112.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104112.SelectPaging = false;
            this.cmdRT104112.SelectTop = 0;
            this.cmdRT104112.SiteControl = false;
            this.cmdRT104112.SiteFieldName = null;
            this.cmdRT104112.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1041121
            // 
            this.cmdRT1041121.CacheConnection = false;
            this.cmdRT1041121.CommandText = "usp_RTLessorAVSCustARClearRTN";
            this.cmdRT1041121.CommandTimeout = 30;
            this.cmdRT1041121.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1041121.DynamicTableName = false;
            this.cmdRT1041121.EEPAlias = null;
            this.cmdRT1041121.EncodingAfter = null;
            this.cmdRT1041121.EncodingBefore = "Windows-1252";
            this.cmdRT1041121.EncodingConvert = null;
            this.cmdRT1041121.InfoConnection = this.InfoConnection1;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter10.ParameterName = "cusid";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 15;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "batchno";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 12;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter12.ParameterName = "seq";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 0;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter13.ParameterName = "usr";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 6;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1041121.InfoParameters.Add(infoParameter10);
            this.cmdRT1041121.InfoParameters.Add(infoParameter11);
            this.cmdRT1041121.InfoParameters.Add(infoParameter12);
            this.cmdRT1041121.InfoParameters.Add(infoParameter13);
            this.cmdRT1041121.MultiSetWhere = false;
            this.cmdRT1041121.Name = "cmdRT1041121";
            this.cmdRT1041121.NotificationAutoEnlist = false;
            this.cmdRT1041121.SecExcept = null;
            this.cmdRT1041121.SecFieldName = null;
            this.cmdRT1041121.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1041121.SelectPaging = false;
            this.cmdRT1041121.SelectTop = 0;
            this.cmdRT1041121.SiteControl = false;
            this.cmdRT1041121.SiteFieldName = null;
            this.cmdRT1041121.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104113
            // 
            this.cmdRT104113.CacheConnection = false;
            this.cmdRT104113.CommandText = resources.GetString("cmdRT104113.CommandText");
            this.cmdRT104113.CommandTimeout = 30;
            this.cmdRT104113.CommandType = System.Data.CommandType.Text;
            this.cmdRT104113.DynamicTableName = false;
            this.cmdRT104113.EEPAlias = null;
            this.cmdRT104113.EncodingAfter = null;
            this.cmdRT104113.EncodingBefore = "Windows-1252";
            this.cmdRT104113.EncodingConvert = null;
            this.cmdRT104113.InfoConnection = this.InfoConnection1;
            keyItem17.KeyName = "CUSID";
            keyItem18.KeyName = "BATCHNO";
            keyItem19.KeyName = "SEQ";
            this.cmdRT104113.KeyFields.Add(keyItem17);
            this.cmdRT104113.KeyFields.Add(keyItem18);
            this.cmdRT104113.KeyFields.Add(keyItem19);
            this.cmdRT104113.MultiSetWhere = false;
            this.cmdRT104113.Name = "cmdRT104113";
            this.cmdRT104113.NotificationAutoEnlist = false;
            this.cmdRT104113.SecExcept = null;
            this.cmdRT104113.SecFieldName = null;
            this.cmdRT104113.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104113.SelectPaging = false;
            this.cmdRT104113.SelectTop = 0;
            this.cmdRT104113.SiteControl = false;
            this.cmdRT104113.SiteFieldName = null;
            this.cmdRT104113.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustRepair)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustRepair)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1041)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RTLessorAVSCUST)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RTLessorAVSCUSTAR)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustAR)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10411)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104111)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104112)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1041121)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104113)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustRepair;
        private Srvtools.UpdateComponent ucRTLessorAVSCustRepair;
        private Srvtools.InfoCommand View_RTLessorAVSCustRepair;
        private Srvtools.InfoCommand cmdRT1041;
        private Srvtools.InfoCommand V_RTLessorAVSCUST;
        private Srvtools.InfoCommand V_RTLessorAVSCUSTAR;
        private Srvtools.InfoCommand RTLessorAVSCustAR;
        private Srvtools.UpdateComponent ucRTLessorAVSCustAR;
        private Srvtools.InfoCommand cmdRT10411;
        private Srvtools.InfoCommand cmdRT104111;
        private Srvtools.InfoCommand cmdRT104112;
        private Srvtools.InfoCommand cmdRT1041121;
        private Srvtools.InfoCommand cmdRT104113;
    }
}
