//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infolight.EasilyReportTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infolight.EasilyReportTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascend,升冪,升序.
        /// </summary>
        internal static string Ascend {
            get {
                return ResourceManager.GetString("Ascend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank,空白,空白.
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add,添加,添加.
        /// </summary>
        internal static string btAdd {
            get {
                return ResourceManager.GetString("btAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel,取消,取消.
        /// </summary>
        internal static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change,換圖,换图.
        /// </summary>
        internal static string btChange {
            get {
                return ResourceManager.GetString("btChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close,關閉,关闭.
        /// </summary>
        internal static string btClose {
            get {
                return ResourceManager.GetString("btClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete,刪除,删除.
        /// </summary>
        internal static string btDelete {
            get {
                return ResourceManager.GetString("btDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export,輸出,输出.
        /// </summary>
        internal static string btExport {
            get {
                return ResourceManager.GetString("btExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Font...,欄位字型,字段字型.
        /// </summary>
        internal static string btFieldFont {
            get {
                return ResourceManager.GetString("btFieldFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font...,字型...,字型....
        /// </summary>
        internal static string btFont {
            get {
                return ResourceManager.GetString("btFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Font...,表尾字型...,表尾字型....
        /// </summary>
        internal static string btFooterFont {
            get {
                return ResourceManager.GetString("btFooterFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Font...,表頭字型...,表头字型....
        /// </summary>
        internal static string btHeaderFont {
            get {
                return ResourceManager.GetString("btHeaderFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK,確定,确定.
        /// </summary>
        internal static string btOK {
            get {
                return ResourceManager.GetString("btOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview,預覽,预览.
        /// </summary>
        internal static string btPreview {
            get {
                return ResourceManager.GetString("btPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove,移除,移除.
        /// </summary>
        internal static string btRemove {
            get {
                return ResourceManager.GetString("btRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset,重置(&amp;R),重置(&amp;R),&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset,&amp;Reset.
        /// </summary>
        internal static string btReset {
            get {
                return ResourceManager.GetString("btReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save,保存設定,保存设定.
        /// </summary>
        internal static string btSave {
            get {
                return ResourceManager.GetString("btSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select,選擇,选择.
        /// </summary>
        internal static string btSelect {
            get {
                return ResourceManager.GetString("btSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture...,選擇圖檔...,选择图片....
        /// </summary>
        internal static string btSelectPicture {
            get {
                return ResourceManager.GetString("btSelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send,發送(&amp;S),发送(&amp;S),&amp;Send,&amp;Send,&amp;Send,&amp;Send,&amp;Send.
        /// </summary>
        internal static string btSend {
            get {
                return ResourceManager.GetString("btSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send,發送,发送,Send,Send,Send,Send,Send.
        /// </summary>
        internal static string btWebSendMail {
            get {
                return ResourceManager.GetString("btWebSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column GridLine,行格線,列格线.
        /// </summary>
        internal static string cbColumnGridLine {
            get {
                return ResourceManager.GetString("cbColumnGridLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collumn GridLine,内行格線,内列格线.
        /// </summary>
        internal static string cbColumnInsideLine {
            get {
                return ResourceManager.GetString("cbColumnInsideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default,默認,默认.
        /// </summary>
        internal static string cbDefault {
            get {
                return ResourceManager.GetString("cbDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail,詳情,详情.
        /// </summary>
        internal static string cbDetail {
            get {
                return ResourceManager.GetString("cbDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupTotal,分組匯總,分组汇总.
        /// </summary>
        internal static string cbGroupTotal {
            get {
                return ResourceManager.GetString("cbGroupTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header repeat,重複表頭,重复表头.
        /// </summary>
        internal static string cbHeaderRepeat {
            get {
                return ResourceManager.GetString("cbHeaderRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLine,換行,换行.
        /// </summary>
        internal static string cbNewLine {
            get {
                return ResourceManager.GetString("cbNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row GridLine,列格線,行格线.
        /// </summary>
        internal static string cbRowGridLine {
            get {
                return ResourceManager.GetString("cbRowGridLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress if duplicated,群組重複則不顯示,群组重复则不显示.
        /// </summary>
        internal static string cbSuppressIfDuplicated {
            get {
                return ResourceManager.GetString("cbSuppressIfDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mail,發送郵件,发送邮件.
        /// </summary>
        internal static string cbxSendMail {
            get {
                return ResourceManager.GetString("cbxSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName,公司名稱,公司名称.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstantItem,常用變數,常用参数.
        /// </summary>
        internal static string ConstantItem {
            get {
                return ResourceManager.GetString("ConstantItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSourceItem,欄位,栏位.
        /// </summary>
        internal static string DataSourceItem {
            get {
                return ResourceManager.GetString("DataSourceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descend,降冪,降序.
        /// </summary>
        internal static string Descend {
            get {
                return ResourceManager.GetString("Descend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description,備注,备注.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail,電子郵件,电子邮件,E-mail,E-mail,E-mail,E-mail,E-mail.
        /// </summary>
        internal static string fmEmail {
            get {
                return ResourceManager.GetString("fmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template,模板選擇,模板选择.
        /// </summary>
        internal static string fmLoadTemplate {
            get {
                return ResourceManager.GetString("fmLoadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Picture,圖檔選擇,图片选择.
        /// </summary>
        internal static string fmPictures {
            get {
                return ResourceManager.GetString("fmPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture View,圖檔預覽,图片预览.
        /// </summary>
        internal static string fmPictureView {
            get {
                return ResourceManager.GetString("fmPictureView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily Report Designer,簡易報表設計,简易报表设计.
        /// </summary>
        internal static string fmReportExport {
            get {
                return ResourceManager.GetString("fmReportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Template,另存模板,另存模板.
        /// </summary>
        internal static string fmSaveAsTemplate {
            get {
                return ResourceManager.GetString("fmSaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns,欄位,字段.
        /// </summary>
        internal static string gbColumns {
            get {
                return ResourceManager.GetString("gbColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Setting,內容設定,内容设定.
        /// </summary>
        internal static string gbContentSetting {
            get {
                return ResourceManager.GetString("gbContentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Items,表尾項目,表尾项目.
        /// </summary>
        internal static string gbFooterItems {
            get {
                return ResourceManager.GetString("gbFooterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Columns,分組欄位,分组字段.
        /// </summary>
        internal static string gbGroupColumns {
            get {
                return ResourceManager.GetString("gbGroupColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Header Items,表頭項目,表头项目.
        /// </summary>
        internal static string gbHeaderItems {
            get {
                return ResourceManager.GetString("gbHeaderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Config,電子郵件設定,电子邮件设定.
        /// </summary>
        internal static string gbMailConfig {
            get {
                return ResourceManager.GetString("gbMailConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email,發送電子郵件,发送电子邮件.
        /// </summary>
        internal static string gbMailSend {
            get {
                return ResourceManager.GetString("gbMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Setting,輸出設定,输出设定.
        /// </summary>
        internal static string gbOutputSetting {
            get {
                return ResourceManager.GetString("gbOutputSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Margin:Inches,頁邊距:英寸,页边距:英寸.
        /// </summary>
        internal static string gbPageMargin {
            get {
                return ResourceManager.GetString("gbPageMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setting,頁面設定,页面设定.
        /// </summary>
        internal static string gbPageSetting {
            get {
                return ResourceManager.GetString("gbPageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size,頁面尺寸,页面尺寸.
        /// </summary>
        internal static string gbPageSize {
            get {
                return ResourceManager.GetString("gbPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rientation,打印方向,打印方向.
        /// </summary>
        internal static string gbPrintOrientation {
            get {
                return ResourceManager.GetString("gbPrintOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Columns,被選擇的欄位,被选择的字段.
        /// </summary>
        internal static string gbSelectedColumns {
            get {
                return ResourceManager.GetString("gbSelectedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Group Columns,被選擇的分組欄位,被选择的分组字段.
        /// </summary>
        internal static string gbSelectedGroupColumns {
            get {
                return ResourceManager.GetString("gbSelectedGroupColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show GridLine,顯示格線,显示格线.
        /// </summary>
        internal static string gbShowGridLine {
            get {
                return ResourceManager.GetString("gbShowGridLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sytle Setting,樣式設定,样式设定.
        /// </summary>
        internal static string gbStyleSetting {
            get {
                return ResourceManager.GetString("gbStyleSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Download,點擊下載,点击下载.
        /// </summary>
        internal static string hlDownload {
            get {
                return ResourceManager.GetString("hlDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageItem,圖檔,图片.
        /// </summary>
        internal static string ImageItem {
            get {
                return ResourceManager.GetString("ImageItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment,附件,附件,attachment,attachment,attachment,attachment,attachment.
        /// </summary>
        internal static string lbAttachment {
            get {
                return ResourceManager.GetString("lbAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:,下:,下:.
        /// </summary>
        internal static string lbBottom {
            get {
                return ResourceManager.GetString("lbBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Alignment:,抬頭對齊:,标题对齐:.
        /// </summary>
        internal static string lbCaptionAlignment {
            get {
                return ResourceManager.GetString("lbCaptionAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption Style,抬頭樣式,标题样式.
        /// </summary>
        internal static string lbCaptionStyle {
            get {
                return ResourceManager.GetString("lbCaptionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells:,占用單元格數:,占用单元格数:.
        /// </summary>
        internal static string lbCells {
            get {
                return ResourceManager.GetString("lbCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Alignment:,欄位對齊:,字段对齐:.
        /// </summary>
        internal static string lbColumnAlignment {
            get {
                return ResourceManager.GetString("lbColumnAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Caption:,欄位抬頭:,字段标题:.
        /// </summary>
        internal static string lbColumnCaption {
            get {
                return ResourceManager.GetString("lbColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:,內容:,内容:.
        /// </summary>
        internal static string lbContent {
            get {
                return ResourceManager.GetString("lbContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Alignment:,內容對齊:,内容对齐:.
        /// </summary>
        internal static string lbContentAlignment {
            get {
                return ResourceManager.GetString("lbContentAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource:,資料源,数据源.
        /// </summary>
        internal static string lbDataSourceIndex {
            get {
                return ResourceManager.GetString("lbDataSourceIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Format:,導出格式:,输出格式:.
        /// </summary>
        internal static string lbExportFormat {
            get {
                return ResourceManager.GetString("lbExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name:,欄位名:,字段名:.
        /// </summary>
        internal static string lbField {
            get {
                return ResourceManager.GetString("lbField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Item Type,表尾項目類型,表尾项目类型.
        /// </summary>
        internal static string lbFooterItemType {
            get {
                return ResourceManager.GetString("lbFooterItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:,格式:,格式:.
        /// </summary>
        internal static string lbFormat {
            get {
                return ResourceManager.GetString("lbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupGap:,分組間隙:,分组间隙:.
        /// </summary>
        internal static string lbGroupGap {
            get {
                return ResourceManager.GetString("lbGroupGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Total Caption:,組匯總抬頭:,组汇总标题:.
        /// </summary>
        internal static string lbGroupTotalCaption {
            get {
                return ResourceManager.GetString("lbGroupTotalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Type:,分組方式:,分组方式:.
        /// </summary>
        internal static string lbGroupType {
            get {
                return ResourceManager.GetString("lbGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Item Type,表頭項目類型,表头项目类型.
        /// </summary>
        internal static string lbHeaderItemType {
            get {
                return ResourceManager.GetString("lbHeaderItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index:,索引:,索引:.
        /// </summary>
        internal static string lbIndex {
            get {
                return ResourceManager.GetString("lbIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:,左:,左:.
        /// </summary>
        internal static string lbLeft {
            get {
                return ResourceManager.GetString("lbLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail From:,寄件人:,寄件人:.
        /// </summary>
        internal static string lbMailFrom {
            get {
                return ResourceManager.GetString("lbMailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:,抬頭:,标题:.
        /// </summary>
        internal static string lbMailTitle {
            get {
                return ResourceManager.GetString("lbMailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail To:,收件人:,收件人:.
        /// </summary>
        internal static string lbMailTo {
            get {
                return ResourceManager.GetString("lbMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLine Position:,換行對齊位置:,换行对齐位置:.
        /// </summary>
        internal static string lbNewLinePosition {
            get {
                return ResourceManager.GetString("lbNewLinePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order:,排序:,排序:.
        /// </summary>
        internal static string lbOrderType {
            get {
                return ResourceManager.GetString("lbOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output FileName:,輸出檔案名:,输出文件名:.
        /// </summary>
        internal static string lbOutputFileName {
            get {
                return ResourceManager.GetString("lbOutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output FilePath:,輸出路徑:,输出路径:.
        /// </summary>
        internal static string lbOutputFilePath {
            get {
                return ResourceManager.GetString("lbOutputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Mode:,輸出模式:,输出模式:.
        /// </summary>
        internal static string lbOutputMode {
            get {
                return ResourceManager.GetString("lbOutputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Height:,頁的高度:,页的高度:.
        /// </summary>
        internal static string lbPageHeight {
            get {
                return ResourceManager.GetString("lbPageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Page Records:,每頁資料筆數:,每页记录数:.
        /// </summary>
        internal static string lbPageRecords {
            get {
                return ResourceManager.GetString("lbPageRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:,密碼:,密码:.
        /// </summary>
        internal static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures:,圖檔:,图片:.
        /// </summary>
        internal static string lbPictures {
            get {
                return ResourceManager.GetString("lbPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:,位置:,位置:.
        /// </summary>
        internal static string lbPosition {
            get {
                return ResourceManager.GetString("lbPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:,右:,右:.
        /// </summary>
        internal static string lbRight {
            get {
                return ResourceManager.GetString("lbRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select picture:,請選擇圖片:,请选择图片:.
        /// </summary>
        internal static string lbSelectPicture {
            get {
                return ResourceManager.GetString("lbSelectPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one template:,請選擇一個模板:,请选择一个模板:.
        /// </summary>
        internal static string lbSelectTemplate {
            get {
                return ResourceManager.GetString("lbSelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:,伺服器:,服务器:.
        /// </summary>
        internal static string lbSmtpServer {
            get {
                return ResourceManager.GetString("lbSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SumType,匯總類型,汇总类型.
        /// </summary>
        internal static string lbSumType {
            get {
                return ResourceManager.GetString("lbSumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input Template Name:,請輸入模板名:,请输入模板名:.
        /// </summary>
        internal static string lbTemplateName {
            get {
                return ResourceManager.GetString("lbTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:,上:,上:.
        /// </summary>
        internal static string lbTop {
            get {
                return ResourceManager.GetString("lbTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalCaption:,匯總抬頭:,汇总标题:.
        /// </summary>
        internal static string lbTotalCaption {
            get {
                return ResourceManager.GetString("lbTotalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:,寬度:,宽度:.
        /// </summary>
        internal static string lbWidth {
            get {
                return ResourceManager.GetString("lbWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTemplate...,刪除模板...,删除模板....
        /// </summary>
        internal static string MenuDeleteTemplate {
            get {
                return ResourceManager.GetString("MenuDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File,文件,文件.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Template...,讀取模板...,读取模板....
        /// </summary>
        internal static string MenuReadTemplate {
            get {
                return ResourceManager.GetString("MenuReadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Template...,另存模板...,另存模板....
        /// </summary>
        internal static string MenuSaveAsTemplate {
            get {
                return ResourceManager.GetString("MenuSaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Template,保存模板,保存模板.
        /// </summary>
        internal static string MenuSaveTemplate {
            get {
                return ResourceManager.GetString("MenuSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one BindingSource for easliyReport at Design Time.,請在設計時為簡易報表選擇一個BindingSource。,请在设计时为简易报表选择一个BindingSource。.
        /// </summary>
        internal static string MsgDataSourceNull {
            get {
                return ResourceManager.GetString("MsgDataSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Success !,刪除成功！,删除成功！.
        /// </summary>
        internal static string MsgDeleteSuccess {
            get {
                return ResourceManager.GetString("MsgDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error,錯誤,错误.
        /// </summary>
        internal static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not use &lt;Excel group&gt; in folded rows.,使用Excel群組功能的時候不能使用折列列印。,使用Excel分组功能的时候不能使用折列打印。.
        /// </summary>
        internal static string MsgExcelGroupNewLineError {
            get {
                return ResourceManager.GetString("MsgExcelGroupNewLineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting,輸出中...,输出中....
        /// </summary>
        internal static string MsgExporting {
            get {
                return ResourceManager.GetString("MsgExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Success !,輸出成功！,输出成功！.
        /// </summary>
        internal static string MsgExportSuccess {
            get {
                return ResourceManager.GetString("MsgExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select export columns.,請先選擇要輸出的欄位。,请先选择要输出的字段。.
        /// </summary>
        internal static string MsgFieldItemsNull {
            get {
                return ResourceManager.GetString("MsgFieldItemsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not be supported.,不支持此文件類型。,不支持此文件类型。.
        /// </summary>
        internal static string MsgFileTypeNotSupport {
            get {
                return ResourceManager.GetString("MsgFileTypeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &lt;Footer Item Type&gt;， then click &lt;Add&gt; button to add footer item.,請先選擇表尾項目類型，然後按【添加】按鈕添加表尾項目。,请先选择表尾项目类型，然后按【添加】按钮添加表尾项目。.
        /// </summary>
        internal static string MsgFooterItemAdd {
            get {
                return ResourceManager.GetString("MsgFooterItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set order for the column that you want to group by.,請先為要分組的欄位設置排序方式。,请先为要分组的字段设置排序方式。.
        /// </summary>
        internal static string MsgGroupColumnNotOrderBy {
            get {
                return ResourceManager.GetString("MsgGroupColumnNotOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Column is not be set.,群組欄位未設置。,群组字段未设置。.
        /// </summary>
        internal static string MsgGroupColumnsNotSetError {
            get {
                return ResourceManager.GetString("MsgGroupColumnsNotSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one HeaderBindingSource for easliyReport at Design Time.,請在設計時為簡易報表選擇一個HeaderBindingSource。,请在设计时为简易报表选择一个HeaderBindingSource。.
        /// </summary>
        internal static string MsgHeaderDataSourceNull {
            get {
                return ResourceManager.GetString("MsgHeaderDataSourceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select &lt;Header Item Type&gt;， then click &lt;Add&gt; button to add header item.,請先選擇表頭項目類型，然後按【添加】按鈕添加表頭項目。,请先选择表头项目类型，然后按【添加】按钮添加表头项目。.
        /// </summary>
        internal static string MsgHeaderItemAdd {
            get {
                return ResourceManager.GetString("MsgHeaderItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set images at first.,請先在設計時設置好圖片。,请先在设计时设置好图片。.
        /// </summary>
        internal static string MsgImageItemsNull {
            get {
                return ResourceManager.GetString("MsgImageItemsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.,無效的電子郵件地址格式,无效的电子邮件地址格式.
        /// </summary>
        internal static string MsgInvalidMailAddress {
            get {
                return ResourceManager.GetString("MsgInvalidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail From can not be empty !,寄件人地址不能為空 !,寄件人地址不能为空 !.
        /// </summary>
        internal static string MsgMailFromEmpty {
            get {
                return ResourceManager.GetString("MsgMailFromEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail To can not be empty !,收件人地址不能為空 !,收件人地址不能为空 !.
        /// </summary>
        internal static string MsgMailToEmpty {
            get {
                return ResourceManager.GetString("MsgMailToEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set parameters at first.,請先在設計時設置好參數,请先在设计时设置好参数.
        /// </summary>
        internal static string MsgParameterItemsNull {
            get {
                return ResourceManager.GetString("MsgParameterItemsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has not completed, \ndo you really want to abort it?,還未完成，您真的要中止嗎？,还未完成，您真的要中止吗？.
        /// </summary>
        internal static string MsgProcessAbortRequest {
            get {
                return ResourceManager.GetString("MsgProcessAbortRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Finished,完成,完成.
        /// </summary>
        internal static string MsgProcessFinished {
            get {
                return ResourceManager.GetString("MsgProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Start,開始,开始.
        /// </summary>
        internal static string MsgProcessStart {
            get {
                return ResourceManager.GetString("MsgProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select export columns.,請選擇想要輸出的欄位。,请选择想要输出的字段。.
        /// </summary>
        internal static string MsgReportDetails {
            get {
                return ResourceManager.GetString("MsgReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is used to set the format of report and output config.,此頁面用於設置報表的格式和輸出設定。,此页用于设定报表的格式和输出方式设置。.
        /// </summary>
        internal static string MsgReportSetting {
            get {
                return ResourceManager.GetString("MsgReportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success !,保存成功！,保存成功！.
        /// </summary>
        internal static string MsgSaveSuccess {
            get {
                return ResourceManager.GetString("MsgSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success,成功,成功.
        /// </summary>
        internal static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this template ?,您確定要刪除此模板嗎？,您确定要删除此模板吗？.
        /// </summary>
        internal static string MsgTemplateDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgTemplateDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template name which you input has already existed.,您所輸入的模板已經存在。,您所输入的模板已经存在。.
        /// </summary>
        internal static string MsgTemplateExist {
            get {
                return ResourceManager.GetString("MsgTemplateExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input template name， then retry.,請先輸入模板名，然後再試一次。,请先输入模板名，然后再试一次。.
        /// </summary>
        internal static string MsgTemplateFileNameIsNull {
            get {
                return ResourceManager.GetString("MsgTemplateFileNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning,警告,警告.
        /// </summary>
        internal static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,不排序,不排序.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex,頁次,页次.
        /// </summary>
        internal static string PageIndex {
            get {
                return ResourceManager.GetString("PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndexAndTotalPageCount,頁次和總頁次,页次和总页次.
        /// </summary>
        internal static string PageIndexAndTotalPageCount {
            get {
                return ResourceManager.GetString("PageIndexAndTotalPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterItem,參數,参数.
        /// </summary>
        internal static string ParameterItem {
            get {
                return ResourceManager.GetString("ParameterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QueryCondition,查詢條件,查询条件.
        /// </summary>
        internal static string QueryCondition {
            get {
                return ResourceManager.GetString("QueryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportDate,打印日期,打印日期.
        /// </summary>
        internal static string ReportDate {
            get {
                return ResourceManager.GetString("ReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportDateTime,打印日期時間,打印日期时间.
        /// </summary>
        internal static string ReportDateTime {
            get {
                return ResourceManager.GetString("ReportDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportID,報表代號,报表代号.
        /// </summary>
        internal static string ReportID {
            get {
                return ResourceManager.GetString("ReportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportName,報表名稱,报表名称.
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Properties,欄位屬性,字段属性.
        /// </summary>
        internal static string TabControlColumnProperties {
            get {
                return ResourceManager.GetString("TabControlColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns,欄位選擇,字段选择.
        /// </summary>
        internal static string TabControlColumns {
            get {
                return ResourceManager.GetString("TabControlColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Item Properties,表尾項目屬性,表尾项目属性.
        /// </summary>
        internal static string TabControlFooterItemProperties {
            get {
                return ResourceManager.GetString("TabControlFooterItemProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &amp; Total Setting,分組和匯總 設置,分组和汇总 设置.
        /// </summary>
        internal static string TabControlGroupColumnProperties {
            get {
                return ResourceManager.GetString("TabControlGroupColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group &amp; Total,分組和匯總,分组和汇总.
        /// </summary>
        internal static string TabControlGroupColumns {
            get {
                return ResourceManager.GetString("TabControlGroupColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Item Properties,表頭項目屬性,表头项目属性.
        /// </summary>
        internal static string TabControlHeaderItemProperties {
            get {
                return ResourceManager.GetString("TabControlHeaderItemProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Details,報表明細,报表明细.
        /// </summary>
        internal static string TabControlReportDetails {
            get {
                return ResourceManager.GetString("TabControlReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Footer,報表尾,报表尾.
        /// </summary>
        internal static string TabControlReportFooter {
            get {
                return ResourceManager.GetString("TabControlReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Header,報表頭,报表头.
        /// </summary>
        internal static string TabControlReportHeader {
            get {
                return ResourceManager.GetString("TabControlReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Setting,報表設定,报表设定.
        /// </summary>
        internal static string TabControlReportSetting {
            get {
                return ResourceManager.GetString("TabControlReportSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrialVersion only support 10 templates,很抱歉，試用版本最多只能存取10筆樣版資料,很抱歉，试用版本最多只能存取10笔样版资料.
        /// </summary>
        internal static string TrialMessage {
            get {
                return ResourceManager.GetString("TrialMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID,用戶代號,用户代号.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName,用戶名,用户名.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap view {
            get {
                object obj = ResourceManager.GetObject("view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
