namespace sRT312
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTFarEastCust = new Srvtools.InfoCommand(this.components);
            this.ucRTFarEastCust = new Srvtools.UpdateComponent(this.components);
            this.View_RTFarEastCust = new Srvtools.InfoCommand(this.components);
            this.RT312 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTFarEastCust)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTFarEastCust)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT312)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTFarEastCust
            // 
            this.RTFarEastCust.CacheConnection = false;
            this.RTFarEastCust.CommandText = "SELECT dbo.[RTFarEastCust].* FROM dbo.[RTFarEastCust]";
            this.RTFarEastCust.CommandTimeout = 30;
            this.RTFarEastCust.CommandType = System.Data.CommandType.Text;
            this.RTFarEastCust.DynamicTableName = false;
            this.RTFarEastCust.EEPAlias = null;
            this.RTFarEastCust.EncodingAfter = null;
            this.RTFarEastCust.EncodingBefore = "Windows-1252";
            this.RTFarEastCust.EncodingConvert = null;
            this.RTFarEastCust.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "LINEQ1";
            keyItem3.KeyName = "CUSID";
            this.RTFarEastCust.KeyFields.Add(keyItem1);
            this.RTFarEastCust.KeyFields.Add(keyItem2);
            this.RTFarEastCust.KeyFields.Add(keyItem3);
            this.RTFarEastCust.MultiSetWhere = false;
            this.RTFarEastCust.Name = "RTFarEastCust";
            this.RTFarEastCust.NotificationAutoEnlist = false;
            this.RTFarEastCust.SecExcept = null;
            this.RTFarEastCust.SecFieldName = null;
            this.RTFarEastCust.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTFarEastCust.SelectPaging = false;
            this.RTFarEastCust.SelectTop = 0;
            this.RTFarEastCust.SiteControl = false;
            this.RTFarEastCust.SiteFieldName = null;
            this.RTFarEastCust.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTFarEastCust
            // 
            this.ucRTFarEastCust.AutoTrans = true;
            this.ucRTFarEastCust.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "LINEQ1";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "CUSID";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "CUSNC";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "IDNUMBERTYPE";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "SOCIALID";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "SECONDIDTYPE";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "SECONDNO";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "CUTID2";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "TOWNSHIP2";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "RADDR2";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CUTID3";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "TOWNSHIP3";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "RADDR3";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "BIRTHDAY";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "CONTACTTEL";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "MOBILE";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "EMAIL";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "COBOSS";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "COBOSSID";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "COCONTACT";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "COCONTACTTEL";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "COCONTACTMOBILE";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CASEKIND";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "USERRATE";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PAYCYCLE";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "MEMBERID";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "FREECODE";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "IP11";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "MAC";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "PORT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "USERCABLE";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "COTOUT";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "COTIN";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "GTEQUIP";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "GTMONEY";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "GTVALID";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "GTSERIAL";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "GTPRTDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "GTPRTUSR";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "GTREPAYDAT";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "APPLYDAT";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "FINISHDAT";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "DOCKETDAT";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "ACTIVATEDAT";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "OVERDUEDAT";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "DROPDAT";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "CANCELDAT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "CANCELUSR";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "MEMO";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "UUSR";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "UDAT";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "STRBILLINGDAT";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "SETUPAMT";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "CUTID1";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "TOWNSHIP1";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "RADDR1";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr1);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr2);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr3);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr4);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr5);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr6);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr7);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr8);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr9);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr10);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr11);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr12);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr13);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr14);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr15);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr16);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr17);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr18);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr19);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr20);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr21);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr22);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr23);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr24);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr25);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr26);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr27);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr28);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr29);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr30);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr31);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr32);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr33);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr34);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr35);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr36);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr37);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr38);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr39);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr40);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr41);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr42);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr43);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr44);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr45);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr46);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr47);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr48);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr49);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr50);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr51);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr52);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr53);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr54);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr55);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr56);
            this.ucRTFarEastCust.FieldAttrs.Add(fieldAttr57);
            this.ucRTFarEastCust.LogInfo = null;
            this.ucRTFarEastCust.Name = "ucRTFarEastCust";
            this.ucRTFarEastCust.RowAffectsCheck = true;
            this.ucRTFarEastCust.SelectCmd = this.RTFarEastCust;
            this.ucRTFarEastCust.SelectCmdForUpdate = null;
            this.ucRTFarEastCust.SendSQLCmd = true;
            this.ucRTFarEastCust.ServerModify = true;
            this.ucRTFarEastCust.ServerModifyGetMax = false;
            this.ucRTFarEastCust.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTFarEastCust.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTFarEastCust.UseTranscationScope = false;
            this.ucRTFarEastCust.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTFarEastCust
            // 
            this.View_RTFarEastCust.CacheConnection = false;
            this.View_RTFarEastCust.CommandText = "SELECT * FROM dbo.[RTFarEastCust]";
            this.View_RTFarEastCust.CommandTimeout = 30;
            this.View_RTFarEastCust.CommandType = System.Data.CommandType.Text;
            this.View_RTFarEastCust.DynamicTableName = false;
            this.View_RTFarEastCust.EEPAlias = null;
            this.View_RTFarEastCust.EncodingAfter = null;
            this.View_RTFarEastCust.EncodingBefore = "Windows-1252";
            this.View_RTFarEastCust.EncodingConvert = null;
            this.View_RTFarEastCust.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "COMQ1";
            keyItem5.KeyName = "LINEQ1";
            keyItem6.KeyName = "CUSID";
            this.View_RTFarEastCust.KeyFields.Add(keyItem4);
            this.View_RTFarEastCust.KeyFields.Add(keyItem5);
            this.View_RTFarEastCust.KeyFields.Add(keyItem6);
            this.View_RTFarEastCust.MultiSetWhere = false;
            this.View_RTFarEastCust.Name = "View_RTFarEastCust";
            this.View_RTFarEastCust.NotificationAutoEnlist = false;
            this.View_RTFarEastCust.SecExcept = null;
            this.View_RTFarEastCust.SecFieldName = null;
            this.View_RTFarEastCust.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTFarEastCust.SelectPaging = false;
            this.View_RTFarEastCust.SelectTop = 0;
            this.View_RTFarEastCust.SiteControl = false;
            this.View_RTFarEastCust.SiteFieldName = null;
            this.View_RTFarEastCust.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT312
            // 
            this.RT312.CacheConnection = false;
            this.RT312.CommandText = "SELECT * FROM V_RT312";
            this.RT312.CommandTimeout = 30;
            this.RT312.CommandType = System.Data.CommandType.Text;
            this.RT312.DynamicTableName = false;
            this.RT312.EEPAlias = "RTLib";
            this.RT312.EncodingAfter = null;
            this.RT312.EncodingBefore = "Windows-1252";
            this.RT312.EncodingConvert = null;
            this.RT312.InfoConnection = this.InfoConnection1;
            this.RT312.MultiSetWhere = false;
            this.RT312.Name = "RT312";
            this.RT312.NotificationAutoEnlist = false;
            this.RT312.SecExcept = null;
            this.RT312.SecFieldName = null;
            this.RT312.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT312.SelectPaging = false;
            this.RT312.SelectTop = 0;
            this.RT312.SiteControl = false;
            this.RT312.SiteFieldName = null;
            this.RT312.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTFarEastCust)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTFarEastCust)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT312)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTFarEastCust;
        private Srvtools.UpdateComponent ucRTFarEastCust;
        private Srvtools.InfoCommand View_RTFarEastCust;
        private Srvtools.InfoCommand RT312;
    }
}
