namespace sRT1046
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem17 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem18 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem19 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.KeyItem keyItem20 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem21 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem22 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem23 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem24 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustAR = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustAR = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCustARClear = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustARClear = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCustARDTL = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustARDTL = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustAR = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCustARClear = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCustARDTL = new Srvtools.InfoCommand(this.components);
            this.cmdRT10461 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10462 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10463 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10464 = new Srvtools.InfoCommand(this.components);
            this.RT1046 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustAR)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustARClear)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustARDTL)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustAR)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustARClear)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustARDTL)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10461)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10462)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10463)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10464)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1046)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustAR
            // 
            this.RTLessorAVSCustAR.CacheConnection = false;
            this.RTLessorAVSCustAR.CommandText = "SELECT dbo.[RTLessorAVSCustAR].* FROM dbo.[RTLessorAVSCustAR]";
            this.RTLessorAVSCustAR.CommandTimeout = 30;
            this.RTLessorAVSCustAR.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustAR.DynamicTableName = false;
            this.RTLessorAVSCustAR.EEPAlias = null;
            this.RTLessorAVSCustAR.EncodingAfter = null;
            this.RTLessorAVSCustAR.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustAR.EncodingConvert = null;
            this.RTLessorAVSCustAR.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "BATCHNO";
            this.RTLessorAVSCustAR.KeyFields.Add(keyItem1);
            this.RTLessorAVSCustAR.KeyFields.Add(keyItem2);
            this.RTLessorAVSCustAR.MultiSetWhere = false;
            this.RTLessorAVSCustAR.Name = "RTLessorAVSCustAR";
            this.RTLessorAVSCustAR.NotificationAutoEnlist = false;
            this.RTLessorAVSCustAR.SecExcept = null;
            this.RTLessorAVSCustAR.SecFieldName = null;
            this.RTLessorAVSCustAR.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustAR.SelectPaging = false;
            this.RTLessorAVSCustAR.SelectTop = 0;
            this.RTLessorAVSCustAR.SiteControl = false;
            this.RTLessorAVSCustAR.SiteFieldName = null;
            this.RTLessorAVSCustAR.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustAR
            // 
            this.ucRTLessorAVSCustAR.AutoTrans = true;
            this.ucRTLessorAVSCustAR.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CUSID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "BATCHNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PERIOD";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "ARTYPE";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "AMT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "COD1";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "COD2";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "COD3";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "COD4";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "COD5";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CDAT";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "MDAT";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "MUSR";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "CANCELDAT";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "CANCELUSR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "CANCELMEMO";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "REALAMT";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCustAR.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCustAR.LogInfo = null;
            this.ucRTLessorAVSCustAR.Name = "ucRTLessorAVSCustAR";
            this.ucRTLessorAVSCustAR.RowAffectsCheck = true;
            this.ucRTLessorAVSCustAR.SelectCmd = this.RTLessorAVSCustAR;
            this.ucRTLessorAVSCustAR.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustAR.SendSQLCmd = true;
            this.ucRTLessorAVSCustAR.ServerModify = true;
            this.ucRTLessorAVSCustAR.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustAR.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustAR.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustAR.UseTranscationScope = false;
            this.ucRTLessorAVSCustAR.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCustARClear
            // 
            this.RTLessorAVSCustARClear.CacheConnection = false;
            this.RTLessorAVSCustARClear.CommandText = "SELECT dbo.[RTLessorAVSCustARClear].* FROM dbo.[RTLessorAVSCustARClear]";
            this.RTLessorAVSCustARClear.CommandTimeout = 30;
            this.RTLessorAVSCustARClear.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustARClear.DynamicTableName = false;
            this.RTLessorAVSCustARClear.EEPAlias = null;
            this.RTLessorAVSCustARClear.EncodingAfter = null;
            this.RTLessorAVSCustARClear.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustARClear.EncodingConvert = null;
            this.RTLessorAVSCustARClear.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "BATCHNO";
            keyItem5.KeyName = "SEQ";
            this.RTLessorAVSCustARClear.KeyFields.Add(keyItem3);
            this.RTLessorAVSCustARClear.KeyFields.Add(keyItem4);
            this.RTLessorAVSCustARClear.KeyFields.Add(keyItem5);
            this.RTLessorAVSCustARClear.MultiSetWhere = false;
            this.RTLessorAVSCustARClear.Name = "RTLessorAVSCustARClear";
            this.RTLessorAVSCustARClear.NotificationAutoEnlist = false;
            this.RTLessorAVSCustARClear.SecExcept = null;
            this.RTLessorAVSCustARClear.SecFieldName = null;
            this.RTLessorAVSCustARClear.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustARClear.SelectPaging = false;
            this.RTLessorAVSCustARClear.SelectTop = 0;
            this.RTLessorAVSCustARClear.SiteControl = false;
            this.RTLessorAVSCustARClear.SiteFieldName = null;
            this.RTLessorAVSCustARClear.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustARClear
            // 
            this.ucRTLessorAVSCustARClear.AutoTrans = true;
            this.ucRTLessorAVSCustARClear.ExceptJoin = false;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "CUSID";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "BATCHNO";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "SEQ";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "MDAT";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "REALAMT";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "MUSR";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "CANCELDAT";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "CANCELUSR";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCustARClear.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustARClear.LogInfo = null;
            this.ucRTLessorAVSCustARClear.Name = "ucRTLessorAVSCustARClear";
            this.ucRTLessorAVSCustARClear.RowAffectsCheck = true;
            this.ucRTLessorAVSCustARClear.SelectCmd = this.RTLessorAVSCustARClear;
            this.ucRTLessorAVSCustARClear.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustARClear.SendSQLCmd = true;
            this.ucRTLessorAVSCustARClear.ServerModify = true;
            this.ucRTLessorAVSCustARClear.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustARClear.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustARClear.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustARClear.UseTranscationScope = false;
            this.ucRTLessorAVSCustARClear.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCustARDTL
            // 
            this.RTLessorAVSCustARDTL.CacheConnection = false;
            this.RTLessorAVSCustARDTL.CommandText = "SELECT dbo.[RTLessorAVSCustARDTL].* FROM dbo.[RTLessorAVSCustARDTL]";
            this.RTLessorAVSCustARDTL.CommandTimeout = 30;
            this.RTLessorAVSCustARDTL.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustARDTL.DynamicTableName = false;
            this.RTLessorAVSCustARDTL.EEPAlias = null;
            this.RTLessorAVSCustARDTL.EncodingAfter = null;
            this.RTLessorAVSCustARDTL.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustARDTL.EncodingConvert = null;
            this.RTLessorAVSCustARDTL.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "CUSID";
            keyItem7.KeyName = "BATCHNO";
            keyItem8.KeyName = "SEQ";
            this.RTLessorAVSCustARDTL.KeyFields.Add(keyItem6);
            this.RTLessorAVSCustARDTL.KeyFields.Add(keyItem7);
            this.RTLessorAVSCustARDTL.KeyFields.Add(keyItem8);
            this.RTLessorAVSCustARDTL.MultiSetWhere = false;
            this.RTLessorAVSCustARDTL.Name = "RTLessorAVSCustARDTL";
            this.RTLessorAVSCustARDTL.NotificationAutoEnlist = false;
            this.RTLessorAVSCustARDTL.SecExcept = null;
            this.RTLessorAVSCustARDTL.SecFieldName = null;
            this.RTLessorAVSCustARDTL.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustARDTL.SelectPaging = false;
            this.RTLessorAVSCustARDTL.SelectTop = 0;
            this.RTLessorAVSCustARDTL.SiteControl = false;
            this.RTLessorAVSCustARDTL.SiteFieldName = null;
            this.RTLessorAVSCustARDTL.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustARDTL
            // 
            this.ucRTLessorAVSCustARDTL.AutoTrans = true;
            this.ucRTLessorAVSCustARDTL.ExceptJoin = false;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "CUSID";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "BATCHNO";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "SEQ";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "SYY";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "SMM";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "TYY";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "TMM";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "ITEMNC";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "PORM";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "AMT";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "REALAMT";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "CDAT";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "MDAT";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "CANCELDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "CANCELMEMO";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "CANCELUSR";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "L14";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "L23";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCustARDTL.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCustARDTL.LogInfo = null;
            this.ucRTLessorAVSCustARDTL.Name = "ucRTLessorAVSCustARDTL";
            this.ucRTLessorAVSCustARDTL.RowAffectsCheck = true;
            this.ucRTLessorAVSCustARDTL.SelectCmd = this.RTLessorAVSCustARDTL;
            this.ucRTLessorAVSCustARDTL.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustARDTL.SendSQLCmd = true;
            this.ucRTLessorAVSCustARDTL.ServerModify = true;
            this.ucRTLessorAVSCustARDTL.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustARDTL.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustARDTL.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustARDTL.UseTranscationScope = false;
            this.ucRTLessorAVSCustARDTL.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustAR
            // 
            this.View_RTLessorAVSCustAR.CacheConnection = false;
            this.View_RTLessorAVSCustAR.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustAR]";
            this.View_RTLessorAVSCustAR.CommandTimeout = 30;
            this.View_RTLessorAVSCustAR.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustAR.DynamicTableName = false;
            this.View_RTLessorAVSCustAR.EEPAlias = null;
            this.View_RTLessorAVSCustAR.EncodingAfter = null;
            this.View_RTLessorAVSCustAR.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustAR.EncodingConvert = null;
            this.View_RTLessorAVSCustAR.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "CUSID";
            keyItem10.KeyName = "BATCHNO";
            this.View_RTLessorAVSCustAR.KeyFields.Add(keyItem9);
            this.View_RTLessorAVSCustAR.KeyFields.Add(keyItem10);
            this.View_RTLessorAVSCustAR.MultiSetWhere = false;
            this.View_RTLessorAVSCustAR.Name = "View_RTLessorAVSCustAR";
            this.View_RTLessorAVSCustAR.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustAR.SecExcept = null;
            this.View_RTLessorAVSCustAR.SecFieldName = null;
            this.View_RTLessorAVSCustAR.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustAR.SelectPaging = false;
            this.View_RTLessorAVSCustAR.SelectTop = 0;
            this.View_RTLessorAVSCustAR.SiteControl = false;
            this.View_RTLessorAVSCustAR.SiteFieldName = null;
            this.View_RTLessorAVSCustAR.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCustARClear
            // 
            this.View_RTLessorAVSCustARClear.CacheConnection = false;
            this.View_RTLessorAVSCustARClear.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustARClear]";
            this.View_RTLessorAVSCustARClear.CommandTimeout = 30;
            this.View_RTLessorAVSCustARClear.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustARClear.DynamicTableName = false;
            this.View_RTLessorAVSCustARClear.EEPAlias = null;
            this.View_RTLessorAVSCustARClear.EncodingAfter = null;
            this.View_RTLessorAVSCustARClear.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustARClear.EncodingConvert = null;
            this.View_RTLessorAVSCustARClear.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "CUSID";
            keyItem12.KeyName = "BATCHNO";
            keyItem13.KeyName = "SEQ";
            this.View_RTLessorAVSCustARClear.KeyFields.Add(keyItem11);
            this.View_RTLessorAVSCustARClear.KeyFields.Add(keyItem12);
            this.View_RTLessorAVSCustARClear.KeyFields.Add(keyItem13);
            this.View_RTLessorAVSCustARClear.MultiSetWhere = false;
            this.View_RTLessorAVSCustARClear.Name = "View_RTLessorAVSCustARClear";
            this.View_RTLessorAVSCustARClear.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustARClear.SecExcept = null;
            this.View_RTLessorAVSCustARClear.SecFieldName = null;
            this.View_RTLessorAVSCustARClear.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustARClear.SelectPaging = false;
            this.View_RTLessorAVSCustARClear.SelectTop = 0;
            this.View_RTLessorAVSCustARClear.SiteControl = false;
            this.View_RTLessorAVSCustARClear.SiteFieldName = null;
            this.View_RTLessorAVSCustARClear.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCustARDTL
            // 
            this.View_RTLessorAVSCustARDTL.CacheConnection = false;
            this.View_RTLessorAVSCustARDTL.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustARDTL]";
            this.View_RTLessorAVSCustARDTL.CommandTimeout = 30;
            this.View_RTLessorAVSCustARDTL.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustARDTL.DynamicTableName = false;
            this.View_RTLessorAVSCustARDTL.EEPAlias = null;
            this.View_RTLessorAVSCustARDTL.EncodingAfter = null;
            this.View_RTLessorAVSCustARDTL.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustARDTL.EncodingConvert = null;
            this.View_RTLessorAVSCustARDTL.InfoConnection = this.InfoConnection1;
            keyItem14.KeyName = "CUSID";
            keyItem15.KeyName = "BATCHNO";
            keyItem16.KeyName = "SEQ";
            this.View_RTLessorAVSCustARDTL.KeyFields.Add(keyItem14);
            this.View_RTLessorAVSCustARDTL.KeyFields.Add(keyItem15);
            this.View_RTLessorAVSCustARDTL.KeyFields.Add(keyItem16);
            this.View_RTLessorAVSCustARDTL.MultiSetWhere = false;
            this.View_RTLessorAVSCustARDTL.Name = "View_RTLessorAVSCustARDTL";
            this.View_RTLessorAVSCustARDTL.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustARDTL.SecExcept = null;
            this.View_RTLessorAVSCustARDTL.SecFieldName = null;
            this.View_RTLessorAVSCustARDTL.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustARDTL.SelectPaging = false;
            this.View_RTLessorAVSCustARDTL.SelectTop = 0;
            this.View_RTLessorAVSCustARDTL.SiteControl = false;
            this.View_RTLessorAVSCustARDTL.SiteFieldName = null;
            this.View_RTLessorAVSCustARDTL.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10461
            // 
            this.cmdRT10461.CacheConnection = false;
            this.cmdRT10461.CommandText = "usp_RTLessorAVSCustARClearExe";
            this.cmdRT10461.CommandTimeout = 30;
            this.cmdRT10461.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10461.DynamicTableName = false;
            this.cmdRT10461.EEPAlias = null;
            this.cmdRT10461.EncodingAfter = null;
            this.cmdRT10461.EncodingBefore = "Windows-1252";
            this.cmdRT10461.EncodingConvert = null;
            this.cmdRT10461.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter1.ParameterName = "cusid";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 15;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter2.ParameterName = "batchno";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 12;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter3.ParameterName = "realamtx";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 0;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "usr";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 6;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10461.InfoParameters.Add(infoParameter1);
            this.cmdRT10461.InfoParameters.Add(infoParameter2);
            this.cmdRT10461.InfoParameters.Add(infoParameter3);
            this.cmdRT10461.InfoParameters.Add(infoParameter4);
            this.cmdRT10461.MultiSetWhere = false;
            this.cmdRT10461.Name = "cmdRT10461";
            this.cmdRT10461.NotificationAutoEnlist = false;
            this.cmdRT10461.SecExcept = null;
            this.cmdRT10461.SecFieldName = null;
            this.cmdRT10461.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10461.SelectPaging = false;
            this.cmdRT10461.SelectTop = 0;
            this.cmdRT10461.SiteControl = false;
            this.cmdRT10461.SiteFieldName = null;
            this.cmdRT10461.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10462
            // 
            this.cmdRT10462.CacheConnection = false;
            this.cmdRT10462.CommandText = resources.GetString("cmdRT10462.CommandText");
            this.cmdRT10462.CommandTimeout = 30;
            this.cmdRT10462.CommandType = System.Data.CommandType.Text;
            this.cmdRT10462.DynamicTableName = false;
            this.cmdRT10462.EEPAlias = null;
            this.cmdRT10462.EncodingAfter = null;
            this.cmdRT10462.EncodingBefore = "Windows-1252";
            this.cmdRT10462.EncodingConvert = null;
            this.cmdRT10462.InfoConnection = this.InfoConnection1;
            keyItem17.KeyName = "CUSID";
            keyItem18.KeyName = "BATCHNO";
            keyItem19.KeyName = "SEQ";
            this.cmdRT10462.KeyFields.Add(keyItem17);
            this.cmdRT10462.KeyFields.Add(keyItem18);
            this.cmdRT10462.KeyFields.Add(keyItem19);
            this.cmdRT10462.MultiSetWhere = false;
            this.cmdRT10462.Name = "cmdRT10462";
            this.cmdRT10462.NotificationAutoEnlist = false;
            this.cmdRT10462.SecExcept = null;
            this.cmdRT10462.SecFieldName = null;
            this.cmdRT10462.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10462.SelectPaging = false;
            this.cmdRT10462.SelectTop = 0;
            this.cmdRT10462.SiteControl = false;
            this.cmdRT10462.SiteFieldName = null;
            this.cmdRT10462.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10463
            // 
            this.cmdRT10463.CacheConnection = false;
            this.cmdRT10463.CommandText = "usp_RTLessorAVSCustARClearRTN";
            this.cmdRT10463.CommandTimeout = 30;
            this.cmdRT10463.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10463.DynamicTableName = false;
            this.cmdRT10463.EEPAlias = null;
            this.cmdRT10463.EncodingAfter = null;
            this.cmdRT10463.EncodingBefore = "Windows-1252";
            this.cmdRT10463.EncodingConvert = null;
            this.cmdRT10463.InfoConnection = this.InfoConnection1;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "cusid";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 15;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter6.ParameterName = "batchno";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 12;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter7.ParameterName = "seq";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 0;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "usr";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 6;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10463.InfoParameters.Add(infoParameter5);
            this.cmdRT10463.InfoParameters.Add(infoParameter6);
            this.cmdRT10463.InfoParameters.Add(infoParameter7);
            this.cmdRT10463.InfoParameters.Add(infoParameter8);
            this.cmdRT10463.MultiSetWhere = false;
            this.cmdRT10463.Name = "cmdRT10463";
            this.cmdRT10463.NotificationAutoEnlist = false;
            this.cmdRT10463.SecExcept = null;
            this.cmdRT10463.SecFieldName = null;
            this.cmdRT10463.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10463.SelectPaging = false;
            this.cmdRT10463.SelectTop = 0;
            this.cmdRT10463.SiteControl = false;
            this.cmdRT10463.SiteFieldName = null;
            this.cmdRT10463.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10464
            // 
            this.cmdRT10464.CacheConnection = false;
            this.cmdRT10464.CommandText = resources.GetString("cmdRT10464.CommandText");
            this.cmdRT10464.CommandTimeout = 30;
            this.cmdRT10464.CommandType = System.Data.CommandType.Text;
            this.cmdRT10464.DynamicTableName = false;
            this.cmdRT10464.EEPAlias = null;
            this.cmdRT10464.EncodingAfter = null;
            this.cmdRT10464.EncodingBefore = "Windows-1252";
            this.cmdRT10464.EncodingConvert = null;
            this.cmdRT10464.InfoConnection = this.InfoConnection1;
            keyItem20.KeyName = "CUSID";
            keyItem21.KeyName = "BATCHNO";
            keyItem22.KeyName = "SEQ";
            this.cmdRT10464.KeyFields.Add(keyItem20);
            this.cmdRT10464.KeyFields.Add(keyItem21);
            this.cmdRT10464.KeyFields.Add(keyItem22);
            this.cmdRT10464.MultiSetWhere = false;
            this.cmdRT10464.Name = "cmdRT10464";
            this.cmdRT10464.NotificationAutoEnlist = false;
            this.cmdRT10464.SecExcept = null;
            this.cmdRT10464.SecFieldName = null;
            this.cmdRT10464.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10464.SelectPaging = false;
            this.cmdRT10464.SelectTop = 0;
            this.cmdRT10464.SiteControl = false;
            this.cmdRT10464.SiteFieldName = null;
            this.cmdRT10464.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT1046
            // 
            this.RT1046.CacheConnection = false;
            this.RT1046.CommandText = resources.GetString("RT1046.CommandText");
            this.RT1046.CommandTimeout = 30;
            this.RT1046.CommandType = System.Data.CommandType.Text;
            this.RT1046.DynamicTableName = false;
            this.RT1046.EEPAlias = null;
            this.RT1046.EncodingAfter = null;
            this.RT1046.EncodingBefore = "Windows-1252";
            this.RT1046.EncodingConvert = null;
            this.RT1046.InfoConnection = this.InfoConnection1;
            keyItem23.KeyName = "CUSID";
            keyItem24.KeyName = "BATCHNO";
            this.RT1046.KeyFields.Add(keyItem23);
            this.RT1046.KeyFields.Add(keyItem24);
            this.RT1046.MultiSetWhere = false;
            this.RT1046.Name = "RT1046";
            this.RT1046.NotificationAutoEnlist = false;
            this.RT1046.SecExcept = null;
            this.RT1046.SecFieldName = null;
            this.RT1046.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT1046.SelectPaging = false;
            this.RT1046.SelectTop = 0;
            this.RT1046.SiteControl = false;
            this.RT1046.SiteFieldName = null;
            this.RT1046.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustAR)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustARClear)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustARDTL)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustAR)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustARClear)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustARDTL)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10461)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10462)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10463)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10464)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1046)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustAR;
        private Srvtools.UpdateComponent ucRTLessorAVSCustAR;
        private Srvtools.InfoCommand RTLessorAVSCustARClear;
        private Srvtools.UpdateComponent ucRTLessorAVSCustARClear;
        private Srvtools.InfoCommand RTLessorAVSCustARDTL;
        private Srvtools.UpdateComponent ucRTLessorAVSCustARDTL;
        private Srvtools.InfoCommand View_RTLessorAVSCustAR;
        private Srvtools.InfoCommand View_RTLessorAVSCustARClear;
        private Srvtools.InfoCommand View_RTLessorAVSCustARDTL;
        private Srvtools.InfoCommand cmdRT10461;
        private Srvtools.InfoCommand cmdRT10462;
        private Srvtools.InfoCommand cmdRT10463;
        private Srvtools.InfoCommand cmdRT10464;
        private Srvtools.InfoCommand RT1046;
    }
}
