Drop VIEW V_RT204 

CREATE VIEW V_RT204 AS 
SELECT * FROM (
SELECT  A.CUSID, A.BATCHNO, RTLessorAVSCmtyH.COMQ1, RTLessorAVSCmtyH.COMN,B.CUSNC,RTCode.CODENC, A.PERIOD,A.AMT,A.REALAMT,
A.AMT - A.REALAMT AS DIFFAMT, A.MDAT, RTObj_1.CUSNC AS MUSR,
A.COD1, case when A.COD2 like '超商%' then A.COD2 when A.COD2 like '退租%' then A.COD2 when A.COD2 like '信用卡%' then A.COD2 else A.COD2 end as COD2, 
A.COD3, A.CDAT, A.CANCELDAT, RTObj_2.CUSNC AS CANCELUSR, A.CANCELMEMO, B.Dropdat
FROM RTLessorAVSCmtyH RIGHT OUTER JOIN RTLessorAVSCust B ON RTLessorAVSCmtyH.COMQ1 = B.COMQ1 
RIGHT OUTER JOIN RTEmployee RTEmployee_2 INNER JOIN RTObj RTObj_2 ON RTEmployee_2.CUSID = 
RTObj_2.CUSID RIGHT OUTER JOIN RTLessorAVSCustAR A ON RTEmployee_2.EMPLY = A.CANCELUSR 
LEFT OUTER JOIN RTEmployee C INNER JOIN RTObj RTObj_1 ON C.CUSID = RTObj_1.CUSID ON A.MUSR = C.EMPLY 
LEFT OUTER JOIN RTCode ON A.ARTYPE = RTCode.CODE AND RTCode.KIND = 'N2' ON B.CUSID = A.CUSID 
WHERE 1=1) A
