<!-- #include virtual="/WebUtilityV4EBT/DBAUDI/zzKeyList.inc" -->
<!-- #include virtual="/webap/include/accesspermit.inc" -->
<!-- #include virtual="/Webap/include/RTGetUserLevel.inc" -->
<!-- #include virtual="/Webap/include/RTGetUserEmply.inc" -->
<%
Sub SrEnvironment()
  company="元訊寬頻網路股份有限公司"
  system="KTS管理系統"
  title="KTS用戶資料拉單作業"
  buttonName=" 新增 ; 刪除 ; 結束 ;重新整理;頁數;功能選項"
  V=split(SrAccessPermit,";")
  AllowA=V(0):AllowU=V(1):AllowD=V(2):AllowP=V(3)
  ButtonEnable="N;N;Y;Y;Y;Y"  
  'buttonEnable="Y;Y;Y;Y;Y;Y"
  functionOptName="電話明細; 拉  單 "
  functionOptProgram="KTSCUSTPULLtK.asp;KTSCUSTPULL.asp"
  functionOptPrompt="N;Y"
'  If V(1)="Y" then
'     accessMode="U"
'  Else
     accessMode="I"
'  End IF
  DSN="DSN=RTLib"
  formatName="用戶代號;用戶名稱;none;裝機地址;用戶申請日;送件申請日;裝機完工日;報竣日;合約起算日;作廢日;退租日;大盤;小盤;申請<BR>電話數;開通<BR>電話數;拉單日"
  sqlDelete="SELECT KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID,RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3 AS ADDR, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END, " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL THEN 1 ELSE 0 END), " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND KTSWANTGOCUSTD1.APPLYDAT IS NOT NULL THEN 1 ELSE 0 END), " _
           &"KTSWANTGOCUST.cbbnpulldat " _
           &"FROM KTSWANTGOCUSTD1 RIGHT OUTER JOIN KTSWANTGOCUST ON KTSWANTGOCUSTD1.CUSID = KTSWANTGOCUST.CUSID AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND " _
           &"KTSWANTGOCUSTD1.CANCELDAT IS NULL LEFT OUTER JOIN RTObj RTObj_2 INNER JOIN RTEmployee ON RTObj_2.CUSID = RTEmployee.CUSID ON " _
           &"KTSWANTGOCUST.EMPLY = RTEmployee.EMPLY LEFT OUTER JOIN RTObj RTObj_1 ON KTSWANTGOCUST.CONSIGNEE2 = RTObj_1.CUSID LEFT OUTER JOIN " _
           &"RTObj RTObj_3 ON KTSWANTGOCUST.CONSIGNEE1 = RTObj_3.CUSID LEFT OUTER JOIN RTCounty ON KTSWANTGOCUST.CUTID3 = RTCounty.CUTID " _
           &"GROUP BY  KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID, RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END,KTSWANTGOCUST.cbbnpulldat "

  dataTable="ktsWANTGOcust"
  userDefineDelete="Yes"
  numberOfKey=1
  dataProg="KTSCUSTPULLD.asp"
  datawindowFeature=""
  searchWindowFeature="width=640,height=460,scrollbars=yes"
  optionWindowFeature=""
  detailWindowFeature=""
  diaWidth=""
  diaHeight=""
  diaTitle="下列資料將被刪除，請按確認刪除之，或按取消。"
  diaButtonName=" 確認刪除 ; 取消 "
  goodMorning=TRUE
  goodMorningImage="cbbn.jpg"
  colSplit=1
  keyListPageSize=25
  searchProg="KTSCUSTPULLS.ASP"
  '----
  searchFirst=FALSE
  If searchQry="" Then
     searchQry=" KTSWANTGOCUST.CUSID<>'' AND KTSWANTGOCUST.CANCELDAT IS NULL AND KTSWANTGOCUST.CBBNPULLDAT IS NULL "
     searchShow="全部未拉單用戶(不含作廢)"
  ELSE
     SEARCHFIRST=FALSE
  End If
  userlevel=FrGetUserlevel(Request.ServerVariables("LOGON_USER"))
  Emply=FrGetUserEmply(Request.ServerVariables("LOGON_USER"))  
  'Response.Write "user=" & Request.ServerVariables("LOGON_USER")
  '讀取登入帳號之群組資料
  'Response.Write "GP=" & usergroup
  '-------------------------------------------------------------------------------------------
  'userlevel=2:為業務工程師==>只能看所屬社區資料
  'DOMAIN:'T','C','K'北中南轄區人員(客服,技術)只能看所屬轄區資料
 ' Response.Write "DOMAIN=" & domain & "<BR>"
  Domain=Mid(Emply,1,1)
  select case Domain
         case "T"
            DAreaID="='A1'"
         case "P"
            DAreaID="='A1'"                        
         case "C"
            DAreaID="='A2'"         
         case "K"
            DAreaID="='A3'"         
         case else
            DareaID="=''"
  end select
  '高階主管可讀取全部資料
  if UCASE(emply)="T89001" or Ucase(emply)="T89002" or  Ucase(emply)="T89020" or Ucase(emply)="T89018" or Ucase(emply)="T90076" OR _
     Ucase(emply)="T89003" or Ucase(emply)="T89005" or Ucase(emply)="T89025" or Ucase(emply)="T89076"then
     DAreaID="<>'*'"
  end if
  '資訊部管理員可讀取全部資料
  'if userlevel=31 then DAreaID="<>'*'"
  
  '由於分公司搬家尚未申請到線路，故客服先開放所有區域權限，一律讓台北客服處理
  if userlevel=31 or userlevel =1  or userlevel =5 then DAreaID="<>'*'"
  
    If searchShow="全部" Then
         sqlList="SELECT KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID,RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3 AS ADDR, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END, " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND KTSWANTGOCUSTD1.APPLYDAT IS NOT NULL THEN 1 ELSE 0 END), " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND KTSWANTGOCUSTD1.OPENDAT IS NOT NULL THEN 1 ELSE 0 END), " _
           &"KTSWANTGOCUST.cbbnpulldat " _
           &"FROM KTSWANTGOCUSTD1 RIGHT OUTER JOIN KTSWANTGOCUST ON KTSWANTGOCUSTD1.CUSID = KTSWANTGOCUST.CUSID AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND " _
           &"KTSWANTGOCUSTD1.CANCELDAT IS NULL LEFT OUTER JOIN RTObj RTObj_2 INNER JOIN RTEmployee ON RTObj_2.CUSID = RTEmployee.CUSID ON " _
           &"KTSWANTGOCUST.EMPLY = RTEmployee.EMPLY LEFT OUTER JOIN RTObj RTObj_1 ON KTSWANTGOCUST.CONSIGNEE2 = RTObj_1.CUSID LEFT OUTER JOIN " _
           &"RTObj RTObj_3 ON KTSWANTGOCUST.CONSIGNEE1 = RTObj_3.CUSID LEFT OUTER JOIN RTCounty ON KTSWANTGOCUST.CUTID3 = RTCounty.CUTID " _
           &"where " & searchqry & " " _
           &"GROUP BY  KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID, RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END,KTSWANTGOCUST.cbbnpulldat " 
    Else
         sqlList="SELECT KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID,RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3 AS ADDR, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END, " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND KTSWANTGOCUSTD1.APPLYDAT IS NOT NULL THEN 1 ELSE 0 END), " _
           &"SUM(CASE WHEN KTSWANTGOCUSTD1.CUSID IS NOT NULL AND KTSWANTGOCUSTD1.CANCELDAT IS NULL AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND KTSWANTGOCUSTD1.OPENDAT IS NOT NULL THEN 1 ELSE 0 END), " _
           &"KTSWANTGOCUST.cbbnpulldat " _
           &"FROM KTSWANTGOCUSTD1 RIGHT OUTER JOIN KTSWANTGOCUST ON KTSWANTGOCUSTD1.CUSID = KTSWANTGOCUST.CUSID AND KTSWANTGOCUSTD1.DROPDAT IS NULL AND " _
           &"KTSWANTGOCUSTD1.CANCELDAT IS NULL LEFT OUTER JOIN RTObj RTObj_2 INNER JOIN RTEmployee ON RTObj_2.CUSID = RTEmployee.CUSID ON " _
           &"KTSWANTGOCUST.EMPLY = RTEmployee.EMPLY LEFT OUTER JOIN RTObj RTObj_1 ON KTSWANTGOCUST.CONSIGNEE2 = RTObj_1.CUSID LEFT OUTER JOIN " _
           &"RTObj RTObj_3 ON KTSWANTGOCUST.CONSIGNEE1 = RTObj_3.CUSID LEFT OUTER JOIN RTCounty ON KTSWANTGOCUST.CUTID3 = RTCounty.CUTID " _
           &"where " & searchqry & " " _
           &"GROUP BY  KTSWANTGOCUST.CUSID, KTSWANTGOCUST.CUSNC, KTSWANTGOCUST.SOCIALID, RTCounty.CUTNC + KTSWANTGOCUST.TOWNSHIP3 + KTSWANTGOCUST.RADDR3, " _
           &"KTSWANTGOCUST.APFORMAPPLYDAT, KTSWANTGOCUST.APPLYDAT, KTSWANTGOCUST.FINISHDAT, KTSWANTGOCUST.DOCKETDAT, KTSWANTGOCUST.CONTRACTSTRDAT, KTSWANTGOCUST.CANCELDAT, " _
           &"KTSWANTGOCUST.DROPDAT, RTObj_3.SHORTNC, CASE WHEN RTObj_1.SHORTNC IS NULL OR RTObj_1.SHORTNC = '' THEN RTObj_2.CUSNC ELSE RTObj_1.SHORTNC END,KTSWANTGOCUST.cbbnpulldat " 
          
    End If  
  'Response.Write "SQL=" & SQLlist
End Sub
Sub SrRunUserDefineDelete()

End Sub
%>