namespace sRT1043
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr75 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr76 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr77 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr78 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr79 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr80 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr81 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr82 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr83 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr84 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr85 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr86 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr87 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr88 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr89 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr90 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr91 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr92 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr93 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem17 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem18 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem19 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem20 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem21 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem22 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter17 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter18 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter19 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter20 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter21 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter22 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter23 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter24 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter25 = new Srvtools.InfoParameter();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustCont = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustCont = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCustContHardware = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustContHardware = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCustContSndwork = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustContSndwork = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustCont = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCustContHardware = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCustContSndwork = new Srvtools.InfoCommand(this.components);
            this.RT10431 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10431 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10432 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10433 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10435 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10434 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustCont)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustContHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustContSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustCont)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustContHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustContSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10431)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10431)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10432)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10433)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10435)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10434)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT10431";
            service1.NonLogin = false;
            service1.ServiceName = "smRT10431";
            service2.DelegateName = "smRT10432";
            service2.NonLogin = false;
            service2.ServiceName = "smRT10432";
            service3.DelegateName = "smRT10433";
            service3.NonLogin = false;
            service3.ServiceName = "smRT10433";
            service4.DelegateName = "smRT10434";
            service4.NonLogin = false;
            service4.ServiceName = "smRT10434";
            service5.DelegateName = "smRT10435";
            service5.NonLogin = false;
            service5.ServiceName = "smRT10435";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustCont
            // 
            this.RTLessorAVSCustCont.CacheConnection = false;
            this.RTLessorAVSCustCont.CommandText = "SELECT dbo.[RTLessorAVSCustCont].* FROM dbo.[RTLessorAVSCustCont]";
            this.RTLessorAVSCustCont.CommandTimeout = 30;
            this.RTLessorAVSCustCont.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustCont.DynamicTableName = false;
            this.RTLessorAVSCustCont.EEPAlias = null;
            this.RTLessorAVSCustCont.EncodingAfter = null;
            this.RTLessorAVSCustCont.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustCont.EncodingConvert = null;
            this.RTLessorAVSCustCont.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "ENTRYNO";
            this.RTLessorAVSCustCont.KeyFields.Add(keyItem1);
            this.RTLessorAVSCustCont.KeyFields.Add(keyItem2);
            this.RTLessorAVSCustCont.MultiSetWhere = false;
            this.RTLessorAVSCustCont.Name = "RTLessorAVSCustCont";
            this.RTLessorAVSCustCont.NotificationAutoEnlist = false;
            this.RTLessorAVSCustCont.SecExcept = null;
            this.RTLessorAVSCustCont.SecFieldName = null;
            this.RTLessorAVSCustCont.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustCont.SelectPaging = false;
            this.RTLessorAVSCustCont.SelectTop = 0;
            this.RTLessorAVSCustCont.SiteControl = false;
            this.RTLessorAVSCustCont.SiteFieldName = null;
            this.RTLessorAVSCustCont.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustCont
            // 
            this.ucRTLessorAVSCustCont.AutoTrans = true;
            this.ucRTLessorAVSCustCont.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CUSID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ENTRYNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "APPLYDAT";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "PAYCYCLE";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "PERIOD";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "SECONDCASE";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "AMT";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "PAYTYPE";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "CREDITCARDTYPE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "CREDITBANK";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CREDITCARDNO";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CREDITNAME";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CREDITDUEM";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "CREDITDUEY";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "REALAMT";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "TARDAT";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "BATCHNO";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "TUSR";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "FINISHDAT";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "CANCELDAT";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "CANCELUSR";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "MEMO";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "EDAT";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "EUSR";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "UDAT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "UUSR";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ADJUSTDAY";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "STRBILLINGDAT";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "MAXENTRYNO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CASEKIND";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "RCVMONEYDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "CSNOTICEID";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCustCont.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCustCont.LogInfo = null;
            this.ucRTLessorAVSCustCont.Name = "ucRTLessorAVSCustCont";
            this.ucRTLessorAVSCustCont.RowAffectsCheck = true;
            this.ucRTLessorAVSCustCont.SelectCmd = this.RTLessorAVSCustCont;
            this.ucRTLessorAVSCustCont.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustCont.SendSQLCmd = true;
            this.ucRTLessorAVSCustCont.ServerModify = true;
            this.ucRTLessorAVSCustCont.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustCont.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustCont.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustCont.UseTranscationScope = false;
            this.ucRTLessorAVSCustCont.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCustContHardware
            // 
            this.RTLessorAVSCustContHardware.CacheConnection = false;
            this.RTLessorAVSCustContHardware.CommandText = "SELECT dbo.[RTLessorAVSCustContHardware].* FROM dbo.[RTLessorAVSCustContHardware]" +
    "";
            this.RTLessorAVSCustContHardware.CommandTimeout = 30;
            this.RTLessorAVSCustContHardware.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustContHardware.DynamicTableName = false;
            this.RTLessorAVSCustContHardware.EEPAlias = null;
            this.RTLessorAVSCustContHardware.EncodingAfter = null;
            this.RTLessorAVSCustContHardware.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustContHardware.EncodingConvert = null;
            this.RTLessorAVSCustContHardware.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "ENTRYNO";
            keyItem5.KeyName = "PRTNO";
            keyItem6.KeyName = "SEQ";
            this.RTLessorAVSCustContHardware.KeyFields.Add(keyItem3);
            this.RTLessorAVSCustContHardware.KeyFields.Add(keyItem4);
            this.RTLessorAVSCustContHardware.KeyFields.Add(keyItem5);
            this.RTLessorAVSCustContHardware.KeyFields.Add(keyItem6);
            this.RTLessorAVSCustContHardware.MultiSetWhere = false;
            this.RTLessorAVSCustContHardware.Name = "RTLessorAVSCustContHardware";
            this.RTLessorAVSCustContHardware.NotificationAutoEnlist = false;
            this.RTLessorAVSCustContHardware.SecExcept = null;
            this.RTLessorAVSCustContHardware.SecFieldName = null;
            this.RTLessorAVSCustContHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustContHardware.SelectPaging = false;
            this.RTLessorAVSCustContHardware.SelectTop = 0;
            this.RTLessorAVSCustContHardware.SiteControl = false;
            this.RTLessorAVSCustContHardware.SiteFieldName = null;
            this.RTLessorAVSCustContHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustContHardware
            // 
            this.ucRTLessorAVSCustContHardware.AutoTrans = true;
            this.ucRTLessorAVSCustContHardware.ExceptJoin = false;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "CUSID";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "ENTRYNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "PRTNO";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "SEQ";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "PRODNO";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "ITEMNO";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "QTY";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "DROPDAT";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "DROPREASON";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "WAREHOUSE";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "ASSETNO";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "DROPUSR";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "UNIT";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "AMT";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "EUSR";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "EDAT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "UUSR";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "UDAT";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "MEMO";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "BATCHNO";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "TARDAT";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "TUSR";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "RCVPRTNO";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "RCVDAT";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "RCVFINISHDAT";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr49);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr50);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr51);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr52);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr53);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr54);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr55);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr56);
            this.ucRTLessorAVSCustContHardware.FieldAttrs.Add(fieldAttr57);
            this.ucRTLessorAVSCustContHardware.LogInfo = null;
            this.ucRTLessorAVSCustContHardware.Name = "ucRTLessorAVSCustContHardware";
            this.ucRTLessorAVSCustContHardware.RowAffectsCheck = true;
            this.ucRTLessorAVSCustContHardware.SelectCmd = this.RTLessorAVSCustContHardware;
            this.ucRTLessorAVSCustContHardware.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustContHardware.SendSQLCmd = true;
            this.ucRTLessorAVSCustContHardware.ServerModify = true;
            this.ucRTLessorAVSCustContHardware.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustContHardware.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustContHardware.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustContHardware.UseTranscationScope = false;
            this.ucRTLessorAVSCustContHardware.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCustContSndwork
            // 
            this.RTLessorAVSCustContSndwork.CacheConnection = false;
            this.RTLessorAVSCustContSndwork.CommandText = "SELECT dbo.[RTLessorAVSCustContSndwork].* FROM dbo.[RTLessorAVSCustContSndwork]";
            this.RTLessorAVSCustContSndwork.CommandTimeout = 30;
            this.RTLessorAVSCustContSndwork.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustContSndwork.DynamicTableName = false;
            this.RTLessorAVSCustContSndwork.EEPAlias = null;
            this.RTLessorAVSCustContSndwork.EncodingAfter = null;
            this.RTLessorAVSCustContSndwork.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustContSndwork.EncodingConvert = null;
            this.RTLessorAVSCustContSndwork.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "CUSID";
            keyItem8.KeyName = "ENTRYNO";
            keyItem9.KeyName = "PRTNO";
            this.RTLessorAVSCustContSndwork.KeyFields.Add(keyItem7);
            this.RTLessorAVSCustContSndwork.KeyFields.Add(keyItem8);
            this.RTLessorAVSCustContSndwork.KeyFields.Add(keyItem9);
            this.RTLessorAVSCustContSndwork.MultiSetWhere = false;
            this.RTLessorAVSCustContSndwork.Name = "RTLessorAVSCustContSndwork";
            this.RTLessorAVSCustContSndwork.NotificationAutoEnlist = false;
            this.RTLessorAVSCustContSndwork.SecExcept = null;
            this.RTLessorAVSCustContSndwork.SecFieldName = null;
            this.RTLessorAVSCustContSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustContSndwork.SelectPaging = false;
            this.RTLessorAVSCustContSndwork.SelectTop = 0;
            this.RTLessorAVSCustContSndwork.SiteControl = false;
            this.RTLessorAVSCustContSndwork.SiteFieldName = null;
            this.RTLessorAVSCustContSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustContSndwork
            // 
            this.ucRTLessorAVSCustContSndwork.AutoTrans = true;
            this.ucRTLessorAVSCustContSndwork.ExceptJoin = false;
            fieldAttr58.CharSetNull = false;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "CUSID";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CharSetNull = false;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "ENTRYNO";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CharSetNull = false;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "PRTNO";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CharSetNull = false;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "SENDWORKDAT";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CharSetNull = false;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "PRTUSR";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CharSetNull = false;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "ASSIGNENGINEER";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CharSetNull = false;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "ASSIGNCONSIGNEE";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CharSetNull = false;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "REALENGINEER";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CharSetNull = false;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "REALCONSIGNEE";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CharSetNull = false;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "DROPDAT";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CharSetNull = false;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "DROPDESC";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CharSetNull = false;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "CLOSEDAT";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CharSetNull = false;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "BONUSCLOSEYM";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CharSetNull = false;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "BONUSCLOSEDAT";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CharSetNull = false;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "BONUSCLOSEUSR";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CharSetNull = false;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "BONUSFINCHK";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CharSetNull = false;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "STOCKCLOSEYM";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            fieldAttr75.CharSetNull = false;
            fieldAttr75.CheckNull = false;
            fieldAttr75.DataField = "STOCKCLOSEDAT";
            fieldAttr75.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr75.DefaultValue = null;
            fieldAttr75.TrimLength = 0;
            fieldAttr75.UpdateEnable = true;
            fieldAttr75.WhereMode = true;
            fieldAttr76.CharSetNull = false;
            fieldAttr76.CheckNull = false;
            fieldAttr76.DataField = "STOCKCLOSEUSR";
            fieldAttr76.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr76.DefaultValue = null;
            fieldAttr76.TrimLength = 0;
            fieldAttr76.UpdateEnable = true;
            fieldAttr76.WhereMode = true;
            fieldAttr77.CharSetNull = false;
            fieldAttr77.CheckNull = false;
            fieldAttr77.DataField = "STOCKFINCHK";
            fieldAttr77.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr77.DefaultValue = null;
            fieldAttr77.TrimLength = 0;
            fieldAttr77.UpdateEnable = true;
            fieldAttr77.WhereMode = true;
            fieldAttr78.CharSetNull = false;
            fieldAttr78.CheckNull = false;
            fieldAttr78.DataField = "MDF1";
            fieldAttr78.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr78.DefaultValue = null;
            fieldAttr78.TrimLength = 0;
            fieldAttr78.UpdateEnable = true;
            fieldAttr78.WhereMode = true;
            fieldAttr79.CharSetNull = false;
            fieldAttr79.CheckNull = false;
            fieldAttr79.DataField = "MDF2";
            fieldAttr79.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr79.DefaultValue = null;
            fieldAttr79.TrimLength = 0;
            fieldAttr79.UpdateEnable = true;
            fieldAttr79.WhereMode = true;
            fieldAttr80.CharSetNull = false;
            fieldAttr80.CheckNull = false;
            fieldAttr80.DataField = "HOSTNO";
            fieldAttr80.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr80.DefaultValue = null;
            fieldAttr80.TrimLength = 0;
            fieldAttr80.UpdateEnable = true;
            fieldAttr80.WhereMode = true;
            fieldAttr81.CharSetNull = false;
            fieldAttr81.CheckNull = false;
            fieldAttr81.DataField = "HOSTPORT";
            fieldAttr81.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr81.DefaultValue = null;
            fieldAttr81.TrimLength = 0;
            fieldAttr81.UpdateEnable = true;
            fieldAttr81.WhereMode = true;
            fieldAttr82.CharSetNull = false;
            fieldAttr82.CheckNull = false;
            fieldAttr82.DataField = "MEMO";
            fieldAttr82.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr82.DefaultValue = null;
            fieldAttr82.TrimLength = 0;
            fieldAttr82.UpdateEnable = true;
            fieldAttr82.WhereMode = true;
            fieldAttr83.CharSetNull = false;
            fieldAttr83.CheckNull = false;
            fieldAttr83.DataField = "PRTDAT";
            fieldAttr83.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr83.DefaultValue = null;
            fieldAttr83.TrimLength = 0;
            fieldAttr83.UpdateEnable = true;
            fieldAttr83.WhereMode = true;
            fieldAttr84.CharSetNull = false;
            fieldAttr84.CheckNull = false;
            fieldAttr84.DataField = "UNCLOSEDAT";
            fieldAttr84.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr84.DefaultValue = null;
            fieldAttr84.TrimLength = 0;
            fieldAttr84.UpdateEnable = true;
            fieldAttr84.WhereMode = true;
            fieldAttr85.CharSetNull = false;
            fieldAttr85.CheckNull = false;
            fieldAttr85.DataField = "DROPUSR";
            fieldAttr85.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr85.DefaultValue = null;
            fieldAttr85.TrimLength = 0;
            fieldAttr85.UpdateEnable = true;
            fieldAttr85.WhereMode = true;
            fieldAttr86.CharSetNull = false;
            fieldAttr86.CheckNull = false;
            fieldAttr86.DataField = "CLOSEUSR";
            fieldAttr86.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr86.DefaultValue = null;
            fieldAttr86.TrimLength = 0;
            fieldAttr86.UpdateEnable = true;
            fieldAttr86.WhereMode = true;
            fieldAttr87.CharSetNull = false;
            fieldAttr87.CheckNull = false;
            fieldAttr87.DataField = "EUSR";
            fieldAttr87.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr87.DefaultValue = null;
            fieldAttr87.TrimLength = 0;
            fieldAttr87.UpdateEnable = true;
            fieldAttr87.WhereMode = true;
            fieldAttr88.CharSetNull = false;
            fieldAttr88.CheckNull = false;
            fieldAttr88.DataField = "EDAT";
            fieldAttr88.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr88.DefaultValue = null;
            fieldAttr88.TrimLength = 0;
            fieldAttr88.UpdateEnable = true;
            fieldAttr88.WhereMode = true;
            fieldAttr89.CharSetNull = false;
            fieldAttr89.CheckNull = false;
            fieldAttr89.DataField = "UUSR";
            fieldAttr89.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr89.DefaultValue = null;
            fieldAttr89.TrimLength = 0;
            fieldAttr89.UpdateEnable = true;
            fieldAttr89.WhereMode = true;
            fieldAttr90.CharSetNull = false;
            fieldAttr90.CheckNull = false;
            fieldAttr90.DataField = "UDAT";
            fieldAttr90.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr90.DefaultValue = null;
            fieldAttr90.TrimLength = 0;
            fieldAttr90.UpdateEnable = true;
            fieldAttr90.WhereMode = true;
            fieldAttr91.CharSetNull = false;
            fieldAttr91.CheckNull = false;
            fieldAttr91.DataField = "BATCHNO";
            fieldAttr91.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr91.DefaultValue = null;
            fieldAttr91.TrimLength = 0;
            fieldAttr91.UpdateEnable = true;
            fieldAttr91.WhereMode = true;
            fieldAttr92.CharSetNull = false;
            fieldAttr92.CheckNull = false;
            fieldAttr92.DataField = "CDAT";
            fieldAttr92.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr92.DefaultValue = null;
            fieldAttr92.TrimLength = 0;
            fieldAttr92.UpdateEnable = true;
            fieldAttr92.WhereMode = true;
            fieldAttr93.CharSetNull = false;
            fieldAttr93.CheckNull = false;
            fieldAttr93.DataField = "MAXENTRYNO";
            fieldAttr93.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr93.DefaultValue = null;
            fieldAttr93.TrimLength = 0;
            fieldAttr93.UpdateEnable = true;
            fieldAttr93.WhereMode = true;
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr58);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr59);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr60);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr61);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr62);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr63);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr64);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr65);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr66);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr67);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr68);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr69);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr70);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr71);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr72);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr73);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr74);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr75);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr76);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr77);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr78);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr79);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr80);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr81);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr82);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr83);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr84);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr85);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr86);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr87);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr88);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr89);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr90);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr91);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr92);
            this.ucRTLessorAVSCustContSndwork.FieldAttrs.Add(fieldAttr93);
            this.ucRTLessorAVSCustContSndwork.LogInfo = null;
            this.ucRTLessorAVSCustContSndwork.Name = "ucRTLessorAVSCustContSndwork";
            this.ucRTLessorAVSCustContSndwork.RowAffectsCheck = true;
            this.ucRTLessorAVSCustContSndwork.SelectCmd = this.RTLessorAVSCustContSndwork;
            this.ucRTLessorAVSCustContSndwork.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustContSndwork.SendSQLCmd = true;
            this.ucRTLessorAVSCustContSndwork.ServerModify = true;
            this.ucRTLessorAVSCustContSndwork.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustContSndwork.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustContSndwork.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustContSndwork.UseTranscationScope = false;
            this.ucRTLessorAVSCustContSndwork.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustCont
            // 
            this.View_RTLessorAVSCustCont.CacheConnection = false;
            this.View_RTLessorAVSCustCont.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustCont]";
            this.View_RTLessorAVSCustCont.CommandTimeout = 30;
            this.View_RTLessorAVSCustCont.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustCont.DynamicTableName = false;
            this.View_RTLessorAVSCustCont.EEPAlias = null;
            this.View_RTLessorAVSCustCont.EncodingAfter = null;
            this.View_RTLessorAVSCustCont.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustCont.EncodingConvert = null;
            this.View_RTLessorAVSCustCont.InfoConnection = this.InfoConnection1;
            keyItem10.KeyName = "CUSID";
            keyItem11.KeyName = "ENTRYNO";
            this.View_RTLessorAVSCustCont.KeyFields.Add(keyItem10);
            this.View_RTLessorAVSCustCont.KeyFields.Add(keyItem11);
            this.View_RTLessorAVSCustCont.MultiSetWhere = false;
            this.View_RTLessorAVSCustCont.Name = "View_RTLessorAVSCustCont";
            this.View_RTLessorAVSCustCont.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustCont.SecExcept = null;
            this.View_RTLessorAVSCustCont.SecFieldName = null;
            this.View_RTLessorAVSCustCont.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustCont.SelectPaging = false;
            this.View_RTLessorAVSCustCont.SelectTop = 0;
            this.View_RTLessorAVSCustCont.SiteControl = false;
            this.View_RTLessorAVSCustCont.SiteFieldName = null;
            this.View_RTLessorAVSCustCont.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCustContHardware
            // 
            this.View_RTLessorAVSCustContHardware.CacheConnection = false;
            this.View_RTLessorAVSCustContHardware.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustContHardware]";
            this.View_RTLessorAVSCustContHardware.CommandTimeout = 30;
            this.View_RTLessorAVSCustContHardware.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustContHardware.DynamicTableName = false;
            this.View_RTLessorAVSCustContHardware.EEPAlias = null;
            this.View_RTLessorAVSCustContHardware.EncodingAfter = null;
            this.View_RTLessorAVSCustContHardware.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustContHardware.EncodingConvert = null;
            this.View_RTLessorAVSCustContHardware.InfoConnection = this.InfoConnection1;
            keyItem12.KeyName = "CUSID";
            keyItem13.KeyName = "ENTRYNO";
            keyItem14.KeyName = "PRTNO";
            keyItem15.KeyName = "SEQ";
            this.View_RTLessorAVSCustContHardware.KeyFields.Add(keyItem12);
            this.View_RTLessorAVSCustContHardware.KeyFields.Add(keyItem13);
            this.View_RTLessorAVSCustContHardware.KeyFields.Add(keyItem14);
            this.View_RTLessorAVSCustContHardware.KeyFields.Add(keyItem15);
            this.View_RTLessorAVSCustContHardware.MultiSetWhere = false;
            this.View_RTLessorAVSCustContHardware.Name = "View_RTLessorAVSCustContHardware";
            this.View_RTLessorAVSCustContHardware.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustContHardware.SecExcept = null;
            this.View_RTLessorAVSCustContHardware.SecFieldName = null;
            this.View_RTLessorAVSCustContHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustContHardware.SelectPaging = false;
            this.View_RTLessorAVSCustContHardware.SelectTop = 0;
            this.View_RTLessorAVSCustContHardware.SiteControl = false;
            this.View_RTLessorAVSCustContHardware.SiteFieldName = null;
            this.View_RTLessorAVSCustContHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCustContSndwork
            // 
            this.View_RTLessorAVSCustContSndwork.CacheConnection = false;
            this.View_RTLessorAVSCustContSndwork.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustContSndwork]";
            this.View_RTLessorAVSCustContSndwork.CommandTimeout = 30;
            this.View_RTLessorAVSCustContSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustContSndwork.DynamicTableName = false;
            this.View_RTLessorAVSCustContSndwork.EEPAlias = null;
            this.View_RTLessorAVSCustContSndwork.EncodingAfter = null;
            this.View_RTLessorAVSCustContSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustContSndwork.EncodingConvert = null;
            this.View_RTLessorAVSCustContSndwork.InfoConnection = this.InfoConnection1;
            keyItem16.KeyName = "CUSID";
            keyItem17.KeyName = "ENTRYNO";
            keyItem18.KeyName = "PRTNO";
            this.View_RTLessorAVSCustContSndwork.KeyFields.Add(keyItem16);
            this.View_RTLessorAVSCustContSndwork.KeyFields.Add(keyItem17);
            this.View_RTLessorAVSCustContSndwork.KeyFields.Add(keyItem18);
            this.View_RTLessorAVSCustContSndwork.MultiSetWhere = false;
            this.View_RTLessorAVSCustContSndwork.Name = "View_RTLessorAVSCustContSndwork";
            this.View_RTLessorAVSCustContSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustContSndwork.SecExcept = null;
            this.View_RTLessorAVSCustContSndwork.SecFieldName = null;
            this.View_RTLessorAVSCustContSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustContSndwork.SelectPaging = false;
            this.View_RTLessorAVSCustContSndwork.SelectTop = 0;
            this.View_RTLessorAVSCustContSndwork.SiteControl = false;
            this.View_RTLessorAVSCustContSndwork.SiteFieldName = null;
            this.View_RTLessorAVSCustContSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT10431
            // 
            this.RT10431.CacheConnection = false;
            this.RT10431.CommandText = resources.GetString("RT10431.CommandText");
            this.RT10431.CommandTimeout = 30;
            this.RT10431.CommandType = System.Data.CommandType.Text;
            this.RT10431.DynamicTableName = false;
            this.RT10431.EEPAlias = null;
            this.RT10431.EncodingAfter = null;
            this.RT10431.EncodingBefore = "Windows-1252";
            this.RT10431.EncodingConvert = null;
            this.RT10431.InfoConnection = this.InfoConnection1;
            keyItem19.KeyName = "CUSID";
            keyItem20.KeyName = "ENTRYNO";
            keyItem21.KeyName = "PRTNO";
            keyItem22.KeyName = "PRTNO1";
            this.RT10431.KeyFields.Add(keyItem19);
            this.RT10431.KeyFields.Add(keyItem20);
            this.RT10431.KeyFields.Add(keyItem21);
            this.RT10431.KeyFields.Add(keyItem22);
            this.RT10431.MultiSetWhere = false;
            this.RT10431.Name = "RT10431";
            this.RT10431.NotificationAutoEnlist = false;
            this.RT10431.SecExcept = null;
            this.RT10431.SecFieldName = null;
            this.RT10431.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT10431.SelectPaging = false;
            this.RT10431.SelectTop = 0;
            this.RT10431.SiteControl = false;
            this.RT10431.SiteFieldName = null;
            this.RT10431.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10431
            // 
            this.cmdRT10431.CacheConnection = false;
            this.cmdRT10431.CommandText = "usp_RTLessorAVSCustContARSndworkF";
            this.cmdRT10431.CommandTimeout = 30;
            this.cmdRT10431.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10431.DynamicTableName = false;
            this.cmdRT10431.EEPAlias = null;
            this.cmdRT10431.EncodingAfter = null;
            this.cmdRT10431.EncodingBefore = "Windows-1252";
            this.cmdRT10431.EncodingConvert = null;
            this.cmdRT10431.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter1.ParameterName = "cusid";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 15;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "entryno";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "prtno";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 12;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "usr";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 6;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter5.ParameterName = "period";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 0;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter6.ParameterName = "rcvmoney";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 0;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter7.ParameterName = "paytype";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 2;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "creditcardno";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 16;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10431.InfoParameters.Add(infoParameter1);
            this.cmdRT10431.InfoParameters.Add(infoParameter2);
            this.cmdRT10431.InfoParameters.Add(infoParameter3);
            this.cmdRT10431.InfoParameters.Add(infoParameter4);
            this.cmdRT10431.InfoParameters.Add(infoParameter5);
            this.cmdRT10431.InfoParameters.Add(infoParameter6);
            this.cmdRT10431.InfoParameters.Add(infoParameter7);
            this.cmdRT10431.InfoParameters.Add(infoParameter8);
            this.cmdRT10431.MultiSetWhere = false;
            this.cmdRT10431.Name = "cmdRT10431";
            this.cmdRT10431.NotificationAutoEnlist = false;
            this.cmdRT10431.SecExcept = null;
            this.cmdRT10431.SecFieldName = null;
            this.cmdRT10431.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10431.SelectPaging = false;
            this.cmdRT10431.SelectTop = 0;
            this.cmdRT10431.SiteControl = false;
            this.cmdRT10431.SiteFieldName = null;
            this.cmdRT10431.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10432
            // 
            this.cmdRT10432.CacheConnection = false;
            this.cmdRT10432.CommandText = "usp_RTLessorAVSCustContARSndworkUF";
            this.cmdRT10432.CommandTimeout = 30;
            this.cmdRT10432.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10432.DynamicTableName = false;
            this.cmdRT10432.EEPAlias = null;
            this.cmdRT10432.EncodingAfter = null;
            this.cmdRT10432.EncodingBefore = "Windows-1252";
            this.cmdRT10432.EncodingConvert = null;
            this.cmdRT10432.InfoConnection = this.InfoConnection1;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "cusid";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 15;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter10.ParameterName = "entryno";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 0;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "prtno";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 12;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter12.ParameterName = "usr";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 6;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10432.InfoParameters.Add(infoParameter9);
            this.cmdRT10432.InfoParameters.Add(infoParameter10);
            this.cmdRT10432.InfoParameters.Add(infoParameter11);
            this.cmdRT10432.InfoParameters.Add(infoParameter12);
            this.cmdRT10432.MultiSetWhere = false;
            this.cmdRT10432.Name = "cmdRT10432";
            this.cmdRT10432.NotificationAutoEnlist = false;
            this.cmdRT10432.SecExcept = null;
            this.cmdRT10432.SecFieldName = null;
            this.cmdRT10432.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10432.SelectPaging = false;
            this.cmdRT10432.SelectTop = 0;
            this.cmdRT10432.SiteControl = false;
            this.cmdRT10432.SiteFieldName = null;
            this.cmdRT10432.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10433
            // 
            this.cmdRT10433.CacheConnection = false;
            this.cmdRT10433.CommandText = "usp_RTLessorAVSCustContARSndworkFR";
            this.cmdRT10433.CommandTimeout = 30;
            this.cmdRT10433.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10433.DynamicTableName = false;
            this.cmdRT10433.EEPAlias = null;
            this.cmdRT10433.EncodingAfter = null;
            this.cmdRT10433.EncodingBefore = "Windows-1252";
            this.cmdRT10433.EncodingConvert = null;
            this.cmdRT10433.InfoConnection = this.InfoConnection1;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter13.ParameterName = "cusid";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 15;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter14.ParameterName = "entryno";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 0;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter15.ParameterName = "prtno";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 12;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter16.ParameterName = "usr";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 6;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            infoParameter17.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter17.ParameterName = "batchnoxx";
            infoParameter17.Precision = ((byte)(0));
            infoParameter17.Scale = ((byte)(0));
            infoParameter17.Size = 12;
            infoParameter17.SourceColumn = null;
            infoParameter17.XmlSchemaCollectionDatabase = null;
            infoParameter17.XmlSchemaCollectionName = null;
            infoParameter17.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10433.InfoParameters.Add(infoParameter13);
            this.cmdRT10433.InfoParameters.Add(infoParameter14);
            this.cmdRT10433.InfoParameters.Add(infoParameter15);
            this.cmdRT10433.InfoParameters.Add(infoParameter16);
            this.cmdRT10433.InfoParameters.Add(infoParameter17);
            this.cmdRT10433.MultiSetWhere = false;
            this.cmdRT10433.Name = "cmdRT10433";
            this.cmdRT10433.NotificationAutoEnlist = false;
            this.cmdRT10433.SecExcept = null;
            this.cmdRT10433.SecFieldName = null;
            this.cmdRT10433.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10433.SelectPaging = false;
            this.cmdRT10433.SelectTop = 0;
            this.cmdRT10433.SiteControl = false;
            this.cmdRT10433.SiteFieldName = null;
            this.cmdRT10433.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10435
            // 
            this.cmdRT10435.CacheConnection = false;
            this.cmdRT10435.CommandText = "usp_RTLessorAVSCustContARSndworkDropC";
            this.cmdRT10435.CommandTimeout = 30;
            this.cmdRT10435.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10435.DynamicTableName = false;
            this.cmdRT10435.EEPAlias = null;
            this.cmdRT10435.EncodingAfter = null;
            this.cmdRT10435.EncodingBefore = "Windows-1252";
            this.cmdRT10435.EncodingConvert = null;
            this.cmdRT10435.InfoConnection = this.InfoConnection1;
            infoParameter18.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter18.ParameterName = "cusid";
            infoParameter18.Precision = ((byte)(0));
            infoParameter18.Scale = ((byte)(0));
            infoParameter18.Size = 15;
            infoParameter18.SourceColumn = null;
            infoParameter18.XmlSchemaCollectionDatabase = null;
            infoParameter18.XmlSchemaCollectionName = null;
            infoParameter18.XmlSchemaCollectionOwningSchema = null;
            infoParameter19.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter19.ParameterName = "entryno";
            infoParameter19.Precision = ((byte)(0));
            infoParameter19.Scale = ((byte)(0));
            infoParameter19.Size = 0;
            infoParameter19.SourceColumn = null;
            infoParameter19.XmlSchemaCollectionDatabase = null;
            infoParameter19.XmlSchemaCollectionName = null;
            infoParameter19.XmlSchemaCollectionOwningSchema = null;
            infoParameter20.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter20.ParameterName = "prtno";
            infoParameter20.Precision = ((byte)(0));
            infoParameter20.Scale = ((byte)(0));
            infoParameter20.Size = 12;
            infoParameter20.SourceColumn = null;
            infoParameter20.XmlSchemaCollectionDatabase = null;
            infoParameter20.XmlSchemaCollectionName = null;
            infoParameter20.XmlSchemaCollectionOwningSchema = null;
            infoParameter21.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter21.ParameterName = "usr";
            infoParameter21.Precision = ((byte)(0));
            infoParameter21.Scale = ((byte)(0));
            infoParameter21.Size = 6;
            infoParameter21.SourceColumn = null;
            infoParameter21.XmlSchemaCollectionDatabase = null;
            infoParameter21.XmlSchemaCollectionName = null;
            infoParameter21.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10435.InfoParameters.Add(infoParameter18);
            this.cmdRT10435.InfoParameters.Add(infoParameter19);
            this.cmdRT10435.InfoParameters.Add(infoParameter20);
            this.cmdRT10435.InfoParameters.Add(infoParameter21);
            this.cmdRT10435.MultiSetWhere = false;
            this.cmdRT10435.Name = "cmdRT10435";
            this.cmdRT10435.NotificationAutoEnlist = false;
            this.cmdRT10435.SecExcept = null;
            this.cmdRT10435.SecFieldName = null;
            this.cmdRT10435.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10435.SelectPaging = false;
            this.cmdRT10435.SelectTop = 0;
            this.cmdRT10435.SiteControl = false;
            this.cmdRT10435.SiteFieldName = null;
            this.cmdRT10435.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10434
            // 
            this.cmdRT10434.CacheConnection = false;
            this.cmdRT10434.CommandText = "usp_RTLessorAVSCustContARSndworkDrop";
            this.cmdRT10434.CommandTimeout = 30;
            this.cmdRT10434.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10434.DynamicTableName = false;
            this.cmdRT10434.EEPAlias = null;
            this.cmdRT10434.EncodingAfter = null;
            this.cmdRT10434.EncodingBefore = "Windows-1252";
            this.cmdRT10434.EncodingConvert = null;
            this.cmdRT10434.InfoConnection = this.InfoConnection1;
            infoParameter22.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter22.ParameterName = "cusid";
            infoParameter22.Precision = ((byte)(0));
            infoParameter22.Scale = ((byte)(0));
            infoParameter22.Size = 15;
            infoParameter22.SourceColumn = null;
            infoParameter22.XmlSchemaCollectionDatabase = null;
            infoParameter22.XmlSchemaCollectionName = null;
            infoParameter22.XmlSchemaCollectionOwningSchema = null;
            infoParameter23.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter23.ParameterName = "entryno";
            infoParameter23.Precision = ((byte)(0));
            infoParameter23.Scale = ((byte)(0));
            infoParameter23.Size = 0;
            infoParameter23.SourceColumn = null;
            infoParameter23.XmlSchemaCollectionDatabase = null;
            infoParameter23.XmlSchemaCollectionName = null;
            infoParameter23.XmlSchemaCollectionOwningSchema = null;
            infoParameter24.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter24.ParameterName = "prtno";
            infoParameter24.Precision = ((byte)(0));
            infoParameter24.Scale = ((byte)(0));
            infoParameter24.Size = 12;
            infoParameter24.SourceColumn = null;
            infoParameter24.XmlSchemaCollectionDatabase = null;
            infoParameter24.XmlSchemaCollectionName = null;
            infoParameter24.XmlSchemaCollectionOwningSchema = null;
            infoParameter25.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter25.ParameterName = "usr";
            infoParameter25.Precision = ((byte)(0));
            infoParameter25.Scale = ((byte)(0));
            infoParameter25.Size = 6;
            infoParameter25.SourceColumn = null;
            infoParameter25.XmlSchemaCollectionDatabase = null;
            infoParameter25.XmlSchemaCollectionName = null;
            infoParameter25.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10434.InfoParameters.Add(infoParameter22);
            this.cmdRT10434.InfoParameters.Add(infoParameter23);
            this.cmdRT10434.InfoParameters.Add(infoParameter24);
            this.cmdRT10434.InfoParameters.Add(infoParameter25);
            this.cmdRT10434.MultiSetWhere = false;
            this.cmdRT10434.Name = "cmdRT10434";
            this.cmdRT10434.NotificationAutoEnlist = false;
            this.cmdRT10434.SecExcept = null;
            this.cmdRT10434.SecFieldName = null;
            this.cmdRT10434.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10434.SelectPaging = false;
            this.cmdRT10434.SelectTop = 0;
            this.cmdRT10434.SiteControl = false;
            this.cmdRT10434.SiteFieldName = null;
            this.cmdRT10434.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustCont)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustContHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustContSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustCont)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustContHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustContSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10431)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10431)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10432)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10433)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10435)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10434)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustCont;
        private Srvtools.UpdateComponent ucRTLessorAVSCustCont;
        private Srvtools.InfoCommand RTLessorAVSCustContHardware;
        private Srvtools.UpdateComponent ucRTLessorAVSCustContHardware;
        private Srvtools.InfoCommand RTLessorAVSCustContSndwork;
        private Srvtools.UpdateComponent ucRTLessorAVSCustContSndwork;
        private Srvtools.InfoCommand View_RTLessorAVSCustCont;
        private Srvtools.InfoCommand View_RTLessorAVSCustContHardware;
        private Srvtools.InfoCommand View_RTLessorAVSCustContSndwork;
        private Srvtools.InfoCommand RT10431;
        private Srvtools.InfoCommand cmdRT10431;
        private Srvtools.InfoCommand cmdRT10432;
        private Srvtools.InfoCommand cmdRT10433;
        private Srvtools.InfoCommand cmdRT10435;
        private Srvtools.InfoCommand cmdRT10434;
    }
}
