insert into RTLessorAVSCmtyH
(           COMN, CUTID, TOWNSHIP, RADDR, RZONE, CUTID2, TOWNSHIP2, RADDR2, CUTID3, 
                            TOWNSHIP3, RADDR3, CUTID4, TOWNSHIP4, RADDR4, COMCNT, BUILDTYPE, BUILDCNT, BUILDFLOOR, 
                            POWERJECT, POWERTYPE, POWERDISTANCE, SETUPTYPE, CABLELENGTH, AGREEDRILL, TELCOMROOM, 
                            SURVEYDAT, AGREEDAT, AGREE, UNAGREEDESC, UPDEBTCHKDAT, UPDEBTCHKUSR, UPDEBTDAT, TELCOMBOX, 
                            CONTACT, CONTACTTEL, EUSR, EDAT, UUSR, UDAT, REMITAGREE, COPYREMIT, REMITNO, 
                            REMITBANK, BANKBRANCH, REMITACCOUNT, REMITNAME, CHECKTITLE, CCUTID, CTOWNSHIP, CADDR
							,COMTYPE)

SELECT           COMN, CUTID, TOWNSHIP, RADDR, RZONE, CUTID2, TOWNSHIP2, RADDR2, CUTID3, 
                            TOWNSHIP3, RADDR3, CUTID4, TOWNSHIP4, RADDR4, COMCNT, BUILDTYPE, BUILDCNT, BUILDFLOOR, 
                            POWERJECT, POWERTYPE, POWERDISTANCE, SETUPTYPE, CABLELENGTH, AGREEDRILL, TELCOMROOM, 
                            SURVEYDAT, AGREEDAT, AGREE, UNAGREEDESC, UPDEBTCHKDAT, UPDEBTCHKUSR, UPDEBTDAT, TELCOMBOX, 
                            CONTACT, CONTACTTEL, EUSR, EDAT, UUSR, UDAT, REMITAGREE, COPYREMIT, REMITNO, 
                            REMITBANK, BANKBRANCH, REMITACCOUNT, REMITNAME, CHECKTITLE, CCUTID, CTOWNSHIP, CADDR, '8'
FROM              RTLessorCmtyH