insert into RTLessorAVSCmtyLine
( COMQ1,LINEQ1, CUTID, TOWNSHIP, RADDR, RZONE,  LOANNAME, LOANSOCIAL,  
                            LINEIP, GATEWAY, SUBNET, DNSIP, PPPOEACCOUNT, PPPOEPASSWORD, LINETEL, LINERATE, LINEISP, 
                            LINEIPTYPE, APPLYDAT,  DROPDAT, UUSR, UDAT, CANCELUSR, CANCELDAT, MEMO,EUSR)

SELECT          B.COMQ1,  LINEQ1, CUTID, TOWNSHIP, RADDR, RZONE,  LOANNAME, LOANSOCIAL,  
                            LINEIP, GATEWAY, SUBNET, DNSIP, PPPOEACCOUNT, PPPOEPASSWORD, LINETEL, LINERATE, LINEISP, 
                            LINEIPTYPE, APPLYDAT,  DROPDAT, UUSR, UDAT, CANCELUSR, CANCELDAT, MEMO,''
FROM              RTPrjCmtyLine A
left join ( 
select A.COMQ1, b.COMQ1 as COMQ1O 
from RTLessorAVSCmtyH A
left join RTPrjCmtyH b on b.COMN=a.COMN
where A.comtype='9') b on b.COMQ1O=a.COMQ1