Insert into RTLessorAVSCustSndworkLog select * from RTLessorCustSndworkLog
Insert into RTLessorAVSCustSndwork select * from RTLessorCustSndwork
Insert into RTLessorAVSCustReturnSndWorkLog select * from RTLessorCustReturnSndWorkLog
--Insert into RTLessorAVSCustReturnSndWork select * from RTLessorCustReturnSndWork
Insert into RTLessorAVSCustReturnLog select * from RTLessorCustReturnLog
Insert into RTLessorAVSCustReturn select * from RTLessorCustReturn
Insert into RTLessorAVSCustRepairLog select * from RTLessorCustRepairLog
Insert into RTLessorAVSCustRepair select * from RTLessorCustRepair
Insert into RTLessorAVSCustRCVHardwareLog select * from RTLessorCustRCVHardwareLog
Insert into RTLessorAVSCustRCVHardwareDTL select * from RTLessorCustRCVHardwareDTL
Insert into RTLessorAVSCustRCVHardware select * from RTLessorCustRCVHardware
--Insert into RTLessorAVSCustLog select * from RTLessorCustLog
Insert into RTLessorAVSCustHardwareLog select * from RTLessorCustHardwareLog
Insert into RTLessorAVSCustHardware select * from RTLessorCustHardware
Insert into RTLessorAVSCustFaqSndworkLog select * from RTLessorCustFaqSndworkLog
Insert into RTLessorAVSCustFaqSndworkFixCode select * from RTLessorCustFaqSndworkFixCode
Insert into RTLessorAVSCustFaqSndwork select * from RTLessorCustFaqSndwork
--Insert into RTLessorAVSCustFaqList select * from RTLessorCustFaqList
Insert into RTLessorAVSCustFaqHLog select * from RTLessorCustFaqHLog
Insert into RTLessorAVSCustFaqHardwareLog select * from RTLessorCustFaqHardwareLog
Insert into RTLessorAVSCustFaqHardware select * from RTLessorCustFaqHardware
Insert into RTLessorAVSCustFaqH select * from RTLessorCustFaqH
Insert into RTLessorAVSCustDropSndworkLog select * from RTLessorCustDropSndworkLog
Insert into RTLessorAVSCustDropSndwork select * from RTLessorCustDropSndwork
Insert into RTLessorAVSCustDropLog select * from RTLessorCustDropLog
Insert into RTLessorAVSCustDrop select * from RTLessorCustDrop
Insert into RTLessorAVSCustContSndworkLog select * from RTLessorCustContSndworkLog
Insert into RTLessorAVSCustContSndwork select * from RTLessorCustContSndwork
Insert into RTLessorAVSCustContLog select * from RTLessorCustContLog
Insert into RTLessorAVSCustCont select * from RTLessorCustCont
--Insert into RTLessorAVSCustBillingPrtSub select * from RTLessorCustBillingPrtSub
--Insert into RTLessorAVSCustBillingPrt select * from RTLessorCustBillingPrt
Insert into RTLessorAVSCustBillingBarcode select * from RTLessorCustBillingBarcode
Insert into RTLessorAVSCustARDTL select * from RTLessorCustARDTL
Insert into RTLessorAVSCustARClear select * from RTLessorCustARClear
Insert into RTLessorAVSCustAR select * from RTLessorCustAR
Insert into RTLessorAVSCustAdjDayLog select * from RTLessorCustAdjDayLog
Insert into RTLessorAVSCustAdjDay select * from RTLessorCustAdjDay
Insert into RTLessorAVSCmtylineSndworkLog select * from RTLessorCmtylineSndworkLog
Insert into RTLessorAVSCmtyLineSndwork select * from RTLessorCmtyLineSndwork
--Insert into RTLessorAVSCmtyLineLog select * from RTLessorCmtyLineLog
Insert into RTLessorAVSCmtyLineDropSndworkLog select * from RTLessorCmtyLineDropSndworkLog
Insert into RTLessorAVSCmtyLineDropSndwork select * from RTLessorCmtyLineDropSndwork
--Insert into RTLessorAVSCmtyLineDropLog select * from RTLessorCmtyLineDropLog
--Insert into RTLessorAVSCmtyLineDrop select * from RTLessorCmtyLineDrop
--Insert into RTLessorAVSCmtyLine select * from RTLessorCmtyLine
