--SELECT * FROM RTLessorAVSCmtyH

ALTER TABLE RTLessorAVSCmtyH
ADD CZONE VARCHAR(10) NULL

INSERT INTO RTCode
(KIND, CODE, CODENC)
VALUES
('R2', '04', '分散電信室')

--SELECT * FROM RTCode
--WHERE CODENC LIKE '%電信%'

ALTER TABLE RTLessorAVSCmtyH
ALTER COLUMN TELCOMBOX VARCHAR(4)