--SELECT A.COMTYPE, A.CASEKIND, A.USERRATE, B.CODE 
UPDATE A SET A.COMTYPE='B', A.CASEKIND=ISNULL(B.CODE, '56')
FROM RTLessorAVSCust a
left join RTCode B ON B.KIND ='O9' AND B.CODENC=A.USERRATE
WHERE CUSNC LIKE '%SPA%'