UPDATE RTLessorAVSCmtyLine
SET RADDR=
  CASE WHEN VILLAGE <> '' THEN VILLAGE+COD1 ELSE '' END 
+ CASE WHEN NEIGHBOR <> '' THEN NEIGHBOR+COD2 ELSE '' END 
+ CASE WHEN STREET <> '' THEN STREET+COD3 ELSE '' END 
+ CASE WHEN SEC <> '' THEN SEC+COD4 ELSE '' END 
+ CASE WHEN LANE <> '' THEN LANE+COD5 ELSE '' END 
+ CASE WHEN TOWN <> '' THEN TOWN+COD6 ELSE '' END 
+ CASE WHEN ALLEYWAY <> '' THEN ALLEYWAY+COD7 ELSE '' END 
+ CASE WHEN NUM <> '' THEN NUM+COD8 ELSE '' END 
+ CASE WHEN FLOOR <> '' THEN FLOOR+COD9 ELSE '' END 
+ CASE WHEN ROOM <> '' THEN ROOM+COD10 ELSE '' END 
from RTLessorAVSCmtyLine