INSERT INTO RTLessorAVSCmtyLine
(COMQ1, LINEQ1, CUTID, TOWNSHIP, RADDR, RZONE,  LOANNAME, LOANSOCIAL,  
LINEIP, GATEWAY, SUBNET, DNSIP, PPPOEACCOUNT, PPPOEPASSWORD, LINETEL, LINERATE, LINEISP, 
LINEIPTYPE, APPLYDAT,  DROPDAT, UUSR, UDAT, CANCELUSR, CANCELDAT, MEMO, EUSR)
SELECT B.Q1, LINEQ1, CUTID, TOWNSHIP, RADDR, RZONE,  LOANNAME, LOANSOCIAL,  
LINEIP, GATEWAY, SUBNET, DNSIP, PPPOEACCOUNT, PPPOEPASSWORD, LINETEL, LINERATE, LINEISP, 
LINEIPTYPE, APPLYDAT,  DROPDAT, UUSR, UDAT, CANCELUSR, CANCELDAT, MEMO, UUSR
 FROM RTPrjCmtyLine A
 LEFT JOIN (SELECT B.COMQ1, A.COMQ1 AS Q1 FROM RTLessorAVSCmtyH A
LEFT JOIN RTPrjCmtyH B ON B.COMN=A.COMN
WHERE A.COMTYPE = '9') B ON B.COMQ1=A.COMQ1