DROP VIEW V_BARCODE 

CREATE VIEW V_BARCODE AS 
select 
(SELECT COUNT(*) 
FROM RTLessorAVSCustBillingBarcode RD 
WHERE RD.NOTICEID = R.NOTICEID AND RD.CASEKIND = R.CASEKIND AND RD.PAYCYCLE <= R.PAYCYCLE
) AS ITEMNO
, R.*, J.CODENC, '¡¼' + j.codenc+'('+ convert(varchar(6), j.PARM1) +'¤¸)'  as CASEPAYD
, CASE WHEN CODE='01' THEN 6 WHEN CODE='02' THEN 12 WHEN CODE='03' THEN 24
WHEN CODE='04' THEN 36 WHEN CODE='05' THEN 3 WHEN CODE='06' THEN 1 END AS QT_MON
from RTLessorAVSCustBillingBarcode R
left outer join RTCode j on j.code = R.PAYCYCLE and j.kind ='M8' 
--ORDER BY R.NOTICEID, R.ITEMNO