namespace sRT2021
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter17 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter18 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter19 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter20 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter21 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter22 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter23 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter24 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter25 = new Srvtools.InfoParameter();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem13 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem14 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem15 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem16 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyLineFaqSndwork = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyLineFaqSndwork = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCmtyLineFaqSndwork = new Srvtools.InfoCommand(this.components);
            this.cmdRT20213 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20214 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20215 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20216 = new Srvtools.InfoCommand(this.components);
            this.cmdRT20217 = new Srvtools.InfoCommand(this.components);
            this.cmd = new Srvtools.InfoCommand(this.components);
            this.RT20211 = new Srvtools.InfoCommand(this.components);
            this.RT20219 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineFaqSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyLineFaqSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20213)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20214)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20215)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20216)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20217)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20211)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20219)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyLineFaqSndwork
            // 
            this.RTLessorAVSCmtyLineFaqSndwork.CacheConnection = false;
            this.RTLessorAVSCmtyLineFaqSndwork.CommandText = "SELECT dbo.[RTLessorAVSCmtyLineFaqSndwork].* FROM dbo.[RTLessorAVSCmtyLineFaqSndw" +
    "ork]";
            this.RTLessorAVSCmtyLineFaqSndwork.CommandTimeout = 30;
            this.RTLessorAVSCmtyLineFaqSndwork.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyLineFaqSndwork.DynamicTableName = false;
            this.RTLessorAVSCmtyLineFaqSndwork.EEPAlias = null;
            this.RTLessorAVSCmtyLineFaqSndwork.EncodingAfter = null;
            this.RTLessorAVSCmtyLineFaqSndwork.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyLineFaqSndwork.EncodingConvert = null;
            this.RTLessorAVSCmtyLineFaqSndwork.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "LINEQ1";
            keyItem3.KeyName = "FAQNO";
            keyItem4.KeyName = "PRTNO";
            this.RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem3);
            this.RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem4);
            this.RTLessorAVSCmtyLineFaqSndwork.MultiSetWhere = false;
            this.RTLessorAVSCmtyLineFaqSndwork.Name = "RTLessorAVSCmtyLineFaqSndwork";
            this.RTLessorAVSCmtyLineFaqSndwork.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyLineFaqSndwork.SecExcept = null;
            this.RTLessorAVSCmtyLineFaqSndwork.SecFieldName = null;
            this.RTLessorAVSCmtyLineFaqSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyLineFaqSndwork.SelectPaging = false;
            this.RTLessorAVSCmtyLineFaqSndwork.SelectTop = 0;
            this.RTLessorAVSCmtyLineFaqSndwork.SiteControl = false;
            this.RTLessorAVSCmtyLineFaqSndwork.SiteFieldName = null;
            this.RTLessorAVSCmtyLineFaqSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyLineFaqSndwork
            // 
            this.ucRTLessorAVSCmtyLineFaqSndwork.AutoTrans = true;
            this.ucRTLessorAVSCmtyLineFaqSndwork.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "LINEQ1";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "FAQNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "PRTNO";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "SENDWORKDAT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "PRTUSR";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "ASSIGNENGINEER";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "ASSIGNCONSIGNEE";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "REALENGINEER";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "REALCONSIGNEE";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "DROPDAT";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "DROPDESC";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "CLOSEDAT";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "BONUSCLOSEYM";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "BONUSCLOSEDAT";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "BONUSCLOSEUSR";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "BONUSFINCHK";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "STOCKCLOSEYM";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "STOCKCLOSEDAT";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "STOCKCLOSEUSR";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "STOCKFINCHK";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "MDF1";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "MDF2";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "HOSTNO";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "HOSTPORT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "MEMO";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "PRTDAT";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "UNCLOSEDAT";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "DROPUSR";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "CLOSEUSR";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "EUSR";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "EDAT";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "UUSR";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "UDAT";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "BATCHNO";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "CDAT";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "MAXENTRYNO";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCmtyLineFaqSndwork.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCmtyLineFaqSndwork.LogInfo = null;
            this.ucRTLessorAVSCmtyLineFaqSndwork.Name = "ucRTLessorAVSCmtyLineFaqSndwork";
            this.ucRTLessorAVSCmtyLineFaqSndwork.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyLineFaqSndwork.SelectCmd = this.RTLessorAVSCmtyLineFaqSndwork;
            this.ucRTLessorAVSCmtyLineFaqSndwork.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyLineFaqSndwork.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyLineFaqSndwork.ServerModify = true;
            this.ucRTLessorAVSCmtyLineFaqSndwork.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyLineFaqSndwork.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyLineFaqSndwork.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyLineFaqSndwork.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyLineFaqSndwork.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCmtyLineFaqSndwork
            // 
            this.View_RTLessorAVSCmtyLineFaqSndwork.CacheConnection = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.CommandText = "SELECT * FROM dbo.[RTLessorAVSCmtyLineFaqSndwork]";
            this.View_RTLessorAVSCmtyLineFaqSndwork.CommandTimeout = 30;
            this.View_RTLessorAVSCmtyLineFaqSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCmtyLineFaqSndwork.DynamicTableName = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.EEPAlias = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.EncodingAfter = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCmtyLineFaqSndwork.EncodingConvert = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "COMQ1";
            keyItem6.KeyName = "LINEQ1";
            keyItem7.KeyName = "FAQNO";
            keyItem8.KeyName = "PRTNO";
            this.View_RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem5);
            this.View_RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem6);
            this.View_RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem7);
            this.View_RTLessorAVSCmtyLineFaqSndwork.KeyFields.Add(keyItem8);
            this.View_RTLessorAVSCmtyLineFaqSndwork.MultiSetWhere = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.Name = "View_RTLessorAVSCmtyLineFaqSndwork";
            this.View_RTLessorAVSCmtyLineFaqSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SecExcept = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SecFieldName = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SelectPaging = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SelectTop = 0;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SiteControl = false;
            this.View_RTLessorAVSCmtyLineFaqSndwork.SiteFieldName = null;
            this.View_RTLessorAVSCmtyLineFaqSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20213
            // 
            this.cmdRT20213.CacheConnection = false;
            this.cmdRT20213.CommandText = "usp_RTLessorAVSCmtyLineFAQSndworkF";
            this.cmdRT20213.CommandTimeout = 30;
            this.cmdRT20213.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20213.DynamicTableName = false;
            this.cmdRT20213.EEPAlias = null;
            this.cmdRT20213.EncodingAfter = null;
            this.cmdRT20213.EncodingBefore = "Windows-1252";
            this.cmdRT20213.EncodingConvert = null;
            this.cmdRT20213.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter1.ParameterName = "comq1";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 0;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "lineq1";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "faqno";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 13;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "prtno";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 12;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "usr";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 6;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20213.InfoParameters.Add(infoParameter1);
            this.cmdRT20213.InfoParameters.Add(infoParameter2);
            this.cmdRT20213.InfoParameters.Add(infoParameter3);
            this.cmdRT20213.InfoParameters.Add(infoParameter4);
            this.cmdRT20213.InfoParameters.Add(infoParameter5);
            this.cmdRT20213.MultiSetWhere = false;
            this.cmdRT20213.Name = "cmdRT20213";
            this.cmdRT20213.NotificationAutoEnlist = false;
            this.cmdRT20213.SecExcept = null;
            this.cmdRT20213.SecFieldName = null;
            this.cmdRT20213.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20213.SelectPaging = false;
            this.cmdRT20213.SelectTop = 0;
            this.cmdRT20213.SiteControl = false;
            this.cmdRT20213.SiteFieldName = null;
            this.cmdRT20213.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20214
            // 
            this.cmdRT20214.CacheConnection = false;
            this.cmdRT20214.CommandText = "usp_RTLessorAVSCmtylineFAQSndworkUF";
            this.cmdRT20214.CommandTimeout = 30;
            this.cmdRT20214.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20214.DynamicTableName = false;
            this.cmdRT20214.EEPAlias = null;
            this.cmdRT20214.EncodingAfter = null;
            this.cmdRT20214.EncodingBefore = "Windows-1252";
            this.cmdRT20214.EncodingConvert = null;
            this.cmdRT20214.InfoConnection = this.InfoConnection1;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter6.ParameterName = "comq1";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 0;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter7.ParameterName = "lineq1";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 0;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "faqno";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 13;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "prtno";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 13;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter10.ParameterName = "usr";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 6;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20214.InfoParameters.Add(infoParameter6);
            this.cmdRT20214.InfoParameters.Add(infoParameter7);
            this.cmdRT20214.InfoParameters.Add(infoParameter8);
            this.cmdRT20214.InfoParameters.Add(infoParameter9);
            this.cmdRT20214.InfoParameters.Add(infoParameter10);
            this.cmdRT20214.MultiSetWhere = false;
            this.cmdRT20214.Name = "cmdRT20214";
            this.cmdRT20214.NotificationAutoEnlist = false;
            this.cmdRT20214.SecExcept = null;
            this.cmdRT20214.SecFieldName = null;
            this.cmdRT20214.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20214.SelectPaging = false;
            this.cmdRT20214.SelectTop = 0;
            this.cmdRT20214.SiteControl = false;
            this.cmdRT20214.SiteFieldName = null;
            this.cmdRT20214.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20215
            // 
            this.cmdRT20215.CacheConnection = false;
            this.cmdRT20215.CommandText = "usp_RTLessorAVSCmtylineFaqSndworkFR";
            this.cmdRT20215.CommandTimeout = 30;
            this.cmdRT20215.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20215.DynamicTableName = false;
            this.cmdRT20215.EEPAlias = null;
            this.cmdRT20215.EncodingAfter = null;
            this.cmdRT20215.EncodingBefore = "Windows-1252";
            this.cmdRT20215.EncodingConvert = null;
            this.cmdRT20215.InfoConnection = this.InfoConnection1;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter11.ParameterName = "comq1";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 0;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter12.ParameterName = "lineq1";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 0;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter13.ParameterName = "faqno";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 13;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter14.ParameterName = "prtno";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 13;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter15.ParameterName = "usr";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 6;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20215.InfoParameters.Add(infoParameter11);
            this.cmdRT20215.InfoParameters.Add(infoParameter12);
            this.cmdRT20215.InfoParameters.Add(infoParameter13);
            this.cmdRT20215.InfoParameters.Add(infoParameter14);
            this.cmdRT20215.InfoParameters.Add(infoParameter15);
            this.cmdRT20215.MultiSetWhere = false;
            this.cmdRT20215.Name = "cmdRT20215";
            this.cmdRT20215.NotificationAutoEnlist = false;
            this.cmdRT20215.SecExcept = null;
            this.cmdRT20215.SecFieldName = null;
            this.cmdRT20215.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20215.SelectPaging = false;
            this.cmdRT20215.SelectTop = 0;
            this.cmdRT20215.SiteControl = false;
            this.cmdRT20215.SiteFieldName = null;
            this.cmdRT20215.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20216
            // 
            this.cmdRT20216.CacheConnection = false;
            this.cmdRT20216.CommandText = "usp_RTLessorAVSCmtylineFaqSndworkDrop";
            this.cmdRT20216.CommandTimeout = 30;
            this.cmdRT20216.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20216.DynamicTableName = false;
            this.cmdRT20216.EEPAlias = null;
            this.cmdRT20216.EncodingAfter = null;
            this.cmdRT20216.EncodingBefore = "Windows-1252";
            this.cmdRT20216.EncodingConvert = null;
            this.cmdRT20216.InfoConnection = this.InfoConnection1;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter16.ParameterName = "comq1";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 0;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            infoParameter17.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter17.ParameterName = "lineq1";
            infoParameter17.Precision = ((byte)(0));
            infoParameter17.Scale = ((byte)(0));
            infoParameter17.Size = 0;
            infoParameter17.SourceColumn = null;
            infoParameter17.XmlSchemaCollectionDatabase = null;
            infoParameter17.XmlSchemaCollectionName = null;
            infoParameter17.XmlSchemaCollectionOwningSchema = null;
            infoParameter18.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter18.ParameterName = "faqno";
            infoParameter18.Precision = ((byte)(0));
            infoParameter18.Scale = ((byte)(0));
            infoParameter18.Size = 13;
            infoParameter18.SourceColumn = null;
            infoParameter18.XmlSchemaCollectionDatabase = null;
            infoParameter18.XmlSchemaCollectionName = null;
            infoParameter18.XmlSchemaCollectionOwningSchema = null;
            infoParameter19.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter19.ParameterName = "prtno";
            infoParameter19.Precision = ((byte)(0));
            infoParameter19.Scale = ((byte)(0));
            infoParameter19.Size = 13;
            infoParameter19.SourceColumn = null;
            infoParameter19.XmlSchemaCollectionDatabase = null;
            infoParameter19.XmlSchemaCollectionName = null;
            infoParameter19.XmlSchemaCollectionOwningSchema = null;
            infoParameter20.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter20.ParameterName = "usr";
            infoParameter20.Precision = ((byte)(0));
            infoParameter20.Scale = ((byte)(0));
            infoParameter20.Size = 6;
            infoParameter20.SourceColumn = null;
            infoParameter20.XmlSchemaCollectionDatabase = null;
            infoParameter20.XmlSchemaCollectionName = null;
            infoParameter20.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20216.InfoParameters.Add(infoParameter16);
            this.cmdRT20216.InfoParameters.Add(infoParameter17);
            this.cmdRT20216.InfoParameters.Add(infoParameter18);
            this.cmdRT20216.InfoParameters.Add(infoParameter19);
            this.cmdRT20216.InfoParameters.Add(infoParameter20);
            this.cmdRT20216.MultiSetWhere = false;
            this.cmdRT20216.Name = "cmdRT20216";
            this.cmdRT20216.NotificationAutoEnlist = false;
            this.cmdRT20216.SecExcept = null;
            this.cmdRT20216.SecFieldName = null;
            this.cmdRT20216.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20216.SelectPaging = false;
            this.cmdRT20216.SelectTop = 0;
            this.cmdRT20216.SiteControl = false;
            this.cmdRT20216.SiteFieldName = null;
            this.cmdRT20216.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT20217
            // 
            this.cmdRT20217.CacheConnection = false;
            this.cmdRT20217.CommandText = "usp_RTLessorAVSCmtylineFaqSndworkDropC";
            this.cmdRT20217.CommandTimeout = 30;
            this.cmdRT20217.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT20217.DynamicTableName = false;
            this.cmdRT20217.EEPAlias = null;
            this.cmdRT20217.EncodingAfter = null;
            this.cmdRT20217.EncodingBefore = "Windows-1252";
            this.cmdRT20217.EncodingConvert = null;
            this.cmdRT20217.InfoConnection = this.InfoConnection1;
            infoParameter21.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter21.ParameterName = "comq1";
            infoParameter21.Precision = ((byte)(0));
            infoParameter21.Scale = ((byte)(0));
            infoParameter21.Size = 0;
            infoParameter21.SourceColumn = null;
            infoParameter21.XmlSchemaCollectionDatabase = null;
            infoParameter21.XmlSchemaCollectionName = null;
            infoParameter21.XmlSchemaCollectionOwningSchema = null;
            infoParameter22.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter22.ParameterName = "lineq1";
            infoParameter22.Precision = ((byte)(0));
            infoParameter22.Scale = ((byte)(0));
            infoParameter22.Size = 0;
            infoParameter22.SourceColumn = null;
            infoParameter22.XmlSchemaCollectionDatabase = null;
            infoParameter22.XmlSchemaCollectionName = null;
            infoParameter22.XmlSchemaCollectionOwningSchema = null;
            infoParameter23.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter23.ParameterName = "faqno";
            infoParameter23.Precision = ((byte)(0));
            infoParameter23.Scale = ((byte)(0));
            infoParameter23.Size = 13;
            infoParameter23.SourceColumn = null;
            infoParameter23.XmlSchemaCollectionDatabase = null;
            infoParameter23.XmlSchemaCollectionName = null;
            infoParameter23.XmlSchemaCollectionOwningSchema = null;
            infoParameter24.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter24.ParameterName = "prtno";
            infoParameter24.Precision = ((byte)(0));
            infoParameter24.Scale = ((byte)(0));
            infoParameter24.Size = 13;
            infoParameter24.SourceColumn = null;
            infoParameter24.XmlSchemaCollectionDatabase = null;
            infoParameter24.XmlSchemaCollectionName = null;
            infoParameter24.XmlSchemaCollectionOwningSchema = null;
            infoParameter25.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter25.ParameterName = "usr";
            infoParameter25.Precision = ((byte)(0));
            infoParameter25.Scale = ((byte)(0));
            infoParameter25.Size = 6;
            infoParameter25.SourceColumn = null;
            infoParameter25.XmlSchemaCollectionDatabase = null;
            infoParameter25.XmlSchemaCollectionName = null;
            infoParameter25.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT20217.InfoParameters.Add(infoParameter21);
            this.cmdRT20217.InfoParameters.Add(infoParameter22);
            this.cmdRT20217.InfoParameters.Add(infoParameter23);
            this.cmdRT20217.InfoParameters.Add(infoParameter24);
            this.cmdRT20217.InfoParameters.Add(infoParameter25);
            this.cmdRT20217.MultiSetWhere = false;
            this.cmdRT20217.Name = "cmdRT20217";
            this.cmdRT20217.NotificationAutoEnlist = false;
            this.cmdRT20217.SecExcept = null;
            this.cmdRT20217.SecFieldName = null;
            this.cmdRT20217.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT20217.SelectPaging = false;
            this.cmdRT20217.SelectTop = 0;
            this.cmdRT20217.SiteControl = false;
            this.cmdRT20217.SiteFieldName = null;
            this.cmdRT20217.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmd
            // 
            this.cmd.CacheConnection = false;
            this.cmd.CommandText = "";
            this.cmd.CommandTimeout = 30;
            this.cmd.CommandType = System.Data.CommandType.Text;
            this.cmd.DynamicTableName = false;
            this.cmd.EEPAlias = null;
            this.cmd.EncodingAfter = null;
            this.cmd.EncodingBefore = "Windows-1252";
            this.cmd.EncodingConvert = null;
            this.cmd.InfoConnection = this.InfoConnection1;
            this.cmd.MultiSetWhere = false;
            this.cmd.Name = "cmd";
            this.cmd.NotificationAutoEnlist = false;
            this.cmd.SecExcept = null;
            this.cmd.SecFieldName = null;
            this.cmd.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmd.SelectPaging = false;
            this.cmd.SelectTop = 0;
            this.cmd.SiteControl = false;
            this.cmd.SiteFieldName = null;
            this.cmd.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT20211
            // 
            this.RT20211.CacheConnection = false;
            this.RT20211.CommandText = resources.GetString("RT20211.CommandText");
            this.RT20211.CommandTimeout = 30;
            this.RT20211.CommandType = System.Data.CommandType.Text;
            this.RT20211.DynamicTableName = false;
            this.RT20211.EEPAlias = null;
            this.RT20211.EncodingAfter = null;
            this.RT20211.EncodingBefore = "Windows-1252";
            this.RT20211.EncodingConvert = null;
            this.RT20211.InfoConnection = this.InfoConnection1;
            keyItem9.KeyName = "comq1";
            keyItem10.KeyName = "lineq1";
            keyItem11.KeyName = "FAQNO";
            keyItem12.KeyName = "entryno";
            this.RT20211.KeyFields.Add(keyItem9);
            this.RT20211.KeyFields.Add(keyItem10);
            this.RT20211.KeyFields.Add(keyItem11);
            this.RT20211.KeyFields.Add(keyItem12);
            this.RT20211.MultiSetWhere = false;
            this.RT20211.Name = "RT20211";
            this.RT20211.NotificationAutoEnlist = false;
            this.RT20211.SecExcept = null;
            this.RT20211.SecFieldName = null;
            this.RT20211.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT20211.SelectPaging = false;
            this.RT20211.SelectTop = 0;
            this.RT20211.SiteControl = false;
            this.RT20211.SiteFieldName = null;
            this.RT20211.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT20219
            // 
            this.RT20219.CacheConnection = false;
            this.RT20219.CommandText = resources.GetString("RT20219.CommandText");
            this.RT20219.CommandTimeout = 30;
            this.RT20219.CommandType = System.Data.CommandType.Text;
            this.RT20219.DynamicTableName = false;
            this.RT20219.EEPAlias = null;
            this.RT20219.EncodingAfter = null;
            this.RT20219.EncodingBefore = "Windows-1252";
            this.RT20219.EncodingConvert = null;
            this.RT20219.InfoConnection = this.InfoConnection1;
            keyItem13.KeyName = "comq1";
            keyItem14.KeyName = "lineq1";
            keyItem15.KeyName = "FAQNO";
            keyItem16.KeyName = "entryno";
            this.RT20219.KeyFields.Add(keyItem13);
            this.RT20219.KeyFields.Add(keyItem14);
            this.RT20219.KeyFields.Add(keyItem15);
            this.RT20219.KeyFields.Add(keyItem16);
            this.RT20219.MultiSetWhere = false;
            this.RT20219.Name = "RT20219";
            this.RT20219.NotificationAutoEnlist = false;
            this.RT20219.SecExcept = null;
            this.RT20219.SecFieldName = null;
            this.RT20219.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT20219.SelectPaging = false;
            this.RT20219.SelectTop = 0;
            this.RT20219.SiteControl = false;
            this.RT20219.SiteFieldName = null;
            this.RT20219.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineFaqSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCmtyLineFaqSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20213)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20214)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20215)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20216)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT20217)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20211)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT20219)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyLineFaqSndwork;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyLineFaqSndwork;
        private Srvtools.InfoCommand View_RTLessorAVSCmtyLineFaqSndwork;
        private Srvtools.InfoCommand cmdRT20213;
        private Srvtools.InfoCommand cmdRT20214;
        private Srvtools.InfoCommand cmdRT20215;
        private Srvtools.InfoCommand cmdRT20216;
        private Srvtools.InfoCommand cmdRT20217;
        private Srvtools.InfoCommand cmd;
        private Srvtools.InfoCommand RT20211;
        private Srvtools.InfoCommand RT20219;
    }
}
