namespace sRT203
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyLineSNDWORK = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyLineSNDWORK = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorCmtyLineSndwork = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineSNDWORK)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorCmtyLineSndwork)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyLineSNDWORK
            // 
            this.RTLessorAVSCmtyLineSNDWORK.CacheConnection = false;
            this.RTLessorAVSCmtyLineSNDWORK.CommandText = resources.GetString("RTLessorAVSCmtyLineSNDWORK.CommandText");
            this.RTLessorAVSCmtyLineSNDWORK.CommandTimeout = 30;
            this.RTLessorAVSCmtyLineSNDWORK.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyLineSNDWORK.DynamicTableName = false;
            this.RTLessorAVSCmtyLineSNDWORK.EEPAlias = null;
            this.RTLessorAVSCmtyLineSNDWORK.EncodingAfter = null;
            this.RTLessorAVSCmtyLineSNDWORK.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyLineSNDWORK.EncodingConvert = null;
            this.RTLessorAVSCmtyLineSNDWORK.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "LINEQ1";
            keyItem3.KeyName = "PRTNO";
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem3);
            this.RTLessorAVSCmtyLineSNDWORK.MultiSetWhere = false;
            this.RTLessorAVSCmtyLineSNDWORK.Name = "RTLessorAVSCmtyLineSNDWORK";
            this.RTLessorAVSCmtyLineSNDWORK.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyLineSNDWORK.SecExcept = null;
            this.RTLessorAVSCmtyLineSNDWORK.SecFieldName = null;
            this.RTLessorAVSCmtyLineSNDWORK.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyLineSNDWORK.SelectPaging = false;
            this.RTLessorAVSCmtyLineSNDWORK.SelectTop = 0;
            this.RTLessorAVSCmtyLineSNDWORK.SiteControl = false;
            this.RTLessorAVSCmtyLineSNDWORK.SiteFieldName = null;
            this.RTLessorAVSCmtyLineSNDWORK.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyLineSNDWORK
            // 
            this.ucRTLessorAVSCmtyLineSNDWORK.AutoTrans = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "LINEQ1";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PRTNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SENDWORKDAT";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "PRTUSR";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ASSIGNENGINEER";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "ASSIGNCONSIGNEE";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "REALENGINEER";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "REALCONSIGNEE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "DROPDAT";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "DROPDESC";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CLOSEDAT";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "BONUSCLOSEYM";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "BONUSCLOSEDAT";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "BONUSCLOSEUSR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "BONUSFINCHK";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "STOCKCLOSEYM";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "STOCKCLOSEDAT";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "STOCKCLOSEUSR";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "STOCKFINCHK";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "MDF1";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "MDF2";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "HOSTNO";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "HOSTPORT";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "MEMO";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PRTDAT";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "UNCLOSEDAT";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "DROPUSR";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "CLOSEUSR";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "EUSR";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "EDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "UUSR";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "UDAT";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "BATCHNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CDAT";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "MAXENTRYNO";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "SNDKIND";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "EQUIPSETUPDAT";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "ADSLAPPLYDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "QTHW";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "QTTR";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "QTTK";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "QTNT";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCmtyLineSNDWORK.LogInfo = null;
            this.ucRTLessorAVSCmtyLineSNDWORK.Name = "ucRTLessorAVSCmtyLineSNDWORK";
            this.ucRTLessorAVSCmtyLineSNDWORK.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.SelectCmd = this.RTLessorAVSCmtyLineSNDWORK;
            this.ucRTLessorAVSCmtyLineSNDWORK.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyLineSNDWORK.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ServerModify = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyLineSNDWORK.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyLineSNDWORK.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyLineSNDWORK.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyLineSNDWORK.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorCmtyLineSndwork
            // 
            this.View_RTLessorCmtyLineSndwork.CacheConnection = false;
            this.View_RTLessorCmtyLineSndwork.CommandText = "SELECT * FROM dbo.[RTLessorCmtyLineSndwork]";
            this.View_RTLessorCmtyLineSndwork.CommandTimeout = 30;
            this.View_RTLessorCmtyLineSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorCmtyLineSndwork.DynamicTableName = false;
            this.View_RTLessorCmtyLineSndwork.EEPAlias = null;
            this.View_RTLessorCmtyLineSndwork.EncodingAfter = null;
            this.View_RTLessorCmtyLineSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorCmtyLineSndwork.EncodingConvert = null;
            this.View_RTLessorCmtyLineSndwork.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "COMQ1";
            keyItem5.KeyName = "LINEQ1";
            keyItem6.KeyName = "PRTNO";
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem4);
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem5);
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem6);
            this.View_RTLessorCmtyLineSndwork.MultiSetWhere = false;
            this.View_RTLessorCmtyLineSndwork.Name = "View_RTLessorCmtyLineSndwork";
            this.View_RTLessorCmtyLineSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorCmtyLineSndwork.SecExcept = null;
            this.View_RTLessorCmtyLineSndwork.SecFieldName = null;
            this.View_RTLessorCmtyLineSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorCmtyLineSndwork.SelectPaging = false;
            this.View_RTLessorCmtyLineSndwork.SelectTop = 0;
            this.View_RTLessorCmtyLineSndwork.SiteControl = false;
            this.View_RTLessorCmtyLineSndwork.SiteFieldName = null;
            this.View_RTLessorCmtyLineSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineSNDWORK)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorCmtyLineSndwork)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyLineSNDWORK;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyLineSNDWORK;
        private Srvtools.InfoCommand View_RTLessorCmtyLineSndwork;
    }
}
