namespace sRT203
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter17 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter18 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter19 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter20 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter21 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter22 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter23 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter24 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter25 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter26 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter27 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter28 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter29 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter30 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter31 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter32 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter33 = new Srvtools.InfoParameter();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCmtyLineSNDWORK = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCmtyLineSNDWORK = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorCmtyLineSndwork = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.RT2032 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2031 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2032 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2033 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2035 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2034 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2036 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2037 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2038 = new Srvtools.InfoCommand(this.components);
            this.cmdRT2039 = new Srvtools.InfoCommand(this.components);
            this.cmd = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineSNDWORK)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorCmtyLineSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT2032)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2031)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2032)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2033)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2035)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2034)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2036)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2037)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2038)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2039)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT2031";
            service1.NonLogin = false;
            service1.ServiceName = "smRT2031";
            service2.DelegateName = "smRT2032";
            service2.NonLogin = false;
            service2.ServiceName = "smRT2032";
            service3.DelegateName = "smRT2033";
            service3.NonLogin = false;
            service3.ServiceName = "smRT2033";
            service4.DelegateName = "smRT2034";
            service4.NonLogin = false;
            service4.ServiceName = "smRT2034";
            service5.DelegateName = "smRT2035";
            service5.NonLogin = false;
            service5.ServiceName = "smRT2035";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCmtyLineSNDWORK
            // 
            this.RTLessorAVSCmtyLineSNDWORK.CacheConnection = false;
            this.RTLessorAVSCmtyLineSNDWORK.CommandText = resources.GetString("RTLessorAVSCmtyLineSNDWORK.CommandText");
            this.RTLessorAVSCmtyLineSNDWORK.CommandTimeout = 30;
            this.RTLessorAVSCmtyLineSNDWORK.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCmtyLineSNDWORK.DynamicTableName = false;
            this.RTLessorAVSCmtyLineSNDWORK.EEPAlias = null;
            this.RTLessorAVSCmtyLineSNDWORK.EncodingAfter = null;
            this.RTLessorAVSCmtyLineSNDWORK.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCmtyLineSNDWORK.EncodingConvert = null;
            this.RTLessorAVSCmtyLineSNDWORK.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "COMQ1";
            keyItem2.KeyName = "LINEQ1";
            keyItem3.KeyName = "PRTNO";
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem1);
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem2);
            this.RTLessorAVSCmtyLineSNDWORK.KeyFields.Add(keyItem3);
            this.RTLessorAVSCmtyLineSNDWORK.MultiSetWhere = false;
            this.RTLessorAVSCmtyLineSNDWORK.Name = "RTLessorAVSCmtyLineSNDWORK";
            this.RTLessorAVSCmtyLineSNDWORK.NotificationAutoEnlist = false;
            this.RTLessorAVSCmtyLineSNDWORK.SecExcept = null;
            this.RTLessorAVSCmtyLineSNDWORK.SecFieldName = null;
            this.RTLessorAVSCmtyLineSNDWORK.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCmtyLineSNDWORK.SelectPaging = false;
            this.RTLessorAVSCmtyLineSNDWORK.SelectTop = 0;
            this.RTLessorAVSCmtyLineSNDWORK.SiteControl = false;
            this.RTLessorAVSCmtyLineSNDWORK.SiteFieldName = null;
            this.RTLessorAVSCmtyLineSNDWORK.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCmtyLineSNDWORK
            // 
            this.ucRTLessorAVSCmtyLineSNDWORK.AutoTrans = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "COMQ1";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "LINEQ1";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "PRTNO";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "SENDWORKDAT";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "PRTUSR";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ASSIGNENGINEER";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "ASSIGNCONSIGNEE";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "REALENGINEER";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "REALCONSIGNEE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "DROPDAT";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "DROPDESC";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "CLOSEDAT";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "BONUSCLOSEYM";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "BONUSCLOSEDAT";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "BONUSCLOSEUSR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "BONUSFINCHK";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "STOCKCLOSEYM";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "STOCKCLOSEDAT";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "STOCKCLOSEUSR";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "STOCKFINCHK";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "MDF1";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "MDF2";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "HOSTNO";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "HOSTPORT";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "MEMO";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PRTDAT";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "UNCLOSEDAT";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "DROPUSR";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "CLOSEUSR";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "EUSR";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "EDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "UUSR";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "UDAT";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "BATCHNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "CDAT";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "MAXENTRYNO";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "SNDKIND";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "EQUIPSETUPDAT";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "ADSLAPPLYDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "QTHW";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "QTTR";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "QTTK";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "QTNT";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCmtyLineSNDWORK.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCmtyLineSNDWORK.LogInfo = null;
            this.ucRTLessorAVSCmtyLineSNDWORK.Name = "ucRTLessorAVSCmtyLineSNDWORK";
            this.ucRTLessorAVSCmtyLineSNDWORK.RowAffectsCheck = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.SelectCmd = this.RTLessorAVSCmtyLineSNDWORK;
            this.ucRTLessorAVSCmtyLineSNDWORK.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCmtyLineSNDWORK.SendSQLCmd = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ServerModify = true;
            this.ucRTLessorAVSCmtyLineSNDWORK.ServerModifyGetMax = false;
            this.ucRTLessorAVSCmtyLineSNDWORK.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCmtyLineSNDWORK.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCmtyLineSNDWORK.UseTranscationScope = false;
            this.ucRTLessorAVSCmtyLineSNDWORK.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorCmtyLineSndwork
            // 
            this.View_RTLessorCmtyLineSndwork.CacheConnection = false;
            this.View_RTLessorCmtyLineSndwork.CommandText = "SELECT * FROM dbo.[RTLessorCmtyLineSndwork]";
            this.View_RTLessorCmtyLineSndwork.CommandTimeout = 30;
            this.View_RTLessorCmtyLineSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorCmtyLineSndwork.DynamicTableName = false;
            this.View_RTLessorCmtyLineSndwork.EEPAlias = null;
            this.View_RTLessorCmtyLineSndwork.EncodingAfter = null;
            this.View_RTLessorCmtyLineSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorCmtyLineSndwork.EncodingConvert = null;
            this.View_RTLessorCmtyLineSndwork.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "COMQ1";
            keyItem5.KeyName = "LINEQ1";
            keyItem6.KeyName = "PRTNO";
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem4);
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem5);
            this.View_RTLessorCmtyLineSndwork.KeyFields.Add(keyItem6);
            this.View_RTLessorCmtyLineSndwork.MultiSetWhere = false;
            this.View_RTLessorCmtyLineSndwork.Name = "View_RTLessorCmtyLineSndwork";
            this.View_RTLessorCmtyLineSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorCmtyLineSndwork.SecExcept = null;
            this.View_RTLessorCmtyLineSndwork.SecFieldName = null;
            this.View_RTLessorCmtyLineSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorCmtyLineSndwork.SelectPaging = false;
            this.View_RTLessorCmtyLineSndwork.SelectTop = 0;
            this.View_RTLessorCmtyLineSndwork.SiteControl = false;
            this.View_RTLessorCmtyLineSndwork.SiteFieldName = null;
            this.View_RTLessorCmtyLineSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "RT203";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "getFix()";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 2;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "PRTNO";
            this.autoNumber1.UpdateComp = this.ucRTLessorAVSCmtyLineSNDWORK;
            // 
            // RT2032
            // 
            this.RT2032.CacheConnection = false;
            this.RT2032.CommandText = resources.GetString("RT2032.CommandText");
            this.RT2032.CommandTimeout = 30;
            this.RT2032.CommandType = System.Data.CommandType.Text;
            this.RT2032.DynamicTableName = false;
            this.RT2032.EEPAlias = null;
            this.RT2032.EncodingAfter = null;
            this.RT2032.EncodingBefore = "Windows-1252";
            this.RT2032.EncodingConvert = null;
            this.RT2032.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "comq1";
            keyItem8.KeyName = "lineq1";
            keyItem9.KeyName = "PRTNO";
            keyItem10.KeyName = "ENTRYNO";
            keyItem11.KeyName = "PRTNO1";
            keyItem12.KeyName = "ENTRYNO1";
            this.RT2032.KeyFields.Add(keyItem7);
            this.RT2032.KeyFields.Add(keyItem8);
            this.RT2032.KeyFields.Add(keyItem9);
            this.RT2032.KeyFields.Add(keyItem10);
            this.RT2032.KeyFields.Add(keyItem11);
            this.RT2032.KeyFields.Add(keyItem12);
            this.RT2032.MultiSetWhere = false;
            this.RT2032.Name = "RT2032";
            this.RT2032.NotificationAutoEnlist = false;
            this.RT2032.SecExcept = null;
            this.RT2032.SecFieldName = null;
            this.RT2032.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT2032.SelectPaging = false;
            this.RT2032.SelectTop = 0;
            this.RT2032.SiteControl = false;
            this.RT2032.SiteFieldName = null;
            this.RT2032.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2031
            // 
            this.cmdRT2031.CacheConnection = false;
            this.cmdRT2031.CommandText = "usp_RTLessorAVScmtylineSndworkF";
            this.cmdRT2031.CommandTimeout = 30;
            this.cmdRT2031.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2031.DynamicTableName = false;
            this.cmdRT2031.EEPAlias = null;
            this.cmdRT2031.EncodingAfter = null;
            this.cmdRT2031.EncodingBefore = "Windows-1252";
            this.cmdRT2031.EncodingConvert = null;
            this.cmdRT2031.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter1.ParameterName = "comq1";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 0;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "lineq1";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "prtno";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 12;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "usr";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 6;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2031.InfoParameters.Add(infoParameter1);
            this.cmdRT2031.InfoParameters.Add(infoParameter2);
            this.cmdRT2031.InfoParameters.Add(infoParameter3);
            this.cmdRT2031.InfoParameters.Add(infoParameter4);
            this.cmdRT2031.MultiSetWhere = false;
            this.cmdRT2031.Name = "cmdRT2031";
            this.cmdRT2031.NotificationAutoEnlist = false;
            this.cmdRT2031.SecExcept = null;
            this.cmdRT2031.SecFieldName = null;
            this.cmdRT2031.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2031.SelectPaging = false;
            this.cmdRT2031.SelectTop = 0;
            this.cmdRT2031.SiteControl = false;
            this.cmdRT2031.SiteFieldName = null;
            this.cmdRT2031.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2032
            // 
            this.cmdRT2032.CacheConnection = false;
            this.cmdRT2032.CommandText = "usp_RTLessorAVSCmtyLineSndworkUF";
            this.cmdRT2032.CommandTimeout = 30;
            this.cmdRT2032.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2032.DynamicTableName = false;
            this.cmdRT2032.EEPAlias = null;
            this.cmdRT2032.EncodingAfter = null;
            this.cmdRT2032.EncodingBefore = "Windows-1252";
            this.cmdRT2032.EncodingConvert = null;
            this.cmdRT2032.InfoConnection = this.InfoConnection1;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter5.ParameterName = "comq1";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 0;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter6.ParameterName = "lineq1";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 0;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter7.ParameterName = "prtno";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 12;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "usr";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 6;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2032.InfoParameters.Add(infoParameter5);
            this.cmdRT2032.InfoParameters.Add(infoParameter6);
            this.cmdRT2032.InfoParameters.Add(infoParameter7);
            this.cmdRT2032.InfoParameters.Add(infoParameter8);
            this.cmdRT2032.MultiSetWhere = false;
            this.cmdRT2032.Name = "cmdRT2032";
            this.cmdRT2032.NotificationAutoEnlist = false;
            this.cmdRT2032.SecExcept = null;
            this.cmdRT2032.SecFieldName = null;
            this.cmdRT2032.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2032.SelectPaging = false;
            this.cmdRT2032.SelectTop = 0;
            this.cmdRT2032.SiteControl = false;
            this.cmdRT2032.SiteFieldName = null;
            this.cmdRT2032.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2033
            // 
            this.cmdRT2033.CacheConnection = false;
            this.cmdRT2033.CommandText = "usp_RTLessorAVSCmtylineSndworkFR";
            this.cmdRT2033.CommandTimeout = 30;
            this.cmdRT2033.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2033.DynamicTableName = false;
            this.cmdRT2033.EEPAlias = null;
            this.cmdRT2033.EncodingAfter = null;
            this.cmdRT2033.EncodingBefore = "Windows-1252";
            this.cmdRT2033.EncodingConvert = null;
            this.cmdRT2033.InfoConnection = this.InfoConnection1;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter9.ParameterName = "comq1";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 0;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter10.ParameterName = "lineq1";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 0;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "prtno";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 12;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter12.ParameterName = "usr";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 6;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2033.InfoParameters.Add(infoParameter9);
            this.cmdRT2033.InfoParameters.Add(infoParameter10);
            this.cmdRT2033.InfoParameters.Add(infoParameter11);
            this.cmdRT2033.InfoParameters.Add(infoParameter12);
            this.cmdRT2033.MultiSetWhere = false;
            this.cmdRT2033.Name = "cmdRT2033";
            this.cmdRT2033.NotificationAutoEnlist = false;
            this.cmdRT2033.SecExcept = null;
            this.cmdRT2033.SecFieldName = null;
            this.cmdRT2033.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2033.SelectPaging = false;
            this.cmdRT2033.SelectTop = 0;
            this.cmdRT2033.SiteControl = false;
            this.cmdRT2033.SiteFieldName = null;
            this.cmdRT2033.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2035
            // 
            this.cmdRT2035.CacheConnection = false;
            this.cmdRT2035.CommandText = "usp_RTLessorAVScmtylineSndworkDropc";
            this.cmdRT2035.CommandTimeout = 30;
            this.cmdRT2035.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2035.DynamicTableName = false;
            this.cmdRT2035.EEPAlias = null;
            this.cmdRT2035.EncodingAfter = null;
            this.cmdRT2035.EncodingBefore = "Windows-1252";
            this.cmdRT2035.EncodingConvert = null;
            this.cmdRT2035.InfoConnection = this.InfoConnection1;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter13.ParameterName = "comq1";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 0;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter14.ParameterName = "lineq1";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 0;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter15.ParameterName = "prtno";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 12;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter16.ParameterName = "usr";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 6;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2035.InfoParameters.Add(infoParameter13);
            this.cmdRT2035.InfoParameters.Add(infoParameter14);
            this.cmdRT2035.InfoParameters.Add(infoParameter15);
            this.cmdRT2035.InfoParameters.Add(infoParameter16);
            this.cmdRT2035.MultiSetWhere = false;
            this.cmdRT2035.Name = "cmdRT2035";
            this.cmdRT2035.NotificationAutoEnlist = false;
            this.cmdRT2035.SecExcept = null;
            this.cmdRT2035.SecFieldName = null;
            this.cmdRT2035.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2035.SelectPaging = false;
            this.cmdRT2035.SelectTop = 0;
            this.cmdRT2035.SiteControl = false;
            this.cmdRT2035.SiteFieldName = null;
            this.cmdRT2035.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2034
            // 
            this.cmdRT2034.CacheConnection = false;
            this.cmdRT2034.CommandText = "usp_RTLessorAVScmtylineSndworkDrop";
            this.cmdRT2034.CommandTimeout = 30;
            this.cmdRT2034.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2034.DynamicTableName = false;
            this.cmdRT2034.EEPAlias = null;
            this.cmdRT2034.EncodingAfter = null;
            this.cmdRT2034.EncodingBefore = "Windows-1252";
            this.cmdRT2034.EncodingConvert = null;
            this.cmdRT2034.InfoConnection = this.InfoConnection1;
            infoParameter17.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter17.ParameterName = "comq1";
            infoParameter17.Precision = ((byte)(0));
            infoParameter17.Scale = ((byte)(0));
            infoParameter17.Size = 0;
            infoParameter17.SourceColumn = null;
            infoParameter17.XmlSchemaCollectionDatabase = null;
            infoParameter17.XmlSchemaCollectionName = null;
            infoParameter17.XmlSchemaCollectionOwningSchema = null;
            infoParameter18.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter18.ParameterName = "lineq1";
            infoParameter18.Precision = ((byte)(0));
            infoParameter18.Scale = ((byte)(0));
            infoParameter18.Size = 0;
            infoParameter18.SourceColumn = null;
            infoParameter18.XmlSchemaCollectionDatabase = null;
            infoParameter18.XmlSchemaCollectionName = null;
            infoParameter18.XmlSchemaCollectionOwningSchema = null;
            infoParameter19.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter19.ParameterName = "prtno";
            infoParameter19.Precision = ((byte)(0));
            infoParameter19.Scale = ((byte)(0));
            infoParameter19.Size = 12;
            infoParameter19.SourceColumn = null;
            infoParameter19.XmlSchemaCollectionDatabase = null;
            infoParameter19.XmlSchemaCollectionName = null;
            infoParameter19.XmlSchemaCollectionOwningSchema = null;
            infoParameter20.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter20.ParameterName = "usr";
            infoParameter20.Precision = ((byte)(0));
            infoParameter20.Scale = ((byte)(0));
            infoParameter20.Size = 6;
            infoParameter20.SourceColumn = null;
            infoParameter20.XmlSchemaCollectionDatabase = null;
            infoParameter20.XmlSchemaCollectionName = null;
            infoParameter20.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2034.InfoParameters.Add(infoParameter17);
            this.cmdRT2034.InfoParameters.Add(infoParameter18);
            this.cmdRT2034.InfoParameters.Add(infoParameter19);
            this.cmdRT2034.InfoParameters.Add(infoParameter20);
            this.cmdRT2034.MultiSetWhere = false;
            this.cmdRT2034.Name = "cmdRT2034";
            this.cmdRT2034.NotificationAutoEnlist = false;
            this.cmdRT2034.SecExcept = null;
            this.cmdRT2034.SecFieldName = null;
            this.cmdRT2034.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2034.SelectPaging = false;
            this.cmdRT2034.SelectTop = 0;
            this.cmdRT2034.SiteControl = false;
            this.cmdRT2034.SiteFieldName = null;
            this.cmdRT2034.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2036
            // 
            this.cmdRT2036.CacheConnection = false;
            this.cmdRT2036.CommandText = "usp_RTLessorAVSCustDROPF";
            this.cmdRT2036.CommandTimeout = 30;
            this.cmdRT2036.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2036.DynamicTableName = false;
            this.cmdRT2036.EEPAlias = null;
            this.cmdRT2036.EncodingAfter = null;
            this.cmdRT2036.EncodingBefore = "Windows-1252";
            this.cmdRT2036.EncodingConvert = null;
            this.cmdRT2036.InfoConnection = this.InfoConnection1;
            infoParameter21.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter21.ParameterName = "cusid";
            infoParameter21.Precision = ((byte)(0));
            infoParameter21.Scale = ((byte)(0));
            infoParameter21.Size = 15;
            infoParameter21.SourceColumn = null;
            infoParameter21.XmlSchemaCollectionDatabase = null;
            infoParameter21.XmlSchemaCollectionName = null;
            infoParameter21.XmlSchemaCollectionOwningSchema = null;
            infoParameter22.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter22.ParameterName = "entryno";
            infoParameter22.Precision = ((byte)(0));
            infoParameter22.Scale = ((byte)(0));
            infoParameter22.Size = 0;
            infoParameter22.SourceColumn = null;
            infoParameter22.XmlSchemaCollectionDatabase = null;
            infoParameter22.XmlSchemaCollectionName = null;
            infoParameter22.XmlSchemaCollectionOwningSchema = null;
            infoParameter23.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter23.ParameterName = "usr";
            infoParameter23.Precision = ((byte)(0));
            infoParameter23.Scale = ((byte)(0));
            infoParameter23.Size = 6;
            infoParameter23.SourceColumn = null;
            infoParameter23.XmlSchemaCollectionDatabase = null;
            infoParameter23.XmlSchemaCollectionName = null;
            infoParameter23.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2036.InfoParameters.Add(infoParameter21);
            this.cmdRT2036.InfoParameters.Add(infoParameter22);
            this.cmdRT2036.InfoParameters.Add(infoParameter23);
            this.cmdRT2036.MultiSetWhere = false;
            this.cmdRT2036.Name = "cmdRT2036";
            this.cmdRT2036.NotificationAutoEnlist = false;
            this.cmdRT2036.SecExcept = null;
            this.cmdRT2036.SecFieldName = null;
            this.cmdRT2036.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2036.SelectPaging = false;
            this.cmdRT2036.SelectTop = 0;
            this.cmdRT2036.SiteControl = false;
            this.cmdRT2036.SiteFieldName = null;
            this.cmdRT2036.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2037
            // 
            this.cmdRT2037.CacheConnection = false;
            this.cmdRT2037.CommandText = "usp_RTLessorAVSCustDROPFR";
            this.cmdRT2037.CommandTimeout = 30;
            this.cmdRT2037.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2037.DynamicTableName = false;
            this.cmdRT2037.EEPAlias = null;
            this.cmdRT2037.EncodingAfter = null;
            this.cmdRT2037.EncodingBefore = "Windows-1252";
            this.cmdRT2037.EncodingConvert = null;
            this.cmdRT2037.InfoConnection = this.InfoConnection1;
            infoParameter24.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter24.ParameterName = "cusid";
            infoParameter24.Precision = ((byte)(0));
            infoParameter24.Scale = ((byte)(0));
            infoParameter24.Size = 15;
            infoParameter24.SourceColumn = null;
            infoParameter24.XmlSchemaCollectionDatabase = null;
            infoParameter24.XmlSchemaCollectionName = null;
            infoParameter24.XmlSchemaCollectionOwningSchema = null;
            infoParameter25.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter25.ParameterName = "entryno";
            infoParameter25.Precision = ((byte)(0));
            infoParameter25.Scale = ((byte)(0));
            infoParameter25.Size = 0;
            infoParameter25.SourceColumn = null;
            infoParameter25.XmlSchemaCollectionDatabase = null;
            infoParameter25.XmlSchemaCollectionName = null;
            infoParameter25.XmlSchemaCollectionOwningSchema = null;
            infoParameter26.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter26.ParameterName = "usr";
            infoParameter26.Precision = ((byte)(0));
            infoParameter26.Scale = ((byte)(0));
            infoParameter26.Size = 6;
            infoParameter26.SourceColumn = null;
            infoParameter26.XmlSchemaCollectionDatabase = null;
            infoParameter26.XmlSchemaCollectionName = null;
            infoParameter26.XmlSchemaCollectionOwningSchema = null;
            infoParameter27.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter27.ParameterName = "batchnoxx";
            infoParameter27.Precision = ((byte)(0));
            infoParameter27.Scale = ((byte)(0));
            infoParameter27.Size = 12;
            infoParameter27.SourceColumn = null;
            infoParameter27.XmlSchemaCollectionDatabase = null;
            infoParameter27.XmlSchemaCollectionName = null;
            infoParameter27.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2037.InfoParameters.Add(infoParameter24);
            this.cmdRT2037.InfoParameters.Add(infoParameter25);
            this.cmdRT2037.InfoParameters.Add(infoParameter26);
            this.cmdRT2037.InfoParameters.Add(infoParameter27);
            this.cmdRT2037.MultiSetWhere = false;
            this.cmdRT2037.Name = "cmdRT2037";
            this.cmdRT2037.NotificationAutoEnlist = false;
            this.cmdRT2037.SecExcept = null;
            this.cmdRT2037.SecFieldName = null;
            this.cmdRT2037.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2037.SelectPaging = false;
            this.cmdRT2037.SelectTop = 0;
            this.cmdRT2037.SiteControl = false;
            this.cmdRT2037.SiteFieldName = null;
            this.cmdRT2037.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2038
            // 
            this.cmdRT2038.CacheConnection = false;
            this.cmdRT2038.CommandText = "usp_RTLessorAVSCustdropDrop";
            this.cmdRT2038.CommandTimeout = 30;
            this.cmdRT2038.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2038.DynamicTableName = false;
            this.cmdRT2038.EEPAlias = null;
            this.cmdRT2038.EncodingAfter = null;
            this.cmdRT2038.EncodingBefore = "Windows-1252";
            this.cmdRT2038.EncodingConvert = null;
            this.cmdRT2038.InfoConnection = this.InfoConnection1;
            infoParameter28.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter28.ParameterName = "cusid";
            infoParameter28.Precision = ((byte)(0));
            infoParameter28.Scale = ((byte)(0));
            infoParameter28.Size = 15;
            infoParameter28.SourceColumn = null;
            infoParameter28.XmlSchemaCollectionDatabase = null;
            infoParameter28.XmlSchemaCollectionName = null;
            infoParameter28.XmlSchemaCollectionOwningSchema = null;
            infoParameter29.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter29.ParameterName = "entryno";
            infoParameter29.Precision = ((byte)(0));
            infoParameter29.Scale = ((byte)(0));
            infoParameter29.Size = 0;
            infoParameter29.SourceColumn = null;
            infoParameter29.XmlSchemaCollectionDatabase = null;
            infoParameter29.XmlSchemaCollectionName = null;
            infoParameter29.XmlSchemaCollectionOwningSchema = null;
            infoParameter30.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter30.ParameterName = "usr";
            infoParameter30.Precision = ((byte)(0));
            infoParameter30.Scale = ((byte)(0));
            infoParameter30.Size = 6;
            infoParameter30.SourceColumn = null;
            infoParameter30.XmlSchemaCollectionDatabase = null;
            infoParameter30.XmlSchemaCollectionName = null;
            infoParameter30.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2038.InfoParameters.Add(infoParameter28);
            this.cmdRT2038.InfoParameters.Add(infoParameter29);
            this.cmdRT2038.InfoParameters.Add(infoParameter30);
            this.cmdRT2038.MultiSetWhere = false;
            this.cmdRT2038.Name = "cmdRT2038";
            this.cmdRT2038.NotificationAutoEnlist = false;
            this.cmdRT2038.SecExcept = null;
            this.cmdRT2038.SecFieldName = null;
            this.cmdRT2038.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2038.SelectPaging = false;
            this.cmdRT2038.SelectTop = 0;
            this.cmdRT2038.SiteControl = false;
            this.cmdRT2038.SiteFieldName = null;
            this.cmdRT2038.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT2039
            // 
            this.cmdRT2039.CacheConnection = false;
            this.cmdRT2039.CommandText = "usp_RTLessorAVSCustdropDropC";
            this.cmdRT2039.CommandTimeout = 30;
            this.cmdRT2039.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT2039.DynamicTableName = false;
            this.cmdRT2039.EEPAlias = null;
            this.cmdRT2039.EncodingAfter = null;
            this.cmdRT2039.EncodingBefore = "Windows-1252";
            this.cmdRT2039.EncodingConvert = null;
            this.cmdRT2039.InfoConnection = this.InfoConnection1;
            infoParameter31.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter31.ParameterName = "cusid";
            infoParameter31.Precision = ((byte)(0));
            infoParameter31.Scale = ((byte)(0));
            infoParameter31.Size = 15;
            infoParameter31.SourceColumn = null;
            infoParameter31.XmlSchemaCollectionDatabase = null;
            infoParameter31.XmlSchemaCollectionName = null;
            infoParameter31.XmlSchemaCollectionOwningSchema = null;
            infoParameter32.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter32.ParameterName = "entryno";
            infoParameter32.Precision = ((byte)(0));
            infoParameter32.Scale = ((byte)(0));
            infoParameter32.Size = 0;
            infoParameter32.SourceColumn = null;
            infoParameter32.XmlSchemaCollectionDatabase = null;
            infoParameter32.XmlSchemaCollectionName = null;
            infoParameter32.XmlSchemaCollectionOwningSchema = null;
            infoParameter33.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter33.ParameterName = "usr";
            infoParameter33.Precision = ((byte)(0));
            infoParameter33.Scale = ((byte)(0));
            infoParameter33.Size = 6;
            infoParameter33.SourceColumn = null;
            infoParameter33.XmlSchemaCollectionDatabase = null;
            infoParameter33.XmlSchemaCollectionName = null;
            infoParameter33.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT2039.InfoParameters.Add(infoParameter31);
            this.cmdRT2039.InfoParameters.Add(infoParameter32);
            this.cmdRT2039.InfoParameters.Add(infoParameter33);
            this.cmdRT2039.MultiSetWhere = false;
            this.cmdRT2039.Name = "cmdRT2039";
            this.cmdRT2039.NotificationAutoEnlist = false;
            this.cmdRT2039.SecExcept = null;
            this.cmdRT2039.SecFieldName = null;
            this.cmdRT2039.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT2039.SelectPaging = false;
            this.cmdRT2039.SelectTop = 0;
            this.cmdRT2039.SiteControl = false;
            this.cmdRT2039.SiteFieldName = null;
            this.cmdRT2039.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmd
            // 
            this.cmd.CacheConnection = false;
            this.cmd.CommandText = "";
            this.cmd.CommandTimeout = 30;
            this.cmd.CommandType = System.Data.CommandType.Text;
            this.cmd.DynamicTableName = false;
            this.cmd.EEPAlias = null;
            this.cmd.EncodingAfter = null;
            this.cmd.EncodingBefore = "Windows-1252";
            this.cmd.EncodingConvert = null;
            this.cmd.InfoConnection = this.InfoConnection1;
            this.cmd.MultiSetWhere = false;
            this.cmd.Name = "cmd";
            this.cmd.NotificationAutoEnlist = false;
            this.cmd.SecExcept = null;
            this.cmd.SecFieldName = null;
            this.cmd.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmd.SelectPaging = false;
            this.cmd.SelectTop = 0;
            this.cmd.SiteControl = false;
            this.cmd.SiteFieldName = null;
            this.cmd.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCmtyLineSNDWORK)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorCmtyLineSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT2032)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2031)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2032)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2033)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2035)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2034)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2036)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2037)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2038)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT2039)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCmtyLineSNDWORK;
        private Srvtools.UpdateComponent ucRTLessorAVSCmtyLineSNDWORK;
        private Srvtools.InfoCommand View_RTLessorCmtyLineSndwork;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand RT2032;
        private Srvtools.InfoCommand cmdRT2031;
        private Srvtools.InfoCommand cmdRT2032;
        private Srvtools.InfoCommand cmdRT2033;
        private Srvtools.InfoCommand cmdRT2035;
        private Srvtools.InfoCommand cmdRT2034;
        private Srvtools.InfoCommand cmdRT2036;
        private Srvtools.InfoCommand cmdRT2037;
        private Srvtools.InfoCommand cmdRT2038;
        private Srvtools.InfoCommand cmdRT2039;
        private Srvtools.InfoCommand cmd;
    }
}
