namespace sRT1402
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr58 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr59 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr60 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr61 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr62 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr63 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr64 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr65 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr66 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr67 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr68 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr69 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr70 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr71 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr72 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr73 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr74 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustSndwork = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustSndwork = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustSndwork = new Srvtools.InfoCommand(this.components);
            this.cmdRT1042 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1042)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustSndwork
            // 
            this.RTLessorAVSCustSndwork.CacheConnection = false;
            this.RTLessorAVSCustSndwork.CommandText = "SELECT dbo.[RTLessorAVSCustSndwork].* FROM dbo.[RTLessorAVSCustSndwork]";
            this.RTLessorAVSCustSndwork.CommandTimeout = 30;
            this.RTLessorAVSCustSndwork.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustSndwork.DynamicTableName = false;
            this.RTLessorAVSCustSndwork.EEPAlias = null;
            this.RTLessorAVSCustSndwork.EncodingAfter = null;
            this.RTLessorAVSCustSndwork.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustSndwork.EncodingConvert = null;
            this.RTLessorAVSCustSndwork.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "CUSID";
            keyItem6.KeyName = "PRTNO";
            this.RTLessorAVSCustSndwork.KeyFields.Add(keyItem5);
            this.RTLessorAVSCustSndwork.KeyFields.Add(keyItem6);
            this.RTLessorAVSCustSndwork.MultiSetWhere = false;
            this.RTLessorAVSCustSndwork.Name = "RTLessorAVSCustSndwork";
            this.RTLessorAVSCustSndwork.NotificationAutoEnlist = false;
            this.RTLessorAVSCustSndwork.SecExcept = null;
            this.RTLessorAVSCustSndwork.SecFieldName = null;
            this.RTLessorAVSCustSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustSndwork.SelectPaging = false;
            this.RTLessorAVSCustSndwork.SelectTop = 0;
            this.RTLessorAVSCustSndwork.SiteControl = false;
            this.RTLessorAVSCustSndwork.SiteFieldName = null;
            this.RTLessorAVSCustSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustSndwork
            // 
            this.ucRTLessorAVSCustSndwork.AutoTrans = true;
            this.ucRTLessorAVSCustSndwork.ExceptJoin = false;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "CUSID";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "PRTNO";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "SENDWORKDAT";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "PRTUSR";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "ASSIGNENGINEER";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "ASSIGNCONSIGNEE";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "REALENGINEER";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "REALCONSIGNEE";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "DROPDAT";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "DROPDESC";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "CLOSEDAT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "BONUSCLOSEYM";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "BONUSCLOSEDAT";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "BONUSCLOSEUSR";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "BONUSFINCHK";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "STOCKCLOSEYM";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "STOCKCLOSEDAT";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "STOCKCLOSEUSR";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "STOCKFINCHK";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "MDF1";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            fieldAttr58.CharSetNull = false;
            fieldAttr58.CheckNull = false;
            fieldAttr58.DataField = "MDF2";
            fieldAttr58.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr58.DefaultValue = null;
            fieldAttr58.TrimLength = 0;
            fieldAttr58.UpdateEnable = true;
            fieldAttr58.WhereMode = true;
            fieldAttr59.CharSetNull = false;
            fieldAttr59.CheckNull = false;
            fieldAttr59.DataField = "HOSTNO";
            fieldAttr59.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr59.DefaultValue = null;
            fieldAttr59.TrimLength = 0;
            fieldAttr59.UpdateEnable = true;
            fieldAttr59.WhereMode = true;
            fieldAttr60.CharSetNull = false;
            fieldAttr60.CheckNull = false;
            fieldAttr60.DataField = "HOSTPORT";
            fieldAttr60.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr60.DefaultValue = null;
            fieldAttr60.TrimLength = 0;
            fieldAttr60.UpdateEnable = true;
            fieldAttr60.WhereMode = true;
            fieldAttr61.CharSetNull = false;
            fieldAttr61.CheckNull = false;
            fieldAttr61.DataField = "MEMO";
            fieldAttr61.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr61.DefaultValue = null;
            fieldAttr61.TrimLength = 0;
            fieldAttr61.UpdateEnable = true;
            fieldAttr61.WhereMode = true;
            fieldAttr62.CharSetNull = false;
            fieldAttr62.CheckNull = false;
            fieldAttr62.DataField = "PRTDAT";
            fieldAttr62.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr62.DefaultValue = null;
            fieldAttr62.TrimLength = 0;
            fieldAttr62.UpdateEnable = true;
            fieldAttr62.WhereMode = true;
            fieldAttr63.CharSetNull = false;
            fieldAttr63.CheckNull = false;
            fieldAttr63.DataField = "UNCLOSEDAT";
            fieldAttr63.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr63.DefaultValue = null;
            fieldAttr63.TrimLength = 0;
            fieldAttr63.UpdateEnable = true;
            fieldAttr63.WhereMode = true;
            fieldAttr64.CharSetNull = false;
            fieldAttr64.CheckNull = false;
            fieldAttr64.DataField = "DROPUSR";
            fieldAttr64.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr64.DefaultValue = null;
            fieldAttr64.TrimLength = 0;
            fieldAttr64.UpdateEnable = true;
            fieldAttr64.WhereMode = true;
            fieldAttr65.CharSetNull = false;
            fieldAttr65.CheckNull = false;
            fieldAttr65.DataField = "CLOSEUSR";
            fieldAttr65.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr65.DefaultValue = null;
            fieldAttr65.TrimLength = 0;
            fieldAttr65.UpdateEnable = true;
            fieldAttr65.WhereMode = true;
            fieldAttr66.CharSetNull = false;
            fieldAttr66.CheckNull = false;
            fieldAttr66.DataField = "EUSR";
            fieldAttr66.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr66.DefaultValue = null;
            fieldAttr66.TrimLength = 0;
            fieldAttr66.UpdateEnable = true;
            fieldAttr66.WhereMode = true;
            fieldAttr67.CharSetNull = false;
            fieldAttr67.CheckNull = false;
            fieldAttr67.DataField = "EDAT";
            fieldAttr67.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr67.DefaultValue = null;
            fieldAttr67.TrimLength = 0;
            fieldAttr67.UpdateEnable = true;
            fieldAttr67.WhereMode = true;
            fieldAttr68.CharSetNull = false;
            fieldAttr68.CheckNull = false;
            fieldAttr68.DataField = "UUSR";
            fieldAttr68.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr68.DefaultValue = null;
            fieldAttr68.TrimLength = 0;
            fieldAttr68.UpdateEnable = true;
            fieldAttr68.WhereMode = true;
            fieldAttr69.CharSetNull = false;
            fieldAttr69.CheckNull = false;
            fieldAttr69.DataField = "UDAT";
            fieldAttr69.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr69.DefaultValue = null;
            fieldAttr69.TrimLength = 0;
            fieldAttr69.UpdateEnable = true;
            fieldAttr69.WhereMode = true;
            fieldAttr70.CharSetNull = false;
            fieldAttr70.CheckNull = false;
            fieldAttr70.DataField = "BATCHNO";
            fieldAttr70.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr70.DefaultValue = null;
            fieldAttr70.TrimLength = 0;
            fieldAttr70.UpdateEnable = true;
            fieldAttr70.WhereMode = true;
            fieldAttr71.CharSetNull = false;
            fieldAttr71.CheckNull = false;
            fieldAttr71.DataField = "CDAT";
            fieldAttr71.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr71.DefaultValue = null;
            fieldAttr71.TrimLength = 0;
            fieldAttr71.UpdateEnable = true;
            fieldAttr71.WhereMode = true;
            fieldAttr72.CharSetNull = false;
            fieldAttr72.CheckNull = false;
            fieldAttr72.DataField = "MAXENTRYNO";
            fieldAttr72.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr72.DefaultValue = null;
            fieldAttr72.TrimLength = 0;
            fieldAttr72.UpdateEnable = true;
            fieldAttr72.WhereMode = true;
            fieldAttr73.CharSetNull = false;
            fieldAttr73.CheckNull = false;
            fieldAttr73.DataField = "MAC";
            fieldAttr73.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr73.DefaultValue = null;
            fieldAttr73.TrimLength = 0;
            fieldAttr73.UpdateEnable = true;
            fieldAttr73.WhereMode = true;
            fieldAttr74.CharSetNull = false;
            fieldAttr74.CheckNull = false;
            fieldAttr74.DataField = "RCVMONEYDAT";
            fieldAttr74.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr74.DefaultValue = null;
            fieldAttr74.TrimLength = 0;
            fieldAttr74.UpdateEnable = true;
            fieldAttr74.WhereMode = true;
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr49);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr50);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr51);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr52);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr53);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr54);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr55);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr56);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr57);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr58);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr59);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr60);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr61);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr62);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr63);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr64);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr65);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr66);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr67);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr68);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr69);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr70);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr71);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr72);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr73);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr74);
            this.ucRTLessorAVSCustSndwork.LogInfo = null;
            this.ucRTLessorAVSCustSndwork.Name = "ucRTLessorAVSCustSndwork";
            this.ucRTLessorAVSCustSndwork.RowAffectsCheck = true;
            this.ucRTLessorAVSCustSndwork.SelectCmd = this.RTLessorAVSCustSndwork;
            this.ucRTLessorAVSCustSndwork.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustSndwork.SendSQLCmd = true;
            this.ucRTLessorAVSCustSndwork.ServerModify = true;
            this.ucRTLessorAVSCustSndwork.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustSndwork.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustSndwork.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustSndwork.UseTranscationScope = false;
            this.ucRTLessorAVSCustSndwork.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustSndwork
            // 
            this.View_RTLessorAVSCustSndwork.CacheConnection = false;
            this.View_RTLessorAVSCustSndwork.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustSndwork]";
            this.View_RTLessorAVSCustSndwork.CommandTimeout = 30;
            this.View_RTLessorAVSCustSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustSndwork.DynamicTableName = false;
            this.View_RTLessorAVSCustSndwork.EEPAlias = null;
            this.View_RTLessorAVSCustSndwork.EncodingAfter = null;
            this.View_RTLessorAVSCustSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustSndwork.EncodingConvert = null;
            this.View_RTLessorAVSCustSndwork.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "PRTNO";
            this.View_RTLessorAVSCustSndwork.KeyFields.Add(keyItem1);
            this.View_RTLessorAVSCustSndwork.KeyFields.Add(keyItem2);
            this.View_RTLessorAVSCustSndwork.MultiSetWhere = false;
            this.View_RTLessorAVSCustSndwork.Name = "View_RTLessorAVSCustSndwork";
            this.View_RTLessorAVSCustSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustSndwork.SecExcept = null;
            this.View_RTLessorAVSCustSndwork.SecFieldName = null;
            this.View_RTLessorAVSCustSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustSndwork.SelectPaging = false;
            this.View_RTLessorAVSCustSndwork.SelectTop = 0;
            this.View_RTLessorAVSCustSndwork.SiteControl = false;
            this.View_RTLessorAVSCustSndwork.SiteFieldName = null;
            this.View_RTLessorAVSCustSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1042
            // 
            this.cmdRT1042.CacheConnection = false;
            this.cmdRT1042.CommandText = resources.GetString("cmdRT1042.CommandText");
            this.cmdRT1042.CommandTimeout = 30;
            this.cmdRT1042.CommandType = System.Data.CommandType.Text;
            this.cmdRT1042.DynamicTableName = false;
            this.cmdRT1042.EEPAlias = null;
            this.cmdRT1042.EncodingAfter = null;
            this.cmdRT1042.EncodingBefore = "Windows-1252";
            this.cmdRT1042.EncodingConvert = null;
            this.cmdRT1042.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "PRTNO";
            keyItem7.KeyName = "PRTNO1";
            this.cmdRT1042.KeyFields.Add(keyItem3);
            this.cmdRT1042.KeyFields.Add(keyItem4);
            this.cmdRT1042.KeyFields.Add(keyItem7);
            this.cmdRT1042.MultiSetWhere = false;
            this.cmdRT1042.Name = "cmdRT1042";
            this.cmdRT1042.NotificationAutoEnlist = false;
            this.cmdRT1042.SecExcept = null;
            this.cmdRT1042.SecFieldName = null;
            this.cmdRT1042.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1042.SelectPaging = false;
            this.cmdRT1042.SelectTop = 0;
            this.cmdRT1042.SiteControl = false;
            this.cmdRT1042.SiteFieldName = null;
            this.cmdRT1042.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1042)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustSndwork;
        private Srvtools.UpdateComponent ucRTLessorAVSCustSndwork;
        private Srvtools.InfoCommand View_RTLessorAVSCustSndwork;
        private Srvtools.InfoCommand cmdRT1042;
    }
}
