<!-- #include virtual="/webap/include/lockright.inc" -->
<html>
<head>
</head>
<body id="bg" style="background-image: url('/webap/image/cbbn.bmp');
background-repeat: no-repeat; background-attachment: scroll;
 position: relative; background-position: center
30%">

<p align=center><span style="background-color: #FFFFFF"><font face="細明體" color="#0000FF" size="3"><b>元訊寬頻Intranet應用系統</b></font></span></p>
<p align=CENTER><font face="細明體" color="#0000FF" size="2"><b><span style="background-color: #FFFFFF">資訊部<%=NOW()%></span></b></font></p>
</body>
</html>