namespace sRT10423
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter17 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustHardware = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustHardware = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustHardware = new Srvtools.InfoCommand(this.components);
            this.cmdRT104231 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104232 = new Srvtools.InfoCommand(this.components);
            this.V_RT104231 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104233 = new Srvtools.InfoCommand(this.components);
            this.cmdRT104234 = new Srvtools.InfoCommand(this.components);
            this.V_RT104235 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustHardware)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104231)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104232)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RT104231)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104233)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104234)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RT104235)).BeginInit();
            // 
            // serviceManager1
            // 
            service5.DelegateName = "smRT104231";
            service5.NonLogin = false;
            service5.ServiceName = "smRT104231";
            service6.DelegateName = "smRT104232";
            service6.NonLogin = false;
            service6.ServiceName = "smRT104232";
            service7.DelegateName = "smRT104233";
            service7.NonLogin = false;
            service7.ServiceName = "smRT104233";
            service8.DelegateName = "smRT104234";
            service8.NonLogin = false;
            service8.ServiceName = "smRT104234";
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustHardware
            // 
            this.RTLessorAVSCustHardware.CacheConnection = false;
            this.RTLessorAVSCustHardware.CommandText = "SELECT dbo.[RTLessorAVSCustHardware].* FROM dbo.[RTLessorAVSCustHardware]";
            this.RTLessorAVSCustHardware.CommandTimeout = 30;
            this.RTLessorAVSCustHardware.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustHardware.DynamicTableName = false;
            this.RTLessorAVSCustHardware.EEPAlias = null;
            this.RTLessorAVSCustHardware.EncodingAfter = null;
            this.RTLessorAVSCustHardware.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustHardware.EncodingConvert = null;
            this.RTLessorAVSCustHardware.InfoConnection = this.InfoConnection1;
            keyItem7.KeyName = "CUSID";
            keyItem8.KeyName = "PRTNO";
            keyItem9.KeyName = "ENTRYNO";
            this.RTLessorAVSCustHardware.KeyFields.Add(keyItem7);
            this.RTLessorAVSCustHardware.KeyFields.Add(keyItem8);
            this.RTLessorAVSCustHardware.KeyFields.Add(keyItem9);
            this.RTLessorAVSCustHardware.MultiSetWhere = false;
            this.RTLessorAVSCustHardware.Name = "RTLessorAVSCustHardware";
            this.RTLessorAVSCustHardware.NotificationAutoEnlist = false;
            this.RTLessorAVSCustHardware.SecExcept = null;
            this.RTLessorAVSCustHardware.SecFieldName = null;
            this.RTLessorAVSCustHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustHardware.SelectPaging = false;
            this.RTLessorAVSCustHardware.SelectTop = 0;
            this.RTLessorAVSCustHardware.SiteControl = false;
            this.RTLessorAVSCustHardware.SiteFieldName = null;
            this.RTLessorAVSCustHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustHardware
            // 
            this.ucRTLessorAVSCustHardware.AutoTrans = true;
            this.ucRTLessorAVSCustHardware.ExceptJoin = false;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "CUSID";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PRTNO";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ENTRYNO";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "PRODNO";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "ITEMNO";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "QTY";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "DROPDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "DROPREASON";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "WAREHOUSE";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "ASSETNO";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "DROPUSR";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "UNIT";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "AMT";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "EUSR";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "EDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "UUSR";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "UDAT";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "MEMO";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "BATCHNO";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "TARDAT";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "TUSR";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "RCVPRTNO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "RCVDAT";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "RCVFINISHDAT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCustHardware.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCustHardware.LogInfo = null;
            this.ucRTLessorAVSCustHardware.Name = "ucRTLessorAVSCustHardware";
            this.ucRTLessorAVSCustHardware.RowAffectsCheck = true;
            this.ucRTLessorAVSCustHardware.SelectCmd = this.RTLessorAVSCustHardware;
            this.ucRTLessorAVSCustHardware.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustHardware.SendSQLCmd = true;
            this.ucRTLessorAVSCustHardware.ServerModify = true;
            this.ucRTLessorAVSCustHardware.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustHardware.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustHardware.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustHardware.UseTranscationScope = false;
            this.ucRTLessorAVSCustHardware.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustHardware
            // 
            this.View_RTLessorAVSCustHardware.CacheConnection = false;
            this.View_RTLessorAVSCustHardware.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustHardware]";
            this.View_RTLessorAVSCustHardware.CommandTimeout = 30;
            this.View_RTLessorAVSCustHardware.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustHardware.DynamicTableName = false;
            this.View_RTLessorAVSCustHardware.EEPAlias = null;
            this.View_RTLessorAVSCustHardware.EncodingAfter = null;
            this.View_RTLessorAVSCustHardware.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustHardware.EncodingConvert = null;
            this.View_RTLessorAVSCustHardware.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "PRTNO";
            keyItem3.KeyName = "ENTRYNO";
            this.View_RTLessorAVSCustHardware.KeyFields.Add(keyItem1);
            this.View_RTLessorAVSCustHardware.KeyFields.Add(keyItem2);
            this.View_RTLessorAVSCustHardware.KeyFields.Add(keyItem3);
            this.View_RTLessorAVSCustHardware.MultiSetWhere = false;
            this.View_RTLessorAVSCustHardware.Name = "View_RTLessorAVSCustHardware";
            this.View_RTLessorAVSCustHardware.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustHardware.SecExcept = null;
            this.View_RTLessorAVSCustHardware.SecFieldName = null;
            this.View_RTLessorAVSCustHardware.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustHardware.SelectPaging = false;
            this.View_RTLessorAVSCustHardware.SelectTop = 0;
            this.View_RTLessorAVSCustHardware.SiteControl = false;
            this.View_RTLessorAVSCustHardware.SiteFieldName = null;
            this.View_RTLessorAVSCustHardware.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104231
            // 
            this.cmdRT104231.CacheConnection = false;
            this.cmdRT104231.CommandText = "usp_RTLessorAVSCustHardwareTRNRCVExe";
            this.cmdRT104231.CommandTimeout = 30;
            this.cmdRT104231.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT104231.DynamicTableName = false;
            this.cmdRT104231.EEPAlias = null;
            this.cmdRT104231.EncodingAfter = null;
            this.cmdRT104231.EncodingBefore = "Windows-1252";
            this.cmdRT104231.EncodingConvert = null;
            this.cmdRT104231.InfoConnection = this.InfoConnection1;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter14.ParameterName = "cusid";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 15;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter15.ParameterName = "prtno";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 12;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter16.ParameterName = "usr";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 6;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT104231.InfoParameters.Add(infoParameter14);
            this.cmdRT104231.InfoParameters.Add(infoParameter15);
            this.cmdRT104231.InfoParameters.Add(infoParameter16);
            this.cmdRT104231.MultiSetWhere = false;
            this.cmdRT104231.Name = "cmdRT104231";
            this.cmdRT104231.NotificationAutoEnlist = false;
            this.cmdRT104231.SecExcept = null;
            this.cmdRT104231.SecFieldName = null;
            this.cmdRT104231.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104231.SelectPaging = false;
            this.cmdRT104231.SelectTop = 0;
            this.cmdRT104231.SiteControl = false;
            this.cmdRT104231.SiteFieldName = null;
            this.cmdRT104231.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104232
            // 
            this.cmdRT104232.CacheConnection = false;
            this.cmdRT104232.CommandText = "usp_RTLessorAVSCustHardwareTRNRCVRTNExe";
            this.cmdRT104232.CommandTimeout = 30;
            this.cmdRT104232.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT104232.DynamicTableName = false;
            this.cmdRT104232.EEPAlias = null;
            this.cmdRT104232.EncodingAfter = null;
            this.cmdRT104232.EncodingBefore = "Windows-1252";
            this.cmdRT104232.EncodingConvert = null;
            this.cmdRT104232.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter1.ParameterName = "rcvprtno";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 13;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter2.ParameterName = "usr";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 6;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT104232.InfoParameters.Add(infoParameter1);
            this.cmdRT104232.InfoParameters.Add(infoParameter2);
            this.cmdRT104232.MultiSetWhere = false;
            this.cmdRT104232.Name = "cmdRT104232";
            this.cmdRT104232.NotificationAutoEnlist = false;
            this.cmdRT104232.SecExcept = null;
            this.cmdRT104232.SecFieldName = null;
            this.cmdRT104232.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104232.SelectPaging = false;
            this.cmdRT104232.SelectTop = 0;
            this.cmdRT104232.SiteControl = false;
            this.cmdRT104232.SiteFieldName = null;
            this.cmdRT104232.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // V_RT104231
            // 
            this.V_RT104231.CacheConnection = false;
            this.V_RT104231.CommandText = "select CUSID, PRTNO, count(*) as CNT \r\nFROM RTLessorAVSCUSTHardware\r\nWHERE dropda" +
    "t is null and rcvprtno=\'\' and rcvfinishdat is null and batchno=\'\' and qty > 0 \r\n" +
    "GROUP BY CUSID, PRTNO";
            this.V_RT104231.CommandTimeout = 30;
            this.V_RT104231.CommandType = System.Data.CommandType.Text;
            this.V_RT104231.DynamicTableName = false;
            this.V_RT104231.EEPAlias = null;
            this.V_RT104231.EncodingAfter = null;
            this.V_RT104231.EncodingBefore = "Windows-1252";
            this.V_RT104231.EncodingConvert = null;
            this.V_RT104231.InfoConnection = this.InfoConnection1;
            this.V_RT104231.MultiSetWhere = false;
            this.V_RT104231.Name = "V_RT104231";
            this.V_RT104231.NotificationAutoEnlist = false;
            this.V_RT104231.SecExcept = null;
            this.V_RT104231.SecFieldName = null;
            this.V_RT104231.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.V_RT104231.SelectPaging = false;
            this.V_RT104231.SelectTop = 0;
            this.V_RT104231.SiteControl = false;
            this.V_RT104231.SiteFieldName = null;
            this.V_RT104231.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104233
            // 
            this.cmdRT104233.CacheConnection = false;
            this.cmdRT104233.CommandText = "usp_RTLessorAVSCustHardwareDrop";
            this.cmdRT104233.CommandTimeout = 30;
            this.cmdRT104233.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT104233.DynamicTableName = false;
            this.cmdRT104233.EEPAlias = null;
            this.cmdRT104233.EncodingAfter = null;
            this.cmdRT104233.EncodingBefore = "Windows-1252";
            this.cmdRT104233.EncodingConvert = null;
            this.cmdRT104233.InfoConnection = this.InfoConnection1;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "cusid";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 15;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "prtno";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 12;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter5.ParameterName = "entryno";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 0;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter17.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter17.ParameterName = "usr";
            infoParameter17.Precision = ((byte)(0));
            infoParameter17.Scale = ((byte)(0));
            infoParameter17.Size = 6;
            infoParameter17.SourceColumn = null;
            infoParameter17.XmlSchemaCollectionDatabase = null;
            infoParameter17.XmlSchemaCollectionName = null;
            infoParameter17.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT104233.InfoParameters.Add(infoParameter3);
            this.cmdRT104233.InfoParameters.Add(infoParameter4);
            this.cmdRT104233.InfoParameters.Add(infoParameter5);
            this.cmdRT104233.InfoParameters.Add(infoParameter17);
            this.cmdRT104233.MultiSetWhere = false;
            this.cmdRT104233.Name = "cmdRT104233";
            this.cmdRT104233.NotificationAutoEnlist = false;
            this.cmdRT104233.SecExcept = null;
            this.cmdRT104233.SecFieldName = null;
            this.cmdRT104233.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104233.SelectPaging = false;
            this.cmdRT104233.SelectTop = 0;
            this.cmdRT104233.SiteControl = false;
            this.cmdRT104233.SiteFieldName = null;
            this.cmdRT104233.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT104234
            // 
            this.cmdRT104234.CacheConnection = false;
            this.cmdRT104234.CommandText = "usp_RTLessorAVSCustHardwareDropC";
            this.cmdRT104234.CommandTimeout = 30;
            this.cmdRT104234.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT104234.DynamicTableName = false;
            this.cmdRT104234.EEPAlias = null;
            this.cmdRT104234.EncodingAfter = null;
            this.cmdRT104234.EncodingBefore = "Windows-1252";
            this.cmdRT104234.EncodingConvert = null;
            this.cmdRT104234.InfoConnection = this.InfoConnection1;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter6.ParameterName = "cusid";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 15;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter7.ParameterName = "prtno";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 12;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter8.ParameterName = "entryno";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 0;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "usr";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 6;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT104234.InfoParameters.Add(infoParameter6);
            this.cmdRT104234.InfoParameters.Add(infoParameter7);
            this.cmdRT104234.InfoParameters.Add(infoParameter8);
            this.cmdRT104234.InfoParameters.Add(infoParameter9);
            this.cmdRT104234.MultiSetWhere = false;
            this.cmdRT104234.Name = "cmdRT104234";
            this.cmdRT104234.NotificationAutoEnlist = false;
            this.cmdRT104234.SecExcept = null;
            this.cmdRT104234.SecFieldName = null;
            this.cmdRT104234.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT104234.SelectPaging = false;
            this.cmdRT104234.SelectTop = 0;
            this.cmdRT104234.SiteControl = false;
            this.cmdRT104234.SiteFieldName = null;
            this.cmdRT104234.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // V_RT104235
            // 
            this.V_RT104235.CacheConnection = false;
            this.V_RT104235.CommandText = resources.GetString("V_RT104235.CommandText");
            this.V_RT104235.CommandTimeout = 30;
            this.V_RT104235.CommandType = System.Data.CommandType.Text;
            this.V_RT104235.DynamicTableName = false;
            this.V_RT104235.EEPAlias = null;
            this.V_RT104235.EncodingAfter = null;
            this.V_RT104235.EncodingBefore = "Windows-1252";
            this.V_RT104235.EncodingConvert = null;
            this.V_RT104235.InfoConnection = this.InfoConnection1;
            keyItem4.KeyName = "cusid";
            keyItem5.KeyName = "PRTNO";
            keyItem6.KeyName = "ENTRYNO";
            keyItem10.KeyName = "SEQ";
            this.V_RT104235.KeyFields.Add(keyItem4);
            this.V_RT104235.KeyFields.Add(keyItem5);
            this.V_RT104235.KeyFields.Add(keyItem6);
            this.V_RT104235.KeyFields.Add(keyItem10);
            this.V_RT104235.MultiSetWhere = false;
            this.V_RT104235.Name = "V_RT104235";
            this.V_RT104235.NotificationAutoEnlist = false;
            this.V_RT104235.SecExcept = null;
            this.V_RT104235.SecFieldName = null;
            this.V_RT104235.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.V_RT104235.SelectPaging = false;
            this.V_RT104235.SelectTop = 0;
            this.V_RT104235.SiteControl = false;
            this.V_RT104235.SiteFieldName = null;
            this.V_RT104235.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustHardware)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104231)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104232)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RT104231)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104233)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT104234)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.V_RT104235)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustHardware;
        private Srvtools.UpdateComponent ucRTLessorAVSCustHardware;
        private Srvtools.InfoCommand View_RTLessorAVSCustHardware;
        private Srvtools.InfoCommand cmdRT104231;
        private Srvtools.InfoCommand cmdRT104232;
        private Srvtools.InfoCommand V_RT104231;
        private Srvtools.InfoCommand cmdRT104233;
        private Srvtools.InfoCommand cmdRT104234;
        private Srvtools.InfoCommand V_RT104235;
    }
}
