<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AjaxWebMenuUtility.aspx.cs" Inherits="WebMenuUtility" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>EEP Manager</title>
    <script language="JavaScript" type="text/JavaScript" src="methods.js"></script>

    <link href="css/MenuUtility.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <div>
            <table border="0" cellpadding="0" cellspacing="0" class="fullWidthTable">
                <tr>
                    <td id="headerLogo_bg">
                        <div id="headerLogo">
                        </div>
                    </td>
                </tr>
                <%--<tr>
                <td style="height: 45px;">
                    <asp:Silverlight ID="Xaml1" runat="server" Source="~/ClientBin/SilverlightTools.xap"
                        CssClass="slPlugin" MinimumVersion="2.0.30523" Width="100%" Windowless="true"
                        PluginBackground="Transparent" />
                </td>
            </tr>--%>
            </table>
            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%">
                <tr>
                                <td style="width: 227px; vertical-align: top;">
                                    <div id="leftframe" style="width: 224px; height: 100%;">
                                        <table border="0" cellpadding="0" cellspacing="0" style="width: 224px">
                                            <tr>
                                                <td id="topContent">
                                                    </td>
                                            </tr>
                                            <tr>
                                                <td align="right" style="width: 224px; height: 428px"
                                                    valign="top" id="middleContent">
                                                    &nbsp;<table border="0" cellpadding="0" cellspacing="0" style="width: 200px">
                                                        <tr>
                                                            <td align="left" style="width: 200px; height: 20px;">
                                                                <asp:DropDownList ID="ddlSolution" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlSolution_SelectedIndexChanged"
                                                                    Width="170px">
                                                                </asp:DropDownList></td>
                                                        </tr>
                                                        <tr>
                                                            <td align="left" style="width: 200px">
                                                                <asp:Panel ID="Panel1" runat="server" Height="400px" ScrollBars="Auto" Width="170px">
                                                                    <asp:TreeView ID="tView" runat="server" AutoGenerateDataBindings="False" Height="154px"
                                                                        ImageSet="Simple" NodeIndent="10" ShowLines="True" Width="170px">
                                                                        <NodeStyle Font-Names="Verdana" Font-Size="8pt" ForeColor="White" HorizontalPadding="0px"
                                                                            NodeSpacing="0px" VerticalPadding="0px" />
                                                                        <SelectedNodeStyle Font-Underline="True" ForeColor="#DD5555" HorizontalPadding="0px"
                                                                            ImageUrl="~/Image/main/b5.gif" VerticalPadding="0px" />
                                                                        <HoverNodeStyle Font-Underline="True" ForeColor="#DD5555" />
                                                                        <ParentNodeStyle Font-Bold="False" ImageUrl="~/Image/main/b4.gif" />
                                                                        <RootNodeStyle ImageUrl="~/Image/main/b4.gif" />
                                                                        <LeafNodeStyle ImageUrl="~/Image/main/b6.gif" />
                                                                    </asp:TreeView>
                                                                </asp:Panel>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="left" style="width: 224px; height: 60px" id="footContent">
                                                    <table border="0" cellpadding="0" cellspacing="0">
                                                        <tr>
                                                            <td id="marginContent1">
                                                            </td>
                                                            <td id="changePasswordContainer">
                                                                <asp:Button ID="btnChangepassword" runat="server" CssClass="btn_mouseout" OnClick="btnChangepassword_Click"
                                                                    onmouseout="this.className='btn_mouseout';" onmouseover="this.className='btn_mouseover';"
                                                                    Text="修改密碼" Width="60px" />
                                                            </td>
                                                            <td id="logOutContainer">
                                                                <asp:Button ID="btnLogOut" runat="server" CssClass="btn_mouseout" OnClick="btnLogOut_Click"
                                                                    onmouseout="this.className='btn_mouseout';" onmouseover="this.className='btn_mouseover';"
                                                                    Text="log out" Width="60px" />
                                                            </td>
                                                            <td id="marginContent2">
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </td>
                                <td style="width: 10px;" valign="top" id="split">
                                        <img height="16" src="Image/main/close.gif" width="10" alt="hide tree" id="IMG1"
                                        onclick="return IMG1_onclick(this)" />
                                        </td>
                                <td id="mainframe" style="width: 100%;"
                                    valign="top">
                                    <iframe id="main" frameborder="0" marginheight="0" marginwidth="2" name="main"
                                        scrolling="auto" src="DefaultPage.aspx" width="100%" height="600"></iframe>
                                </td>
                </tr>
            </table>
        </div>
    
    </div>
    </form>
</body>
</html>
