/*
SELECT A.RZONE1, A.CUTID1, B.CUTNC, A.TOWNSHIP1, A.RADDR1 
FROM RTLessorAVSCust A
LEFT JOIN RTCounty B ON B.CUTID=A.CUTID1
*/

UPDATE A 
SET A.RADDR1=A.RZONE1+ISNULL(B.CUTNC, '')+ ISNULL(A.TOWNSHIP1, '')+ ISNULL(A.RADDR1, '')
FROM RTLessorAVSCust A
LEFT JOIN RTCounty B ON B.CUTID=A.CUTID1
UPDATE A 
SET A.RADDR2=A.RZONE2+ISNULL(B.CUTNC, '')+ ISNULL(A.TOWNSHIP2, '')+ ISNULL(A.RADDR2, '')
FROM RTLessorAVSCust A
LEFT JOIN RTCounty B ON B.CUTID=A.CUTID2
UPDATE A 
SET A.RADDR3=A.RZONE3+ISNULL(B.CUTNC, '')+ ISNULL(A.TOWNSHIP3, '')+ ISNULL(A.RADDR3, '')
FROM RTLessorAVSCust A
LEFT JOIN RTCounty B ON B.CUTID=A.CUTID3