namespace sRT1042
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustSndwork = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustSndwork = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustSndwork = new Srvtools.InfoCommand(this.components);
            this.RT1042 = new Srvtools.InfoCommand(this.components);
            this.autoNumber1 = new Srvtools.AutoNumber(this.components);
            this.RT10421 = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1042)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10421)).BeginInit();
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustSndwork
            // 
            this.RTLessorAVSCustSndwork.CacheConnection = false;
            this.RTLessorAVSCustSndwork.CommandText = "SELECT dbo.[RTLessorAVSCustSndwork].* FROM dbo.[RTLessorAVSCustSndwork]";
            this.RTLessorAVSCustSndwork.CommandTimeout = 30;
            this.RTLessorAVSCustSndwork.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustSndwork.DynamicTableName = false;
            this.RTLessorAVSCustSndwork.EEPAlias = null;
            this.RTLessorAVSCustSndwork.EncodingAfter = null;
            this.RTLessorAVSCustSndwork.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustSndwork.EncodingConvert = null;
            this.RTLessorAVSCustSndwork.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "PRTNO";
            this.RTLessorAVSCustSndwork.KeyFields.Add(keyItem1);
            this.RTLessorAVSCustSndwork.KeyFields.Add(keyItem2);
            this.RTLessorAVSCustSndwork.MultiSetWhere = false;
            this.RTLessorAVSCustSndwork.Name = "RTLessorAVSCustSndwork";
            this.RTLessorAVSCustSndwork.NotificationAutoEnlist = false;
            this.RTLessorAVSCustSndwork.SecExcept = null;
            this.RTLessorAVSCustSndwork.SecFieldName = null;
            this.RTLessorAVSCustSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustSndwork.SelectPaging = false;
            this.RTLessorAVSCustSndwork.SelectTop = 0;
            this.RTLessorAVSCustSndwork.SiteControl = false;
            this.RTLessorAVSCustSndwork.SiteFieldName = null;
            this.RTLessorAVSCustSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustSndwork
            // 
            this.ucRTLessorAVSCustSndwork.AutoTrans = true;
            this.ucRTLessorAVSCustSndwork.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CUSID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "PRTNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "SENDWORKDAT";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "PRTUSR";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "ASSIGNENGINEER";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "ASSIGNCONSIGNEE";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "REALENGINEER";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "REALCONSIGNEE";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "DROPDAT";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "DROPDESC";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CLOSEDAT";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "BONUSCLOSEYM";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "BONUSCLOSEDAT";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "BONUSCLOSEUSR";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "BONUSFINCHK";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "STOCKCLOSEYM";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "STOCKCLOSEDAT";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "STOCKCLOSEUSR";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "STOCKFINCHK";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "MDF1";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "MDF2";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "HOSTNO";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "HOSTPORT";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "MEMO";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "PRTDAT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "UNCLOSEDAT";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "DROPUSR";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "CLOSEUSR";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "EUSR";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "EDAT";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "UUSR";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "UDAT";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "BATCHNO";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "CDAT";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "MAXENTRYNO";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "MAC";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "RCVMONEYDAT";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCustSndwork.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCustSndwork.LogInfo = null;
            this.ucRTLessorAVSCustSndwork.Name = "ucRTLessorAVSCustSndwork";
            this.ucRTLessorAVSCustSndwork.RowAffectsCheck = true;
            this.ucRTLessorAVSCustSndwork.SelectCmd = this.RTLessorAVSCustSndwork;
            this.ucRTLessorAVSCustSndwork.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustSndwork.SendSQLCmd = true;
            this.ucRTLessorAVSCustSndwork.ServerModify = true;
            this.ucRTLessorAVSCustSndwork.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustSndwork.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustSndwork.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustSndwork.UseTranscationScope = false;
            this.ucRTLessorAVSCustSndwork.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustSndwork
            // 
            this.View_RTLessorAVSCustSndwork.CacheConnection = false;
            this.View_RTLessorAVSCustSndwork.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustSndwork]";
            this.View_RTLessorAVSCustSndwork.CommandTimeout = 30;
            this.View_RTLessorAVSCustSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustSndwork.DynamicTableName = false;
            this.View_RTLessorAVSCustSndwork.EEPAlias = null;
            this.View_RTLessorAVSCustSndwork.EncodingAfter = null;
            this.View_RTLessorAVSCustSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustSndwork.EncodingConvert = null;
            this.View_RTLessorAVSCustSndwork.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "PRTNO";
            this.View_RTLessorAVSCustSndwork.KeyFields.Add(keyItem3);
            this.View_RTLessorAVSCustSndwork.KeyFields.Add(keyItem4);
            this.View_RTLessorAVSCustSndwork.MultiSetWhere = false;
            this.View_RTLessorAVSCustSndwork.Name = "View_RTLessorAVSCustSndwork";
            this.View_RTLessorAVSCustSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustSndwork.SecExcept = null;
            this.View_RTLessorAVSCustSndwork.SecFieldName = null;
            this.View_RTLessorAVSCustSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustSndwork.SelectPaging = false;
            this.View_RTLessorAVSCustSndwork.SelectTop = 0;
            this.View_RTLessorAVSCustSndwork.SiteControl = false;
            this.View_RTLessorAVSCustSndwork.SiteFieldName = null;
            this.View_RTLessorAVSCustSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT1042
            // 
            this.RT1042.CacheConnection = false;
            this.RT1042.CommandText = resources.GetString("RT1042.CommandText");
            this.RT1042.CommandTimeout = 30;
            this.RT1042.CommandType = System.Data.CommandType.Text;
            this.RT1042.DynamicTableName = false;
            this.RT1042.EEPAlias = null;
            this.RT1042.EncodingAfter = null;
            this.RT1042.EncodingBefore = "Windows-1252";
            this.RT1042.EncodingConvert = null;
            this.RT1042.InfoConnection = this.InfoConnection1;
            keyItem5.KeyName = "CUSID";
            keyItem6.KeyName = "PRTNO";
            keyItem7.KeyName = "PRTNO1";
            this.RT1042.KeyFields.Add(keyItem5);
            this.RT1042.KeyFields.Add(keyItem6);
            this.RT1042.KeyFields.Add(keyItem7);
            this.RT1042.MultiSetWhere = false;
            this.RT1042.Name = "RT1042";
            this.RT1042.NotificationAutoEnlist = false;
            this.RT1042.SecExcept = null;
            this.RT1042.SecFieldName = null;
            this.RT1042.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT1042.SelectPaging = false;
            this.RT1042.SelectTop = 0;
            this.RT1042.SiteControl = false;
            this.RT1042.SiteFieldName = null;
            this.RT1042.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // autoNumber1
            // 
            this.autoNumber1.Active = true;
            this.autoNumber1.AutoNoID = "RT1042";
            this.autoNumber1.Description = null;
            this.autoNumber1.GetFixed = "getFix()";
            this.autoNumber1.isNumFill = false;
            this.autoNumber1.Name = "autoNumber1";
            this.autoNumber1.Number = null;
            this.autoNumber1.NumDig = 4;
            this.autoNumber1.OldVersion = false;
            this.autoNumber1.OverFlow = true;
            this.autoNumber1.StartValue = 1;
            this.autoNumber1.Step = 1;
            this.autoNumber1.TargetColumn = "PRTNO";
            this.autoNumber1.UpdateComp = this.ucRTLessorAVSCustSndwork;
            // 
            // RT10421
            // 
            this.RT10421.CacheConnection = false;
            this.RT10421.CommandText = "SELECT CUSID, PRTNO, COUNT(*) AS CNT FROM RTLESSORAVSCUSTHARDWARE \r\nWHERE DROPDAT" +
    " IS NULL AND RCVFINISHDAT IS NULL\r\nGROUP BY CUSID, PRTNO";
            this.RT10421.CommandTimeout = 30;
            this.RT10421.CommandType = System.Data.CommandType.Text;
            this.RT10421.DynamicTableName = false;
            this.RT10421.EEPAlias = null;
            this.RT10421.EncodingAfter = null;
            this.RT10421.EncodingBefore = "Windows-1252";
            this.RT10421.EncodingConvert = null;
            this.RT10421.InfoConnection = this.InfoConnection1;
            this.RT10421.MultiSetWhere = false;
            this.RT10421.Name = "RT10421";
            this.RT10421.NotificationAutoEnlist = false;
            this.RT10421.SecExcept = null;
            this.RT10421.SecFieldName = null;
            this.RT10421.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT10421.SelectPaging = false;
            this.RT10421.SelectTop = 0;
            this.RT10421.SiteControl = false;
            this.RT10421.SiteFieldName = null;
            this.RT10421.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT1042)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10421)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustSndwork;
        private Srvtools.UpdateComponent ucRTLessorAVSCustSndwork;
        private Srvtools.InfoCommand View_RTLessorAVSCustSndwork;
        private Srvtools.InfoCommand RT1042;
        private Srvtools.AutoNumber autoNumber1;
        private Srvtools.InfoCommand RT10421;
    }
}
