SELECT A.COMQ1, B.COMN , A.LINEQ1, A.CUSID , A.CUSNC , D.CUTNC , A.TOWNSHIP2 , A.RADDR2 
, A.MOBILE , A.COMTYPE , E.CODENC , A.CASEKIND , F.CODENC 
, A.IP11 , A.APPLYDAT , A.FINISHDAT, A.DOCKETDAT, A.STRBILLINGDAT, A.NEWBILLINGDAT, A.DUEDAT , A.FREECODE 
, A.DROPDAT , A.CANCELDAT , C.QT_CC , C.ADDR
FROM RTLessorAVSCust A
LEFT JOIN RTLessorAVSCmtyH B ON B.COMQ1=A.COMQ1 
LEFT OUTER JOIN V_RT104FAQ C ON C.CUSIDF=A.CUSID
LEFT OUTER JOIN RTCounty D ON D.CUTID=A.CUTID2
LEFT OUTER JOIN RTCode E ON E.KIND='P5' AND E.CODE=A.COMTYPE
LEFT OUTER JOIN RTCode F ON F.KIND='O9' AND F.CODE=A.CASEKIND
WHERE 1=1
order by ISNULL(A.DROPDAT, '')+ISNULL(A.CANCELDAT, ''), A.IP11