SELECT * FROM RTLessorAVSCustCont

SELECT * FROM RTLessorAVSCustBillingBarcode
WHERE CSNOTICEID LIKE 'A1805%' 

SELECT A.* FROM RTLessorAVSCustCont A
LEFT JOIN RTLessorAVSCust B ON B.CUSID=A.CUSID
WHERE B.CUSID = 'S130403014' AND ENTRYNO = 8

INSERT INTO RTLessorAVSCustCont
(CUSID, ENTRYNO, APPLYDAT, PAYCYCLE, PERIOD, SECONDCASE, AMT, PAYTYPE, REALAMT, TARDAT, BATCHNO, TUSR, FINISHDAT, EDAT, EUSR, UDAT, ADJUSTDAY
,STRBILLINGDAT, MAXENTRYNO, CASEKIND, RCVMONEYDAT, CSNOTICEID)
SELECT A.CUSID, ISNULL(D.MM, 0)+1 AS ENTRYNO, GETDATE() AS APPLYDAT, B.PAYCYCLE, A.PERIOD, C.SECONDCASE
, A.AMT, '05' AS PAYTYPE, 0 AS REALAMT, GETDATE() AS TARDAT, A.BATCHNO, 'USER' AS TUSR
, GETDATE() AS FINISHDAT, GETDATE() AS EDAT, 'USER' AS EUSR, GETDATE() AS UDAT, 0 AS ADJUSTDAY
,  dateadd(d, 1, E.DUEDAT) AS STRBILLINGDAT, 0 AS MAXENTRYNO, C.CASEKIND, A.CDAT AS RCVMONEYDAT, B.CSNOTICEID
FROM RTLessorAVSCustAR A
LEFT JOIN RTLessorAVSCustBillingBarcode B ON B.CSBARCOD1=A.COD3 AND B.CSBARCOD2=A.COD4 AND  B.CSBARCOD3=A.COD5
LEFT JOIN RTLessorAVSCust C ON C.CUSID=A.CUSID
LEFT JOIN (SELECT CUSID, MAX(ENTRYNO) AS MM FROM RTLessorAVSCustCont GROUP BY CUSID) D ON D.CUSID=A.CUSID
LEFT JOIN RTLessorAVSCustBillingPrtSub E ON E.NOTICEID=B.NOTICEID
WHERE A.CDAT >='20180501' AND A.COD1 <> ''AND COD3 <> ''
 AND A.BATCHNO NOT IN (SELECT BATCHNO FROM RTLessorAVSCustCont A)

SELECT * FROM RTLessorAVSCustBillingPrtSub
WHERE BATCH = '20180501'
SELECT * FROM RTLessorAVSCustBillingBarcode
WHERE NOTICEID IN (SELECT NOTICEID FROM RTLessorAVSCustBillingPrtSub
WHERE BATCH = '20180501')


DELETE FROM RTLessorAVSCustCont
WHERE BATCHNO IN (SELECT BATCHNO FROM RTLessorAVSCustAR A WHERE  A.CDAT >='20180501' AND COD3 <> '')