SELECT * 
FROM RTCODE WHERE KIND='O9' AND CODE > '30'

SELECT DISTINCT CASEKIND FROM RTLessorAVSCust
WHERE COMTYPE = '9'
ORDER BY CASEKIND

INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '31', '高資費', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '32', '中資費', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '33', '低資費', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '34', '專案300', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '35', '專案250', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '36', '專案200', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '37', '標準型+', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '38', '專業型+', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '39', '經濟型', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '40', '老客戶專案', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '41', '20M', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '42', '40M', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '43', '70M', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '44', '專業型', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '45', '標準型', '7')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '46', '經濟250', '7')

INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '47', '標準型+', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '48', '專業型+', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '49', '專案250', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '50', '專案300', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '51', '經濟型', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '52', '標準型', '8')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '53', '專業型', '8')

INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '54', '20M', '9')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '55', '40M', '9')
INSERT INTO RTCode (KIND, CODE, CODENC, PARM1) VALUES ('O9', '56', '70M', '9')

/*-AVS
AVS--01-39,02-44,03-35,04-36,05-45,07-46,08-34,09-38,10-37,11-40,14-41,15-31,16-33,17-41,18-42,19-43,20-32
*/
UPDATE RTLessorAVSCust SET CASEKIND = '39' WHERE COMTYPE='7' AND CASEKIND='01'
UPDATE RTLessorAVSCust SET CASEKIND = '44' WHERE COMTYPE='7' AND CASEKIND='02'
UPDATE RTLessorAVSCust SET CASEKIND = '35' WHERE COMTYPE='7' AND CASEKIND='03'
UPDATE RTLessorAVSCust SET CASEKIND = '36' WHERE COMTYPE='7' AND CASEKIND='04'
UPDATE RTLessorAVSCust SET CASEKIND = '45' WHERE COMTYPE='7' AND CASEKIND='05'
UPDATE RTLessorAVSCust SET CASEKIND = '46' WHERE COMTYPE='7' AND CASEKIND='07'
UPDATE RTLessorAVSCust SET CASEKIND = '34' WHERE COMTYPE='7' AND CASEKIND='08'
UPDATE RTLessorAVSCust SET CASEKIND = '38' WHERE COMTYPE='7' AND CASEKIND='09'
UPDATE RTLessorAVSCust SET CASEKIND = '37' WHERE COMTYPE='7' AND CASEKIND='10'
UPDATE RTLessorAVSCust SET CASEKIND = '40' WHERE COMTYPE='7' AND CASEKIND='11'
UPDATE RTLessorAVSCust SET CASEKIND = '41' WHERE COMTYPE='7' AND CASEKIND='14'
UPDATE RTLessorAVSCust SET CASEKIND = '31' WHERE COMTYPE='7' AND CASEKIND='15'
UPDATE RTLessorAVSCust SET CASEKIND = '33' WHERE COMTYPE='7' AND CASEKIND='16'
UPDATE RTLessorAVSCust SET CASEKIND = '41' WHERE COMTYPE='7' AND CASEKIND='17'
UPDATE RTLessorAVSCust SET CASEKIND = '42' WHERE COMTYPE='7' AND CASEKIND='18'
UPDATE RTLessorAVSCust SET CASEKIND = '43' WHERE COMTYPE='7' AND CASEKIND='19'
UPDATE RTLessorAVSCust SET CASEKIND = '32' WHERE COMTYPE='7' AND CASEKIND='20'

/*ET --01-51,02-53,03-49,05-52,08-50,09-48,10-47*/
UPDATE RTLessorAVSCust SET CASEKIND = '51' WHERE COMTYPE='8' AND CASEKIND='01'
UPDATE RTLessorAVSCust SET CASEKIND = '53' WHERE COMTYPE='8' AND CASEKIND='02'
UPDATE RTLessorAVSCust SET CASEKIND = '49' WHERE COMTYPE='8' AND CASEKIND='03'
UPDATE RTLessorAVSCust SET CASEKIND = '52' WHERE COMTYPE='8' AND CASEKIND='05'
UPDATE RTLessorAVSCust SET CASEKIND = '50' WHERE COMTYPE='8' AND CASEKIND='08'
UPDATE RTLessorAVSCust SET CASEKIND = '48' WHERE COMTYPE='8' AND CASEKIND='09'
UPDATE RTLessorAVSCust SET CASEKIND = '47' WHERE COMTYPE='8' AND CASEKIND='10'
