select * from RTLessorAVSCust
select * from RTCode
WHERE KIND='O9'

select * from RTCode
WHERE KIND='P5' AND CODE IN ('7','8', '9', 'B')
ORDER BY PARM1 

UPDATE RTCode SET PARM1 = '1' WHERE KIND='P5' AND CODE='7'
UPDATE RTCode SET PARM1 = '2' WHERE KIND='P5' AND CODE='8'
UPDATE RTCode SET PARM1 = '4' WHERE KIND='P5' AND CODE='9'
UPDATE RTCode SET PARM1 = '3' WHERE KIND='P5' AND CODE='B'

UPDATE RTCode SET CODENC = '元訊So-net專案20M' WHERE KIND='O9' AND CODE='41'
UPDATE RTCode SET CODENC = '元訊So-net專案40M' WHERE KIND='O9' AND CODE='42'
UPDATE RTCode SET CODENC = '元訊So-net專案60M' WHERE KIND='O9' AND CODE='43'

UPDATE RTCode SET PARM1 = 'B' WHERE KIND='O9' AND CODE='54'
UPDATE RTCode SET PARM1 = 'B' WHERE KIND='O9' AND CODE='55'
UPDATE RTCode SET PARM1 = 'B' WHERE KIND='O9' AND CODE='56'

select * from RTCode
WHERE KIND='O9'
ORDER BY PARM1 