namespace sRT1045
{
    partial class Component
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Srvtools.Service service1 = new Srvtools.Service();
            Srvtools.Service service2 = new Srvtools.Service();
            Srvtools.Service service3 = new Srvtools.Service();
            Srvtools.Service service4 = new Srvtools.Service();
            Srvtools.Service service5 = new Srvtools.Service();
            Srvtools.Service service6 = new Srvtools.Service();
            Srvtools.Service service7 = new Srvtools.Service();
            Srvtools.Service service8 = new Srvtools.Service();
            Srvtools.Service service9 = new Srvtools.Service();
            Srvtools.Service service10 = new Srvtools.Service();
            Srvtools.KeyItem keyItem1 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem2 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr1 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr2 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr3 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr4 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr5 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr6 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr7 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr8 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr9 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr10 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr11 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr12 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr13 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr14 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr15 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr16 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr17 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr18 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr19 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr20 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr21 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem3 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem4 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem5 = new Srvtools.KeyItem();
            Srvtools.FieldAttr fieldAttr22 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr23 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr24 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr25 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr26 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr27 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr28 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr29 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr30 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr31 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr32 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr33 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr34 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr35 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr36 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr37 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr38 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr39 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr40 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr41 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr42 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr43 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr44 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr45 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr46 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr47 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr48 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr49 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr50 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr51 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr52 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr53 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr54 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr55 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr56 = new Srvtools.FieldAttr();
            Srvtools.FieldAttr fieldAttr57 = new Srvtools.FieldAttr();
            Srvtools.KeyItem keyItem6 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem7 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem8 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem9 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem10 = new Srvtools.KeyItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Component));
            Srvtools.KeyItem keyItem11 = new Srvtools.KeyItem();
            Srvtools.KeyItem keyItem12 = new Srvtools.KeyItem();
            Srvtools.InfoParameter infoParameter1 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter2 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter3 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter4 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter5 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter6 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter7 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter8 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter9 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter10 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter11 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter12 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter13 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter14 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter15 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter16 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter17 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter18 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter19 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter20 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter21 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter22 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter23 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter24 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter25 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter26 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter27 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter28 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter29 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter30 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter31 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter32 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter33 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter34 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter35 = new Srvtools.InfoParameter();
            Srvtools.InfoParameter infoParameter36 = new Srvtools.InfoParameter();
            this.serviceManager1 = new Srvtools.ServiceManager(this.components);
            this.InfoConnection1 = new Srvtools.InfoConnection(this.components);
            this.RTLessorAVSCustDrop = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustDrop = new Srvtools.UpdateComponent(this.components);
            this.RTLessorAVSCustDropSndwork = new Srvtools.InfoCommand(this.components);
            this.ucRTLessorAVSCustDropSndwork = new Srvtools.UpdateComponent(this.components);
            this.View_RTLessorAVSCustDrop = new Srvtools.InfoCommand(this.components);
            this.View_RTLessorAVSCustDropSndwork = new Srvtools.InfoCommand(this.components);
            this.RT10451 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10451 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10452 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10453 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10455 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10454 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10456 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10457 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10458 = new Srvtools.InfoCommand(this.components);
            this.cmdRT10459 = new Srvtools.InfoCommand(this.components);
            this.cmdRT1045A = new Srvtools.InfoCommand(this.components);
            this.cmd = new Srvtools.InfoCommand(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustDrop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustDropSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustDrop)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustDropSndwork)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10451)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10451)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10452)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10453)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10455)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10454)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10456)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10457)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10458)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10459)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1045A)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).BeginInit();
            // 
            // serviceManager1
            // 
            service1.DelegateName = "smRT10451";
            service1.NonLogin = false;
            service1.ServiceName = "smRT10451";
            service2.DelegateName = "smRT10452";
            service2.NonLogin = false;
            service2.ServiceName = "smRT10452";
            service3.DelegateName = "smRT10453";
            service3.NonLogin = false;
            service3.ServiceName = "smRT10453";
            service4.DelegateName = "smRT10454";
            service4.NonLogin = false;
            service4.ServiceName = "smRT10454";
            service5.DelegateName = "smRT10455";
            service5.NonLogin = false;
            service5.ServiceName = "smRT10455";
            service6.DelegateName = "smRT10456";
            service6.NonLogin = false;
            service6.ServiceName = "smRT10456";
            service7.DelegateName = "smRT10457";
            service7.NonLogin = false;
            service7.ServiceName = "smRT10457";
            service8.DelegateName = "smRT10458";
            service8.NonLogin = false;
            service8.ServiceName = "smRT10458";
            service9.DelegateName = "smRT10459";
            service9.NonLogin = false;
            service9.ServiceName = "smRT10459";
            service10.DelegateName = "smRT1045A";
            service10.NonLogin = false;
            service10.ServiceName = "smRT1045A";
            this.serviceManager1.ServiceCollection.Add(service1);
            this.serviceManager1.ServiceCollection.Add(service2);
            this.serviceManager1.ServiceCollection.Add(service3);
            this.serviceManager1.ServiceCollection.Add(service4);
            this.serviceManager1.ServiceCollection.Add(service5);
            this.serviceManager1.ServiceCollection.Add(service6);
            this.serviceManager1.ServiceCollection.Add(service7);
            this.serviceManager1.ServiceCollection.Add(service8);
            this.serviceManager1.ServiceCollection.Add(service9);
            this.serviceManager1.ServiceCollection.Add(service10);
            // 
            // InfoConnection1
            // 
            this.InfoConnection1.EEPAlias = "RTLib";
            // 
            // RTLessorAVSCustDrop
            // 
            this.RTLessorAVSCustDrop.CacheConnection = false;
            this.RTLessorAVSCustDrop.CommandText = "SELECT dbo.[RTLessorAVSCustDrop].* FROM dbo.[RTLessorAVSCustDrop]";
            this.RTLessorAVSCustDrop.CommandTimeout = 30;
            this.RTLessorAVSCustDrop.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustDrop.DynamicTableName = false;
            this.RTLessorAVSCustDrop.EEPAlias = null;
            this.RTLessorAVSCustDrop.EncodingAfter = null;
            this.RTLessorAVSCustDrop.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustDrop.EncodingConvert = null;
            this.RTLessorAVSCustDrop.InfoConnection = this.InfoConnection1;
            keyItem1.KeyName = "CUSID";
            keyItem2.KeyName = "ENTRYNO";
            this.RTLessorAVSCustDrop.KeyFields.Add(keyItem1);
            this.RTLessorAVSCustDrop.KeyFields.Add(keyItem2);
            this.RTLessorAVSCustDrop.MultiSetWhere = false;
            this.RTLessorAVSCustDrop.Name = "RTLessorAVSCustDrop";
            this.RTLessorAVSCustDrop.NotificationAutoEnlist = false;
            this.RTLessorAVSCustDrop.SecExcept = null;
            this.RTLessorAVSCustDrop.SecFieldName = null;
            this.RTLessorAVSCustDrop.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustDrop.SelectPaging = false;
            this.RTLessorAVSCustDrop.SelectTop = 0;
            this.RTLessorAVSCustDrop.SiteControl = false;
            this.RTLessorAVSCustDrop.SiteFieldName = null;
            this.RTLessorAVSCustDrop.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustDrop
            // 
            this.ucRTLessorAVSCustDrop.AutoTrans = true;
            this.ucRTLessorAVSCustDrop.ExceptJoin = false;
            fieldAttr1.CharSetNull = false;
            fieldAttr1.CheckNull = false;
            fieldAttr1.DataField = "CUSID";
            fieldAttr1.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr1.DefaultValue = null;
            fieldAttr1.TrimLength = 0;
            fieldAttr1.UpdateEnable = true;
            fieldAttr1.WhereMode = true;
            fieldAttr2.CharSetNull = false;
            fieldAttr2.CheckNull = false;
            fieldAttr2.DataField = "ENTRYNO";
            fieldAttr2.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr2.DefaultValue = null;
            fieldAttr2.TrimLength = 0;
            fieldAttr2.UpdateEnable = true;
            fieldAttr2.WhereMode = true;
            fieldAttr3.CharSetNull = false;
            fieldAttr3.CheckNull = false;
            fieldAttr3.DataField = "DROPKIND";
            fieldAttr3.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr3.DefaultValue = null;
            fieldAttr3.TrimLength = 0;
            fieldAttr3.UpdateEnable = true;
            fieldAttr3.WhereMode = true;
            fieldAttr4.CharSetNull = false;
            fieldAttr4.CheckNull = false;
            fieldAttr4.DataField = "APPLYDAT";
            fieldAttr4.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr4.DefaultValue = null;
            fieldAttr4.TrimLength = 0;
            fieldAttr4.UpdateEnable = true;
            fieldAttr4.WhereMode = true;
            fieldAttr5.CharSetNull = false;
            fieldAttr5.CheckNull = false;
            fieldAttr5.DataField = "ENDDAT";
            fieldAttr5.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr5.DefaultValue = null;
            fieldAttr5.TrimLength = 0;
            fieldAttr5.UpdateEnable = true;
            fieldAttr5.WhereMode = true;
            fieldAttr6.CharSetNull = false;
            fieldAttr6.CheckNull = false;
            fieldAttr6.DataField = "FINISHDAT";
            fieldAttr6.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr6.DefaultValue = null;
            fieldAttr6.TrimLength = 0;
            fieldAttr6.UpdateEnable = true;
            fieldAttr6.WhereMode = true;
            fieldAttr7.CharSetNull = false;
            fieldAttr7.CheckNull = false;
            fieldAttr7.DataField = "FUSR";
            fieldAttr7.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr7.DefaultValue = null;
            fieldAttr7.TrimLength = 0;
            fieldAttr7.UpdateEnable = true;
            fieldAttr7.WhereMode = true;
            fieldAttr8.CharSetNull = false;
            fieldAttr8.CheckNull = false;
            fieldAttr8.DataField = "SNDPRTNO";
            fieldAttr8.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr8.DefaultValue = null;
            fieldAttr8.TrimLength = 0;
            fieldAttr8.UpdateEnable = true;
            fieldAttr8.WhereMode = true;
            fieldAttr9.CharSetNull = false;
            fieldAttr9.CheckNull = false;
            fieldAttr9.DataField = "SNDWORKCLOSE";
            fieldAttr9.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr9.DefaultValue = null;
            fieldAttr9.TrimLength = 0;
            fieldAttr9.UpdateEnable = true;
            fieldAttr9.WhereMode = true;
            fieldAttr10.CharSetNull = false;
            fieldAttr10.CheckNull = false;
            fieldAttr10.DataField = "CANCELDAT";
            fieldAttr10.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr10.DefaultValue = null;
            fieldAttr10.TrimLength = 0;
            fieldAttr10.UpdateEnable = true;
            fieldAttr10.WhereMode = true;
            fieldAttr11.CharSetNull = false;
            fieldAttr11.CheckNull = false;
            fieldAttr11.DataField = "CANCELUSR";
            fieldAttr11.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr11.DefaultValue = null;
            fieldAttr11.TrimLength = 0;
            fieldAttr11.UpdateEnable = true;
            fieldAttr11.WhereMode = true;
            fieldAttr12.CharSetNull = false;
            fieldAttr12.CheckNull = false;
            fieldAttr12.DataField = "MEMO";
            fieldAttr12.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr12.DefaultValue = null;
            fieldAttr12.TrimLength = 0;
            fieldAttr12.UpdateEnable = true;
            fieldAttr12.WhereMode = true;
            fieldAttr13.CharSetNull = false;
            fieldAttr13.CheckNull = false;
            fieldAttr13.DataField = "EUSR";
            fieldAttr13.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr13.DefaultValue = null;
            fieldAttr13.TrimLength = 0;
            fieldAttr13.UpdateEnable = true;
            fieldAttr13.WhereMode = true;
            fieldAttr14.CharSetNull = false;
            fieldAttr14.CheckNull = false;
            fieldAttr14.DataField = "EDAT";
            fieldAttr14.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr14.DefaultValue = null;
            fieldAttr14.TrimLength = 0;
            fieldAttr14.UpdateEnable = true;
            fieldAttr14.WhereMode = true;
            fieldAttr15.CharSetNull = false;
            fieldAttr15.CheckNull = false;
            fieldAttr15.DataField = "UUSR";
            fieldAttr15.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr15.DefaultValue = null;
            fieldAttr15.TrimLength = 0;
            fieldAttr15.UpdateEnable = true;
            fieldAttr15.WhereMode = true;
            fieldAttr16.CharSetNull = false;
            fieldAttr16.CheckNull = false;
            fieldAttr16.DataField = "UDAT";
            fieldAttr16.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr16.DefaultValue = null;
            fieldAttr16.TrimLength = 0;
            fieldAttr16.UpdateEnable = true;
            fieldAttr16.WhereMode = true;
            fieldAttr17.CharSetNull = false;
            fieldAttr17.CheckNull = false;
            fieldAttr17.DataField = "SNDWORK";
            fieldAttr17.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr17.DefaultValue = null;
            fieldAttr17.TrimLength = 0;
            fieldAttr17.UpdateEnable = true;
            fieldAttr17.WhereMode = true;
            fieldAttr18.CharSetNull = false;
            fieldAttr18.CheckNull = false;
            fieldAttr18.DataField = "SNDUSR";
            fieldAttr18.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr18.DefaultValue = null;
            fieldAttr18.TrimLength = 0;
            fieldAttr18.UpdateEnable = true;
            fieldAttr18.WhereMode = true;
            fieldAttr19.CharSetNull = false;
            fieldAttr19.CheckNull = false;
            fieldAttr19.DataField = "TARDAT";
            fieldAttr19.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr19.DefaultValue = null;
            fieldAttr19.TrimLength = 0;
            fieldAttr19.UpdateEnable = true;
            fieldAttr19.WhereMode = true;
            fieldAttr20.CharSetNull = false;
            fieldAttr20.CheckNull = false;
            fieldAttr20.DataField = "BATCHNO";
            fieldAttr20.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr20.DefaultValue = null;
            fieldAttr20.TrimLength = 0;
            fieldAttr20.UpdateEnable = true;
            fieldAttr20.WhereMode = true;
            fieldAttr21.CharSetNull = false;
            fieldAttr21.CheckNull = false;
            fieldAttr21.DataField = "TUSR";
            fieldAttr21.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr21.DefaultValue = null;
            fieldAttr21.TrimLength = 0;
            fieldAttr21.UpdateEnable = true;
            fieldAttr21.WhereMode = true;
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr1);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr2);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr3);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr4);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr5);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr6);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr7);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr8);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr9);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr10);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr11);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr12);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr13);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr14);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr15);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr16);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr17);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr18);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr19);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr20);
            this.ucRTLessorAVSCustDrop.FieldAttrs.Add(fieldAttr21);
            this.ucRTLessorAVSCustDrop.LogInfo = null;
            this.ucRTLessorAVSCustDrop.Name = "ucRTLessorAVSCustDrop";
            this.ucRTLessorAVSCustDrop.RowAffectsCheck = true;
            this.ucRTLessorAVSCustDrop.SelectCmd = this.RTLessorAVSCustDrop;
            this.ucRTLessorAVSCustDrop.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustDrop.SendSQLCmd = true;
            this.ucRTLessorAVSCustDrop.ServerModify = true;
            this.ucRTLessorAVSCustDrop.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustDrop.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustDrop.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustDrop.UseTranscationScope = false;
            this.ucRTLessorAVSCustDrop.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // RTLessorAVSCustDropSndwork
            // 
            this.RTLessorAVSCustDropSndwork.CacheConnection = false;
            this.RTLessorAVSCustDropSndwork.CommandText = "SELECT dbo.[RTLessorAVSCustDropSndwork].* FROM dbo.[RTLessorAVSCustDropSndwork]";
            this.RTLessorAVSCustDropSndwork.CommandTimeout = 30;
            this.RTLessorAVSCustDropSndwork.CommandType = System.Data.CommandType.Text;
            this.RTLessorAVSCustDropSndwork.DynamicTableName = false;
            this.RTLessorAVSCustDropSndwork.EEPAlias = null;
            this.RTLessorAVSCustDropSndwork.EncodingAfter = null;
            this.RTLessorAVSCustDropSndwork.EncodingBefore = "Windows-1252";
            this.RTLessorAVSCustDropSndwork.EncodingConvert = null;
            this.RTLessorAVSCustDropSndwork.InfoConnection = this.InfoConnection1;
            keyItem3.KeyName = "CUSID";
            keyItem4.KeyName = "ENTRYNO";
            keyItem5.KeyName = "PRTNO";
            this.RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem3);
            this.RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem4);
            this.RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem5);
            this.RTLessorAVSCustDropSndwork.MultiSetWhere = false;
            this.RTLessorAVSCustDropSndwork.Name = "RTLessorAVSCustDropSndwork";
            this.RTLessorAVSCustDropSndwork.NotificationAutoEnlist = false;
            this.RTLessorAVSCustDropSndwork.SecExcept = null;
            this.RTLessorAVSCustDropSndwork.SecFieldName = null;
            this.RTLessorAVSCustDropSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RTLessorAVSCustDropSndwork.SelectPaging = false;
            this.RTLessorAVSCustDropSndwork.SelectTop = 0;
            this.RTLessorAVSCustDropSndwork.SiteControl = false;
            this.RTLessorAVSCustDropSndwork.SiteFieldName = null;
            this.RTLessorAVSCustDropSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // ucRTLessorAVSCustDropSndwork
            // 
            this.ucRTLessorAVSCustDropSndwork.AutoTrans = true;
            this.ucRTLessorAVSCustDropSndwork.ExceptJoin = false;
            fieldAttr22.CharSetNull = false;
            fieldAttr22.CheckNull = false;
            fieldAttr22.DataField = "CUSID";
            fieldAttr22.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr22.DefaultValue = null;
            fieldAttr22.TrimLength = 0;
            fieldAttr22.UpdateEnable = true;
            fieldAttr22.WhereMode = true;
            fieldAttr23.CharSetNull = false;
            fieldAttr23.CheckNull = false;
            fieldAttr23.DataField = "ENTRYNO";
            fieldAttr23.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr23.DefaultValue = null;
            fieldAttr23.TrimLength = 0;
            fieldAttr23.UpdateEnable = true;
            fieldAttr23.WhereMode = true;
            fieldAttr24.CharSetNull = false;
            fieldAttr24.CheckNull = false;
            fieldAttr24.DataField = "PRTNO";
            fieldAttr24.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr24.DefaultValue = null;
            fieldAttr24.TrimLength = 0;
            fieldAttr24.UpdateEnable = true;
            fieldAttr24.WhereMode = true;
            fieldAttr25.CharSetNull = false;
            fieldAttr25.CheckNull = false;
            fieldAttr25.DataField = "SENDWORKDAT";
            fieldAttr25.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr25.DefaultValue = null;
            fieldAttr25.TrimLength = 0;
            fieldAttr25.UpdateEnable = true;
            fieldAttr25.WhereMode = true;
            fieldAttr26.CharSetNull = false;
            fieldAttr26.CheckNull = false;
            fieldAttr26.DataField = "PRTUSR";
            fieldAttr26.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr26.DefaultValue = null;
            fieldAttr26.TrimLength = 0;
            fieldAttr26.UpdateEnable = true;
            fieldAttr26.WhereMode = true;
            fieldAttr27.CharSetNull = false;
            fieldAttr27.CheckNull = false;
            fieldAttr27.DataField = "ASSIGNENGINEER";
            fieldAttr27.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr27.DefaultValue = null;
            fieldAttr27.TrimLength = 0;
            fieldAttr27.UpdateEnable = true;
            fieldAttr27.WhereMode = true;
            fieldAttr28.CharSetNull = false;
            fieldAttr28.CheckNull = false;
            fieldAttr28.DataField = "ASSIGNCONSIGNEE";
            fieldAttr28.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr28.DefaultValue = null;
            fieldAttr28.TrimLength = 0;
            fieldAttr28.UpdateEnable = true;
            fieldAttr28.WhereMode = true;
            fieldAttr29.CharSetNull = false;
            fieldAttr29.CheckNull = false;
            fieldAttr29.DataField = "REALENGINEER";
            fieldAttr29.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr29.DefaultValue = null;
            fieldAttr29.TrimLength = 0;
            fieldAttr29.UpdateEnable = true;
            fieldAttr29.WhereMode = true;
            fieldAttr30.CharSetNull = false;
            fieldAttr30.CheckNull = false;
            fieldAttr30.DataField = "REALCONSIGNEE";
            fieldAttr30.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr30.DefaultValue = null;
            fieldAttr30.TrimLength = 0;
            fieldAttr30.UpdateEnable = true;
            fieldAttr30.WhereMode = true;
            fieldAttr31.CharSetNull = false;
            fieldAttr31.CheckNull = false;
            fieldAttr31.DataField = "DROPDAT";
            fieldAttr31.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr31.DefaultValue = null;
            fieldAttr31.TrimLength = 0;
            fieldAttr31.UpdateEnable = true;
            fieldAttr31.WhereMode = true;
            fieldAttr32.CharSetNull = false;
            fieldAttr32.CheckNull = false;
            fieldAttr32.DataField = "DROPDESC";
            fieldAttr32.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr32.DefaultValue = null;
            fieldAttr32.TrimLength = 0;
            fieldAttr32.UpdateEnable = true;
            fieldAttr32.WhereMode = true;
            fieldAttr33.CharSetNull = false;
            fieldAttr33.CheckNull = false;
            fieldAttr33.DataField = "CLOSEDAT";
            fieldAttr33.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr33.DefaultValue = null;
            fieldAttr33.TrimLength = 0;
            fieldAttr33.UpdateEnable = true;
            fieldAttr33.WhereMode = true;
            fieldAttr34.CharSetNull = false;
            fieldAttr34.CheckNull = false;
            fieldAttr34.DataField = "BONUSCLOSEYM";
            fieldAttr34.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr34.DefaultValue = null;
            fieldAttr34.TrimLength = 0;
            fieldAttr34.UpdateEnable = true;
            fieldAttr34.WhereMode = true;
            fieldAttr35.CharSetNull = false;
            fieldAttr35.CheckNull = false;
            fieldAttr35.DataField = "BONUSCLOSEDAT";
            fieldAttr35.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr35.DefaultValue = null;
            fieldAttr35.TrimLength = 0;
            fieldAttr35.UpdateEnable = true;
            fieldAttr35.WhereMode = true;
            fieldAttr36.CharSetNull = false;
            fieldAttr36.CheckNull = false;
            fieldAttr36.DataField = "BONUSCLOSEUSR";
            fieldAttr36.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr36.DefaultValue = null;
            fieldAttr36.TrimLength = 0;
            fieldAttr36.UpdateEnable = true;
            fieldAttr36.WhereMode = true;
            fieldAttr37.CharSetNull = false;
            fieldAttr37.CheckNull = false;
            fieldAttr37.DataField = "BONUSFINCHK";
            fieldAttr37.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr37.DefaultValue = null;
            fieldAttr37.TrimLength = 0;
            fieldAttr37.UpdateEnable = true;
            fieldAttr37.WhereMode = true;
            fieldAttr38.CharSetNull = false;
            fieldAttr38.CheckNull = false;
            fieldAttr38.DataField = "STOCKCLOSEYM";
            fieldAttr38.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr38.DefaultValue = null;
            fieldAttr38.TrimLength = 0;
            fieldAttr38.UpdateEnable = true;
            fieldAttr38.WhereMode = true;
            fieldAttr39.CharSetNull = false;
            fieldAttr39.CheckNull = false;
            fieldAttr39.DataField = "STOCKCLOSEDAT";
            fieldAttr39.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr39.DefaultValue = null;
            fieldAttr39.TrimLength = 0;
            fieldAttr39.UpdateEnable = true;
            fieldAttr39.WhereMode = true;
            fieldAttr40.CharSetNull = false;
            fieldAttr40.CheckNull = false;
            fieldAttr40.DataField = "STOCKCLOSEUSR";
            fieldAttr40.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr40.DefaultValue = null;
            fieldAttr40.TrimLength = 0;
            fieldAttr40.UpdateEnable = true;
            fieldAttr40.WhereMode = true;
            fieldAttr41.CharSetNull = false;
            fieldAttr41.CheckNull = false;
            fieldAttr41.DataField = "STOCKFINCHK";
            fieldAttr41.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr41.DefaultValue = null;
            fieldAttr41.TrimLength = 0;
            fieldAttr41.UpdateEnable = true;
            fieldAttr41.WhereMode = true;
            fieldAttr42.CharSetNull = false;
            fieldAttr42.CheckNull = false;
            fieldAttr42.DataField = "MDF1";
            fieldAttr42.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr42.DefaultValue = null;
            fieldAttr42.TrimLength = 0;
            fieldAttr42.UpdateEnable = true;
            fieldAttr42.WhereMode = true;
            fieldAttr43.CharSetNull = false;
            fieldAttr43.CheckNull = false;
            fieldAttr43.DataField = "MDF2";
            fieldAttr43.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr43.DefaultValue = null;
            fieldAttr43.TrimLength = 0;
            fieldAttr43.UpdateEnable = true;
            fieldAttr43.WhereMode = true;
            fieldAttr44.CharSetNull = false;
            fieldAttr44.CheckNull = false;
            fieldAttr44.DataField = "HOSTNO";
            fieldAttr44.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr44.DefaultValue = null;
            fieldAttr44.TrimLength = 0;
            fieldAttr44.UpdateEnable = true;
            fieldAttr44.WhereMode = true;
            fieldAttr45.CharSetNull = false;
            fieldAttr45.CheckNull = false;
            fieldAttr45.DataField = "HOSTPORT";
            fieldAttr45.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr45.DefaultValue = null;
            fieldAttr45.TrimLength = 0;
            fieldAttr45.UpdateEnable = true;
            fieldAttr45.WhereMode = true;
            fieldAttr46.CharSetNull = false;
            fieldAttr46.CheckNull = false;
            fieldAttr46.DataField = "MEMO";
            fieldAttr46.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr46.DefaultValue = null;
            fieldAttr46.TrimLength = 0;
            fieldAttr46.UpdateEnable = true;
            fieldAttr46.WhereMode = true;
            fieldAttr47.CharSetNull = false;
            fieldAttr47.CheckNull = false;
            fieldAttr47.DataField = "PRTDAT";
            fieldAttr47.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr47.DefaultValue = null;
            fieldAttr47.TrimLength = 0;
            fieldAttr47.UpdateEnable = true;
            fieldAttr47.WhereMode = true;
            fieldAttr48.CharSetNull = false;
            fieldAttr48.CheckNull = false;
            fieldAttr48.DataField = "UNCLOSEDAT";
            fieldAttr48.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr48.DefaultValue = null;
            fieldAttr48.TrimLength = 0;
            fieldAttr48.UpdateEnable = true;
            fieldAttr48.WhereMode = true;
            fieldAttr49.CharSetNull = false;
            fieldAttr49.CheckNull = false;
            fieldAttr49.DataField = "DROPUSR";
            fieldAttr49.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr49.DefaultValue = null;
            fieldAttr49.TrimLength = 0;
            fieldAttr49.UpdateEnable = true;
            fieldAttr49.WhereMode = true;
            fieldAttr50.CharSetNull = false;
            fieldAttr50.CheckNull = false;
            fieldAttr50.DataField = "CLOSEUSR";
            fieldAttr50.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr50.DefaultValue = null;
            fieldAttr50.TrimLength = 0;
            fieldAttr50.UpdateEnable = true;
            fieldAttr50.WhereMode = true;
            fieldAttr51.CharSetNull = false;
            fieldAttr51.CheckNull = false;
            fieldAttr51.DataField = "EUSR";
            fieldAttr51.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr51.DefaultValue = null;
            fieldAttr51.TrimLength = 0;
            fieldAttr51.UpdateEnable = true;
            fieldAttr51.WhereMode = true;
            fieldAttr52.CharSetNull = false;
            fieldAttr52.CheckNull = false;
            fieldAttr52.DataField = "EDAT";
            fieldAttr52.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr52.DefaultValue = null;
            fieldAttr52.TrimLength = 0;
            fieldAttr52.UpdateEnable = true;
            fieldAttr52.WhereMode = true;
            fieldAttr53.CharSetNull = false;
            fieldAttr53.CheckNull = false;
            fieldAttr53.DataField = "UUSR";
            fieldAttr53.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr53.DefaultValue = null;
            fieldAttr53.TrimLength = 0;
            fieldAttr53.UpdateEnable = true;
            fieldAttr53.WhereMode = true;
            fieldAttr54.CharSetNull = false;
            fieldAttr54.CheckNull = false;
            fieldAttr54.DataField = "UDAT";
            fieldAttr54.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr54.DefaultValue = null;
            fieldAttr54.TrimLength = 0;
            fieldAttr54.UpdateEnable = true;
            fieldAttr54.WhereMode = true;
            fieldAttr55.CharSetNull = false;
            fieldAttr55.CheckNull = false;
            fieldAttr55.DataField = "BATCHNO";
            fieldAttr55.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr55.DefaultValue = null;
            fieldAttr55.TrimLength = 0;
            fieldAttr55.UpdateEnable = true;
            fieldAttr55.WhereMode = true;
            fieldAttr56.CharSetNull = false;
            fieldAttr56.CheckNull = false;
            fieldAttr56.DataField = "CDAT";
            fieldAttr56.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr56.DefaultValue = null;
            fieldAttr56.TrimLength = 0;
            fieldAttr56.UpdateEnable = true;
            fieldAttr56.WhereMode = true;
            fieldAttr57.CharSetNull = false;
            fieldAttr57.CheckNull = false;
            fieldAttr57.DataField = "MAXENTRYNO";
            fieldAttr57.DefaultMode = Srvtools.DefaultModeType.Insert;
            fieldAttr57.DefaultValue = null;
            fieldAttr57.TrimLength = 0;
            fieldAttr57.UpdateEnable = true;
            fieldAttr57.WhereMode = true;
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr22);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr23);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr24);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr25);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr26);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr27);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr28);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr29);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr30);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr31);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr32);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr33);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr34);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr35);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr36);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr37);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr38);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr39);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr40);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr41);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr42);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr43);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr44);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr45);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr46);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr47);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr48);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr49);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr50);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr51);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr52);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr53);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr54);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr55);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr56);
            this.ucRTLessorAVSCustDropSndwork.FieldAttrs.Add(fieldAttr57);
            this.ucRTLessorAVSCustDropSndwork.LogInfo = null;
            this.ucRTLessorAVSCustDropSndwork.Name = "ucRTLessorAVSCustDropSndwork";
            this.ucRTLessorAVSCustDropSndwork.RowAffectsCheck = true;
            this.ucRTLessorAVSCustDropSndwork.SelectCmd = this.RTLessorAVSCustDropSndwork;
            this.ucRTLessorAVSCustDropSndwork.SelectCmdForUpdate = null;
            this.ucRTLessorAVSCustDropSndwork.SendSQLCmd = true;
            this.ucRTLessorAVSCustDropSndwork.ServerModify = true;
            this.ucRTLessorAVSCustDropSndwork.ServerModifyGetMax = false;
            this.ucRTLessorAVSCustDropSndwork.TranscationScopeTimeOut = System.TimeSpan.Parse("00:02:00");
            this.ucRTLessorAVSCustDropSndwork.TransIsolationLevel = System.Data.IsolationLevel.ReadCommitted;
            this.ucRTLessorAVSCustDropSndwork.UseTranscationScope = false;
            this.ucRTLessorAVSCustDropSndwork.WhereMode = Srvtools.WhereModeType.Keyfields;
            // 
            // View_RTLessorAVSCustDrop
            // 
            this.View_RTLessorAVSCustDrop.CacheConnection = false;
            this.View_RTLessorAVSCustDrop.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustDrop]";
            this.View_RTLessorAVSCustDrop.CommandTimeout = 30;
            this.View_RTLessorAVSCustDrop.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustDrop.DynamicTableName = false;
            this.View_RTLessorAVSCustDrop.EEPAlias = null;
            this.View_RTLessorAVSCustDrop.EncodingAfter = null;
            this.View_RTLessorAVSCustDrop.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustDrop.EncodingConvert = null;
            this.View_RTLessorAVSCustDrop.InfoConnection = this.InfoConnection1;
            keyItem6.KeyName = "CUSID";
            keyItem7.KeyName = "ENTRYNO";
            this.View_RTLessorAVSCustDrop.KeyFields.Add(keyItem6);
            this.View_RTLessorAVSCustDrop.KeyFields.Add(keyItem7);
            this.View_RTLessorAVSCustDrop.MultiSetWhere = false;
            this.View_RTLessorAVSCustDrop.Name = "View_RTLessorAVSCustDrop";
            this.View_RTLessorAVSCustDrop.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustDrop.SecExcept = null;
            this.View_RTLessorAVSCustDrop.SecFieldName = null;
            this.View_RTLessorAVSCustDrop.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustDrop.SelectPaging = false;
            this.View_RTLessorAVSCustDrop.SelectTop = 0;
            this.View_RTLessorAVSCustDrop.SiteControl = false;
            this.View_RTLessorAVSCustDrop.SiteFieldName = null;
            this.View_RTLessorAVSCustDrop.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // View_RTLessorAVSCustDropSndwork
            // 
            this.View_RTLessorAVSCustDropSndwork.CacheConnection = false;
            this.View_RTLessorAVSCustDropSndwork.CommandText = "SELECT * FROM dbo.[RTLessorAVSCustDropSndwork]";
            this.View_RTLessorAVSCustDropSndwork.CommandTimeout = 30;
            this.View_RTLessorAVSCustDropSndwork.CommandType = System.Data.CommandType.Text;
            this.View_RTLessorAVSCustDropSndwork.DynamicTableName = false;
            this.View_RTLessorAVSCustDropSndwork.EEPAlias = null;
            this.View_RTLessorAVSCustDropSndwork.EncodingAfter = null;
            this.View_RTLessorAVSCustDropSndwork.EncodingBefore = "Windows-1252";
            this.View_RTLessorAVSCustDropSndwork.EncodingConvert = null;
            this.View_RTLessorAVSCustDropSndwork.InfoConnection = this.InfoConnection1;
            keyItem8.KeyName = "CUSID";
            keyItem9.KeyName = "ENTRYNO";
            keyItem10.KeyName = "PRTNO";
            this.View_RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem8);
            this.View_RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem9);
            this.View_RTLessorAVSCustDropSndwork.KeyFields.Add(keyItem10);
            this.View_RTLessorAVSCustDropSndwork.MultiSetWhere = false;
            this.View_RTLessorAVSCustDropSndwork.Name = "View_RTLessorAVSCustDropSndwork";
            this.View_RTLessorAVSCustDropSndwork.NotificationAutoEnlist = false;
            this.View_RTLessorAVSCustDropSndwork.SecExcept = null;
            this.View_RTLessorAVSCustDropSndwork.SecFieldName = null;
            this.View_RTLessorAVSCustDropSndwork.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.View_RTLessorAVSCustDropSndwork.SelectPaging = false;
            this.View_RTLessorAVSCustDropSndwork.SelectTop = 0;
            this.View_RTLessorAVSCustDropSndwork.SiteControl = false;
            this.View_RTLessorAVSCustDropSndwork.SiteFieldName = null;
            this.View_RTLessorAVSCustDropSndwork.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // RT10451
            // 
            this.RT10451.CacheConnection = false;
            this.RT10451.CommandText = resources.GetString("RT10451.CommandText");
            this.RT10451.CommandTimeout = 30;
            this.RT10451.CommandType = System.Data.CommandType.Text;
            this.RT10451.DynamicTableName = false;
            this.RT10451.EEPAlias = null;
            this.RT10451.EncodingAfter = null;
            this.RT10451.EncodingBefore = "Windows-1252";
            this.RT10451.EncodingConvert = null;
            this.RT10451.InfoConnection = this.InfoConnection1;
            keyItem11.KeyName = "CUSID";
            keyItem12.KeyName = "ENTRYNO";
            this.RT10451.KeyFields.Add(keyItem11);
            this.RT10451.KeyFields.Add(keyItem12);
            this.RT10451.MultiSetWhere = false;
            this.RT10451.Name = "RT10451";
            this.RT10451.NotificationAutoEnlist = false;
            this.RT10451.SecExcept = null;
            this.RT10451.SecFieldName = null;
            this.RT10451.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.RT10451.SelectPaging = false;
            this.RT10451.SelectTop = 0;
            this.RT10451.SiteControl = false;
            this.RT10451.SiteFieldName = null;
            this.RT10451.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10451
            // 
            this.cmdRT10451.CacheConnection = false;
            this.cmdRT10451.CommandText = "usp_RTLessorAVSCustdropSndworkF";
            this.cmdRT10451.CommandTimeout = 30;
            this.cmdRT10451.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10451.DynamicTableName = false;
            this.cmdRT10451.EEPAlias = null;
            this.cmdRT10451.EncodingAfter = null;
            this.cmdRT10451.EncodingBefore = "Windows-1252";
            this.cmdRT10451.EncodingConvert = null;
            this.cmdRT10451.InfoConnection = this.InfoConnection1;
            infoParameter1.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter1.ParameterName = "cusid";
            infoParameter1.Precision = ((byte)(0));
            infoParameter1.Scale = ((byte)(0));
            infoParameter1.Size = 15;
            infoParameter1.SourceColumn = null;
            infoParameter1.XmlSchemaCollectionDatabase = null;
            infoParameter1.XmlSchemaCollectionName = null;
            infoParameter1.XmlSchemaCollectionOwningSchema = null;
            infoParameter2.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter2.ParameterName = "entryno";
            infoParameter2.Precision = ((byte)(0));
            infoParameter2.Scale = ((byte)(0));
            infoParameter2.Size = 0;
            infoParameter2.SourceColumn = null;
            infoParameter2.XmlSchemaCollectionDatabase = null;
            infoParameter2.XmlSchemaCollectionName = null;
            infoParameter2.XmlSchemaCollectionOwningSchema = null;
            infoParameter3.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter3.ParameterName = "prtno";
            infoParameter3.Precision = ((byte)(0));
            infoParameter3.Scale = ((byte)(0));
            infoParameter3.Size = 12;
            infoParameter3.SourceColumn = null;
            infoParameter3.XmlSchemaCollectionDatabase = null;
            infoParameter3.XmlSchemaCollectionName = null;
            infoParameter3.XmlSchemaCollectionOwningSchema = null;
            infoParameter4.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter4.ParameterName = "usr";
            infoParameter4.Precision = ((byte)(0));
            infoParameter4.Scale = ((byte)(0));
            infoParameter4.Size = 6;
            infoParameter4.SourceColumn = null;
            infoParameter4.XmlSchemaCollectionDatabase = null;
            infoParameter4.XmlSchemaCollectionName = null;
            infoParameter4.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10451.InfoParameters.Add(infoParameter1);
            this.cmdRT10451.InfoParameters.Add(infoParameter2);
            this.cmdRT10451.InfoParameters.Add(infoParameter3);
            this.cmdRT10451.InfoParameters.Add(infoParameter4);
            this.cmdRT10451.MultiSetWhere = false;
            this.cmdRT10451.Name = "cmdRT10451";
            this.cmdRT10451.NotificationAutoEnlist = false;
            this.cmdRT10451.SecExcept = null;
            this.cmdRT10451.SecFieldName = null;
            this.cmdRT10451.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10451.SelectPaging = false;
            this.cmdRT10451.SelectTop = 0;
            this.cmdRT10451.SiteControl = false;
            this.cmdRT10451.SiteFieldName = null;
            this.cmdRT10451.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10452
            // 
            this.cmdRT10452.CacheConnection = false;
            this.cmdRT10452.CommandText = "usp_RTLessorAVSCustDROPSndworkUF";
            this.cmdRT10452.CommandTimeout = 30;
            this.cmdRT10452.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10452.DynamicTableName = false;
            this.cmdRT10452.EEPAlias = null;
            this.cmdRT10452.EncodingAfter = null;
            this.cmdRT10452.EncodingBefore = "Windows-1252";
            this.cmdRT10452.EncodingConvert = null;
            this.cmdRT10452.InfoConnection = this.InfoConnection1;
            infoParameter5.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter5.ParameterName = "cusid";
            infoParameter5.Precision = ((byte)(0));
            infoParameter5.Scale = ((byte)(0));
            infoParameter5.Size = 15;
            infoParameter5.SourceColumn = null;
            infoParameter5.XmlSchemaCollectionDatabase = null;
            infoParameter5.XmlSchemaCollectionName = null;
            infoParameter5.XmlSchemaCollectionOwningSchema = null;
            infoParameter6.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter6.ParameterName = "entryno";
            infoParameter6.Precision = ((byte)(0));
            infoParameter6.Scale = ((byte)(0));
            infoParameter6.Size = 0;
            infoParameter6.SourceColumn = null;
            infoParameter6.XmlSchemaCollectionDatabase = null;
            infoParameter6.XmlSchemaCollectionName = null;
            infoParameter6.XmlSchemaCollectionOwningSchema = null;
            infoParameter7.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter7.ParameterName = "prtno";
            infoParameter7.Precision = ((byte)(0));
            infoParameter7.Scale = ((byte)(0));
            infoParameter7.Size = 12;
            infoParameter7.SourceColumn = null;
            infoParameter7.XmlSchemaCollectionDatabase = null;
            infoParameter7.XmlSchemaCollectionName = null;
            infoParameter7.XmlSchemaCollectionOwningSchema = null;
            infoParameter8.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter8.ParameterName = "usr";
            infoParameter8.Precision = ((byte)(0));
            infoParameter8.Scale = ((byte)(0));
            infoParameter8.Size = 6;
            infoParameter8.SourceColumn = null;
            infoParameter8.XmlSchemaCollectionDatabase = null;
            infoParameter8.XmlSchemaCollectionName = null;
            infoParameter8.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10452.InfoParameters.Add(infoParameter5);
            this.cmdRT10452.InfoParameters.Add(infoParameter6);
            this.cmdRT10452.InfoParameters.Add(infoParameter7);
            this.cmdRT10452.InfoParameters.Add(infoParameter8);
            this.cmdRT10452.MultiSetWhere = false;
            this.cmdRT10452.Name = "cmdRT10452";
            this.cmdRT10452.NotificationAutoEnlist = false;
            this.cmdRT10452.SecExcept = null;
            this.cmdRT10452.SecFieldName = null;
            this.cmdRT10452.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10452.SelectPaging = false;
            this.cmdRT10452.SelectTop = 0;
            this.cmdRT10452.SiteControl = false;
            this.cmdRT10452.SiteFieldName = null;
            this.cmdRT10452.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10453
            // 
            this.cmdRT10453.CacheConnection = false;
            this.cmdRT10453.CommandText = "usp_RTLessorAVSCustDROPSndworkFR";
            this.cmdRT10453.CommandTimeout = 30;
            this.cmdRT10453.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10453.DynamicTableName = false;
            this.cmdRT10453.EEPAlias = null;
            this.cmdRT10453.EncodingAfter = null;
            this.cmdRT10453.EncodingBefore = "Windows-1252";
            this.cmdRT10453.EncodingConvert = null;
            this.cmdRT10453.InfoConnection = this.InfoConnection1;
            infoParameter9.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter9.ParameterName = "cusid";
            infoParameter9.Precision = ((byte)(0));
            infoParameter9.Scale = ((byte)(0));
            infoParameter9.Size = 15;
            infoParameter9.SourceColumn = null;
            infoParameter9.XmlSchemaCollectionDatabase = null;
            infoParameter9.XmlSchemaCollectionName = null;
            infoParameter9.XmlSchemaCollectionOwningSchema = null;
            infoParameter10.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter10.ParameterName = "entryno";
            infoParameter10.Precision = ((byte)(0));
            infoParameter10.Scale = ((byte)(0));
            infoParameter10.Size = 0;
            infoParameter10.SourceColumn = null;
            infoParameter10.XmlSchemaCollectionDatabase = null;
            infoParameter10.XmlSchemaCollectionName = null;
            infoParameter10.XmlSchemaCollectionOwningSchema = null;
            infoParameter11.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter11.ParameterName = "prtno";
            infoParameter11.Precision = ((byte)(0));
            infoParameter11.Scale = ((byte)(0));
            infoParameter11.Size = 12;
            infoParameter11.SourceColumn = null;
            infoParameter11.XmlSchemaCollectionDatabase = null;
            infoParameter11.XmlSchemaCollectionName = null;
            infoParameter11.XmlSchemaCollectionOwningSchema = null;
            infoParameter12.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter12.ParameterName = "usr";
            infoParameter12.Precision = ((byte)(0));
            infoParameter12.Scale = ((byte)(0));
            infoParameter12.Size = 6;
            infoParameter12.SourceColumn = null;
            infoParameter12.XmlSchemaCollectionDatabase = null;
            infoParameter12.XmlSchemaCollectionName = null;
            infoParameter12.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10453.InfoParameters.Add(infoParameter9);
            this.cmdRT10453.InfoParameters.Add(infoParameter10);
            this.cmdRT10453.InfoParameters.Add(infoParameter11);
            this.cmdRT10453.InfoParameters.Add(infoParameter12);
            this.cmdRT10453.MultiSetWhere = false;
            this.cmdRT10453.Name = "cmdRT10453";
            this.cmdRT10453.NotificationAutoEnlist = false;
            this.cmdRT10453.SecExcept = null;
            this.cmdRT10453.SecFieldName = null;
            this.cmdRT10453.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10453.SelectPaging = false;
            this.cmdRT10453.SelectTop = 0;
            this.cmdRT10453.SiteControl = false;
            this.cmdRT10453.SiteFieldName = null;
            this.cmdRT10453.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10455
            // 
            this.cmdRT10455.CacheConnection = false;
            this.cmdRT10455.CommandText = "usp_RTLessorAVSCustDROPSndworkDropC";
            this.cmdRT10455.CommandTimeout = 30;
            this.cmdRT10455.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10455.DynamicTableName = false;
            this.cmdRT10455.EEPAlias = null;
            this.cmdRT10455.EncodingAfter = null;
            this.cmdRT10455.EncodingBefore = "Windows-1252";
            this.cmdRT10455.EncodingConvert = null;
            this.cmdRT10455.InfoConnection = this.InfoConnection1;
            infoParameter13.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter13.ParameterName = "cusid";
            infoParameter13.Precision = ((byte)(0));
            infoParameter13.Scale = ((byte)(0));
            infoParameter13.Size = 15;
            infoParameter13.SourceColumn = null;
            infoParameter13.XmlSchemaCollectionDatabase = null;
            infoParameter13.XmlSchemaCollectionName = null;
            infoParameter13.XmlSchemaCollectionOwningSchema = null;
            infoParameter14.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter14.ParameterName = "entryno";
            infoParameter14.Precision = ((byte)(0));
            infoParameter14.Scale = ((byte)(0));
            infoParameter14.Size = 0;
            infoParameter14.SourceColumn = null;
            infoParameter14.XmlSchemaCollectionDatabase = null;
            infoParameter14.XmlSchemaCollectionName = null;
            infoParameter14.XmlSchemaCollectionOwningSchema = null;
            infoParameter15.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter15.ParameterName = "prtno";
            infoParameter15.Precision = ((byte)(0));
            infoParameter15.Scale = ((byte)(0));
            infoParameter15.Size = 12;
            infoParameter15.SourceColumn = null;
            infoParameter15.XmlSchemaCollectionDatabase = null;
            infoParameter15.XmlSchemaCollectionName = null;
            infoParameter15.XmlSchemaCollectionOwningSchema = null;
            infoParameter16.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter16.ParameterName = "usr";
            infoParameter16.Precision = ((byte)(0));
            infoParameter16.Scale = ((byte)(0));
            infoParameter16.Size = 6;
            infoParameter16.SourceColumn = null;
            infoParameter16.XmlSchemaCollectionDatabase = null;
            infoParameter16.XmlSchemaCollectionName = null;
            infoParameter16.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10455.InfoParameters.Add(infoParameter13);
            this.cmdRT10455.InfoParameters.Add(infoParameter14);
            this.cmdRT10455.InfoParameters.Add(infoParameter15);
            this.cmdRT10455.InfoParameters.Add(infoParameter16);
            this.cmdRT10455.MultiSetWhere = false;
            this.cmdRT10455.Name = "cmdRT10455";
            this.cmdRT10455.NotificationAutoEnlist = false;
            this.cmdRT10455.SecExcept = null;
            this.cmdRT10455.SecFieldName = null;
            this.cmdRT10455.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10455.SelectPaging = false;
            this.cmdRT10455.SelectTop = 0;
            this.cmdRT10455.SiteControl = false;
            this.cmdRT10455.SiteFieldName = null;
            this.cmdRT10455.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10454
            // 
            this.cmdRT10454.CacheConnection = false;
            this.cmdRT10454.CommandText = "usp_RTLessorAVSCustDROPSndworkDrop";
            this.cmdRT10454.CommandTimeout = 30;
            this.cmdRT10454.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10454.DynamicTableName = false;
            this.cmdRT10454.EEPAlias = null;
            this.cmdRT10454.EncodingAfter = null;
            this.cmdRT10454.EncodingBefore = "Windows-1252";
            this.cmdRT10454.EncodingConvert = null;
            this.cmdRT10454.InfoConnection = this.InfoConnection1;
            infoParameter17.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter17.ParameterName = "cusid";
            infoParameter17.Precision = ((byte)(0));
            infoParameter17.Scale = ((byte)(0));
            infoParameter17.Size = 15;
            infoParameter17.SourceColumn = null;
            infoParameter17.XmlSchemaCollectionDatabase = null;
            infoParameter17.XmlSchemaCollectionName = null;
            infoParameter17.XmlSchemaCollectionOwningSchema = null;
            infoParameter18.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter18.ParameterName = "entryno";
            infoParameter18.Precision = ((byte)(0));
            infoParameter18.Scale = ((byte)(0));
            infoParameter18.Size = 0;
            infoParameter18.SourceColumn = null;
            infoParameter18.XmlSchemaCollectionDatabase = null;
            infoParameter18.XmlSchemaCollectionName = null;
            infoParameter18.XmlSchemaCollectionOwningSchema = null;
            infoParameter19.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter19.ParameterName = "prtno";
            infoParameter19.Precision = ((byte)(0));
            infoParameter19.Scale = ((byte)(0));
            infoParameter19.Size = 12;
            infoParameter19.SourceColumn = null;
            infoParameter19.XmlSchemaCollectionDatabase = null;
            infoParameter19.XmlSchemaCollectionName = null;
            infoParameter19.XmlSchemaCollectionOwningSchema = null;
            infoParameter20.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter20.ParameterName = "usr";
            infoParameter20.Precision = ((byte)(0));
            infoParameter20.Scale = ((byte)(0));
            infoParameter20.Size = 6;
            infoParameter20.SourceColumn = null;
            infoParameter20.XmlSchemaCollectionDatabase = null;
            infoParameter20.XmlSchemaCollectionName = null;
            infoParameter20.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10454.InfoParameters.Add(infoParameter17);
            this.cmdRT10454.InfoParameters.Add(infoParameter18);
            this.cmdRT10454.InfoParameters.Add(infoParameter19);
            this.cmdRT10454.InfoParameters.Add(infoParameter20);
            this.cmdRT10454.MultiSetWhere = false;
            this.cmdRT10454.Name = "cmdRT10454";
            this.cmdRT10454.NotificationAutoEnlist = false;
            this.cmdRT10454.SecExcept = null;
            this.cmdRT10454.SecFieldName = null;
            this.cmdRT10454.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10454.SelectPaging = false;
            this.cmdRT10454.SelectTop = 0;
            this.cmdRT10454.SiteControl = false;
            this.cmdRT10454.SiteFieldName = null;
            this.cmdRT10454.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10456
            // 
            this.cmdRT10456.CacheConnection = false;
            this.cmdRT10456.CommandText = "usp_RTLessorAVSCustDROPF";
            this.cmdRT10456.CommandTimeout = 30;
            this.cmdRT10456.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10456.DynamicTableName = false;
            this.cmdRT10456.EEPAlias = null;
            this.cmdRT10456.EncodingAfter = null;
            this.cmdRT10456.EncodingBefore = "Windows-1252";
            this.cmdRT10456.EncodingConvert = null;
            this.cmdRT10456.InfoConnection = this.InfoConnection1;
            infoParameter21.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter21.ParameterName = "cusid";
            infoParameter21.Precision = ((byte)(0));
            infoParameter21.Scale = ((byte)(0));
            infoParameter21.Size = 15;
            infoParameter21.SourceColumn = null;
            infoParameter21.XmlSchemaCollectionDatabase = null;
            infoParameter21.XmlSchemaCollectionName = null;
            infoParameter21.XmlSchemaCollectionOwningSchema = null;
            infoParameter22.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter22.ParameterName = "entryno";
            infoParameter22.Precision = ((byte)(0));
            infoParameter22.Scale = ((byte)(0));
            infoParameter22.Size = 0;
            infoParameter22.SourceColumn = null;
            infoParameter22.XmlSchemaCollectionDatabase = null;
            infoParameter22.XmlSchemaCollectionName = null;
            infoParameter22.XmlSchemaCollectionOwningSchema = null;
            infoParameter23.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter23.ParameterName = "usr";
            infoParameter23.Precision = ((byte)(0));
            infoParameter23.Scale = ((byte)(0));
            infoParameter23.Size = 6;
            infoParameter23.SourceColumn = null;
            infoParameter23.XmlSchemaCollectionDatabase = null;
            infoParameter23.XmlSchemaCollectionName = null;
            infoParameter23.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10456.InfoParameters.Add(infoParameter21);
            this.cmdRT10456.InfoParameters.Add(infoParameter22);
            this.cmdRT10456.InfoParameters.Add(infoParameter23);
            this.cmdRT10456.MultiSetWhere = false;
            this.cmdRT10456.Name = "cmdRT10456";
            this.cmdRT10456.NotificationAutoEnlist = false;
            this.cmdRT10456.SecExcept = null;
            this.cmdRT10456.SecFieldName = null;
            this.cmdRT10456.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10456.SelectPaging = false;
            this.cmdRT10456.SelectTop = 0;
            this.cmdRT10456.SiteControl = false;
            this.cmdRT10456.SiteFieldName = null;
            this.cmdRT10456.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10457
            // 
            this.cmdRT10457.CacheConnection = false;
            this.cmdRT10457.CommandText = "usp_RTLessorAVSCustDROPFR";
            this.cmdRT10457.CommandTimeout = 30;
            this.cmdRT10457.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10457.DynamicTableName = false;
            this.cmdRT10457.EEPAlias = null;
            this.cmdRT10457.EncodingAfter = null;
            this.cmdRT10457.EncodingBefore = "Windows-1252";
            this.cmdRT10457.EncodingConvert = null;
            this.cmdRT10457.InfoConnection = this.InfoConnection1;
            infoParameter24.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter24.ParameterName = "cusid";
            infoParameter24.Precision = ((byte)(0));
            infoParameter24.Scale = ((byte)(0));
            infoParameter24.Size = 15;
            infoParameter24.SourceColumn = null;
            infoParameter24.XmlSchemaCollectionDatabase = null;
            infoParameter24.XmlSchemaCollectionName = null;
            infoParameter24.XmlSchemaCollectionOwningSchema = null;
            infoParameter25.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter25.ParameterName = "entryno";
            infoParameter25.Precision = ((byte)(0));
            infoParameter25.Scale = ((byte)(0));
            infoParameter25.Size = 0;
            infoParameter25.SourceColumn = null;
            infoParameter25.XmlSchemaCollectionDatabase = null;
            infoParameter25.XmlSchemaCollectionName = null;
            infoParameter25.XmlSchemaCollectionOwningSchema = null;
            infoParameter26.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter26.ParameterName = "usr";
            infoParameter26.Precision = ((byte)(0));
            infoParameter26.Scale = ((byte)(0));
            infoParameter26.Size = 6;
            infoParameter26.SourceColumn = null;
            infoParameter26.XmlSchemaCollectionDatabase = null;
            infoParameter26.XmlSchemaCollectionName = null;
            infoParameter26.XmlSchemaCollectionOwningSchema = null;
            infoParameter27.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter27.ParameterName = "batchnoxx";
            infoParameter27.Precision = ((byte)(0));
            infoParameter27.Scale = ((byte)(0));
            infoParameter27.Size = 12;
            infoParameter27.SourceColumn = null;
            infoParameter27.XmlSchemaCollectionDatabase = null;
            infoParameter27.XmlSchemaCollectionName = null;
            infoParameter27.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10457.InfoParameters.Add(infoParameter24);
            this.cmdRT10457.InfoParameters.Add(infoParameter25);
            this.cmdRT10457.InfoParameters.Add(infoParameter26);
            this.cmdRT10457.InfoParameters.Add(infoParameter27);
            this.cmdRT10457.MultiSetWhere = false;
            this.cmdRT10457.Name = "cmdRT10457";
            this.cmdRT10457.NotificationAutoEnlist = false;
            this.cmdRT10457.SecExcept = null;
            this.cmdRT10457.SecFieldName = null;
            this.cmdRT10457.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10457.SelectPaging = false;
            this.cmdRT10457.SelectTop = 0;
            this.cmdRT10457.SiteControl = false;
            this.cmdRT10457.SiteFieldName = null;
            this.cmdRT10457.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10458
            // 
            this.cmdRT10458.CacheConnection = false;
            this.cmdRT10458.CommandText = "usp_RTLessorAVSCustdropDrop";
            this.cmdRT10458.CommandTimeout = 30;
            this.cmdRT10458.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10458.DynamicTableName = false;
            this.cmdRT10458.EEPAlias = null;
            this.cmdRT10458.EncodingAfter = null;
            this.cmdRT10458.EncodingBefore = "Windows-1252";
            this.cmdRT10458.EncodingConvert = null;
            this.cmdRT10458.InfoConnection = this.InfoConnection1;
            infoParameter28.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter28.ParameterName = "cusid";
            infoParameter28.Precision = ((byte)(0));
            infoParameter28.Scale = ((byte)(0));
            infoParameter28.Size = 15;
            infoParameter28.SourceColumn = null;
            infoParameter28.XmlSchemaCollectionDatabase = null;
            infoParameter28.XmlSchemaCollectionName = null;
            infoParameter28.XmlSchemaCollectionOwningSchema = null;
            infoParameter29.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter29.ParameterName = "entryno";
            infoParameter29.Precision = ((byte)(0));
            infoParameter29.Scale = ((byte)(0));
            infoParameter29.Size = 0;
            infoParameter29.SourceColumn = null;
            infoParameter29.XmlSchemaCollectionDatabase = null;
            infoParameter29.XmlSchemaCollectionName = null;
            infoParameter29.XmlSchemaCollectionOwningSchema = null;
            infoParameter30.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter30.ParameterName = "usr";
            infoParameter30.Precision = ((byte)(0));
            infoParameter30.Scale = ((byte)(0));
            infoParameter30.Size = 6;
            infoParameter30.SourceColumn = null;
            infoParameter30.XmlSchemaCollectionDatabase = null;
            infoParameter30.XmlSchemaCollectionName = null;
            infoParameter30.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10458.InfoParameters.Add(infoParameter28);
            this.cmdRT10458.InfoParameters.Add(infoParameter29);
            this.cmdRT10458.InfoParameters.Add(infoParameter30);
            this.cmdRT10458.MultiSetWhere = false;
            this.cmdRT10458.Name = "cmdRT10458";
            this.cmdRT10458.NotificationAutoEnlist = false;
            this.cmdRT10458.SecExcept = null;
            this.cmdRT10458.SecFieldName = null;
            this.cmdRT10458.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10458.SelectPaging = false;
            this.cmdRT10458.SelectTop = 0;
            this.cmdRT10458.SiteControl = false;
            this.cmdRT10458.SiteFieldName = null;
            this.cmdRT10458.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT10459
            // 
            this.cmdRT10459.CacheConnection = false;
            this.cmdRT10459.CommandText = "usp_RTLessorAVSCustdropDropC";
            this.cmdRT10459.CommandTimeout = 30;
            this.cmdRT10459.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT10459.DynamicTableName = false;
            this.cmdRT10459.EEPAlias = null;
            this.cmdRT10459.EncodingAfter = null;
            this.cmdRT10459.EncodingBefore = "Windows-1252";
            this.cmdRT10459.EncodingConvert = null;
            this.cmdRT10459.InfoConnection = this.InfoConnection1;
            infoParameter31.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter31.ParameterName = "cusid";
            infoParameter31.Precision = ((byte)(0));
            infoParameter31.Scale = ((byte)(0));
            infoParameter31.Size = 15;
            infoParameter31.SourceColumn = null;
            infoParameter31.XmlSchemaCollectionDatabase = null;
            infoParameter31.XmlSchemaCollectionName = null;
            infoParameter31.XmlSchemaCollectionOwningSchema = null;
            infoParameter32.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter32.ParameterName = "entryno";
            infoParameter32.Precision = ((byte)(0));
            infoParameter32.Scale = ((byte)(0));
            infoParameter32.Size = 0;
            infoParameter32.SourceColumn = null;
            infoParameter32.XmlSchemaCollectionDatabase = null;
            infoParameter32.XmlSchemaCollectionName = null;
            infoParameter32.XmlSchemaCollectionOwningSchema = null;
            infoParameter33.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter33.ParameterName = "usr";
            infoParameter33.Precision = ((byte)(0));
            infoParameter33.Scale = ((byte)(0));
            infoParameter33.Size = 6;
            infoParameter33.SourceColumn = null;
            infoParameter33.XmlSchemaCollectionDatabase = null;
            infoParameter33.XmlSchemaCollectionName = null;
            infoParameter33.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT10459.InfoParameters.Add(infoParameter31);
            this.cmdRT10459.InfoParameters.Add(infoParameter32);
            this.cmdRT10459.InfoParameters.Add(infoParameter33);
            this.cmdRT10459.MultiSetWhere = false;
            this.cmdRT10459.Name = "cmdRT10459";
            this.cmdRT10459.NotificationAutoEnlist = false;
            this.cmdRT10459.SecExcept = null;
            this.cmdRT10459.SecFieldName = null;
            this.cmdRT10459.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT10459.SelectPaging = false;
            this.cmdRT10459.SelectTop = 0;
            this.cmdRT10459.SiteControl = false;
            this.cmdRT10459.SiteFieldName = null;
            this.cmdRT10459.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmdRT1045A
            // 
            this.cmdRT1045A.CacheConnection = false;
            this.cmdRT1045A.CommandText = "usp_RTLessorAVSCustdropTRNSndwork";
            this.cmdRT1045A.CommandTimeout = 30;
            this.cmdRT1045A.CommandType = System.Data.CommandType.StoredProcedure;
            this.cmdRT1045A.DynamicTableName = false;
            this.cmdRT1045A.EEPAlias = null;
            this.cmdRT1045A.EncodingAfter = null;
            this.cmdRT1045A.EncodingBefore = "Windows-1252";
            this.cmdRT1045A.EncodingConvert = null;
            this.cmdRT1045A.InfoConnection = this.InfoConnection1;
            infoParameter34.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter34.ParameterName = "cusid";
            infoParameter34.Precision = ((byte)(0));
            infoParameter34.Scale = ((byte)(0));
            infoParameter34.Size = 15;
            infoParameter34.SourceColumn = null;
            infoParameter34.XmlSchemaCollectionDatabase = null;
            infoParameter34.XmlSchemaCollectionName = null;
            infoParameter34.XmlSchemaCollectionOwningSchema = null;
            infoParameter35.InfoDbType = Srvtools.InfoDbType.Int;
            infoParameter35.ParameterName = "entryno";
            infoParameter35.Precision = ((byte)(0));
            infoParameter35.Scale = ((byte)(0));
            infoParameter35.Size = 0;
            infoParameter35.SourceColumn = null;
            infoParameter35.XmlSchemaCollectionDatabase = null;
            infoParameter35.XmlSchemaCollectionName = null;
            infoParameter35.XmlSchemaCollectionOwningSchema = null;
            infoParameter36.InfoDbType = Srvtools.InfoDbType.VarChar;
            infoParameter36.ParameterName = "usr";
            infoParameter36.Precision = ((byte)(0));
            infoParameter36.Scale = ((byte)(0));
            infoParameter36.Size = 6;
            infoParameter36.SourceColumn = null;
            infoParameter36.XmlSchemaCollectionDatabase = null;
            infoParameter36.XmlSchemaCollectionName = null;
            infoParameter36.XmlSchemaCollectionOwningSchema = null;
            this.cmdRT1045A.InfoParameters.Add(infoParameter34);
            this.cmdRT1045A.InfoParameters.Add(infoParameter35);
            this.cmdRT1045A.InfoParameters.Add(infoParameter36);
            this.cmdRT1045A.MultiSetWhere = false;
            this.cmdRT1045A.Name = "cmdRT1045A";
            this.cmdRT1045A.NotificationAutoEnlist = false;
            this.cmdRT1045A.SecExcept = null;
            this.cmdRT1045A.SecFieldName = null;
            this.cmdRT1045A.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmdRT1045A.SelectPaging = false;
            this.cmdRT1045A.SelectTop = 0;
            this.cmdRT1045A.SiteControl = false;
            this.cmdRT1045A.SiteFieldName = null;
            this.cmdRT1045A.UpdatedRowSource = System.Data.UpdateRowSource.None;
            // 
            // cmd
            // 
            this.cmd.CacheConnection = false;
            this.cmd.CommandText = "";
            this.cmd.CommandTimeout = 30;
            this.cmd.CommandType = System.Data.CommandType.Text;
            this.cmd.DynamicTableName = false;
            this.cmd.EEPAlias = null;
            this.cmd.EncodingAfter = null;
            this.cmd.EncodingBefore = "Windows-1252";
            this.cmd.EncodingConvert = null;
            this.cmd.InfoConnection = this.InfoConnection1;
            this.cmd.MultiSetWhere = false;
            this.cmd.Name = "cmd";
            this.cmd.NotificationAutoEnlist = false;
            this.cmd.SecExcept = null;
            this.cmd.SecFieldName = null;
            this.cmd.SecStyle = Srvtools.SecurityStyle.ssByNone;
            this.cmd.SelectPaging = false;
            this.cmd.SelectTop = 0;
            this.cmd.SiteControl = false;
            this.cmd.SiteFieldName = null;
            this.cmd.UpdatedRowSource = System.Data.UpdateRowSource.None;
            ((System.ComponentModel.ISupportInitialize)(this.InfoConnection1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustDrop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RTLessorAVSCustDropSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustDrop)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.View_RTLessorAVSCustDropSndwork)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RT10451)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10451)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10452)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10453)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10455)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10454)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10456)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10457)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10458)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT10459)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmdRT1045A)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.cmd)).EndInit();

        }

        #endregion

        private Srvtools.ServiceManager serviceManager1;
        private Srvtools.InfoConnection InfoConnection1;
        private Srvtools.InfoCommand RTLessorAVSCustDrop;
        private Srvtools.UpdateComponent ucRTLessorAVSCustDrop;
        private Srvtools.InfoCommand RTLessorAVSCustDropSndwork;
        private Srvtools.UpdateComponent ucRTLessorAVSCustDropSndwork;
        private Srvtools.InfoCommand View_RTLessorAVSCustDrop;
        private Srvtools.InfoCommand View_RTLessorAVSCustDropSndwork;
        private Srvtools.InfoCommand RT10451;
        private Srvtools.InfoCommand cmdRT10451;
        private Srvtools.InfoCommand cmdRT10452;
        private Srvtools.InfoCommand cmdRT10453;
        private Srvtools.InfoCommand cmdRT10455;
        private Srvtools.InfoCommand cmdRT10454;
        private Srvtools.InfoCommand cmdRT10456;
        private Srvtools.InfoCommand cmdRT10457;
        private Srvtools.InfoCommand cmdRT10458;
        private Srvtools.InfoCommand cmdRT10459;
        private Srvtools.InfoCommand cmdRT1045A;
        private Srvtools.InfoCommand cmd;
    }
}
